# 04-ex

1. Reductions

Find the total mean, and the mean for each row and column of the following matrix:

m = np.arange(12).reshape((3,4))



In [1]:
import numpy as np
m = np.arange(12).reshape((3,4))
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
total_mea = np.mean(m)

#did this to every row
row1 = np.mean(m[0])
row2 = np.mean(m[0])
row3 = np.mean(m[0])


#and for every column
col1 = np.mean(m[:,0])
col2 = np.mean(m[:,1])
col3 = np.mean(m[:,2])
col4 = np.mean(m[:,3])

print("Total mean: "+str(total_mea))
print("Row1 mean: "+str(row1))
print("Row2 mean: "+str(row2))
print("Row3 mean: "+str(row3))
print("Column1 mean: "+str(col1))
print("Column2 mean: "+str(col2))
print("Column3 mean: "+str(col3))
print("Column4 mean: "+str(col4))

Total mean: 5.5
Row1 mean: 1.5
Row2 mean: 1.5
Row3 mean: 1.5
Column1 mean: 4.0
Column2 mean: 5.0
Column3 mean: 6.0
Column4 mean: 7.0


2\. **Outer product**

Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [4]:
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])

#1
num_out = np.outer(u,v)

print("1. Using the function outer in numpy: \n"+str(num_out))


#2
mul = []  
for element_u in u: 
    mul2 = [] 
    for element_v in v:
        mul2.append(element_u*element_v) 
    mul.append(mul2)
mul = np.array(mul)


print("2. Using a nested for loop: \n"+str(mul))
#3 

list_comp = np.array([items_u*items_v for items_u in u for items_v in v]).reshape(4,4) #I had to reshape it

print("3. Using a list comprehension: \n"+str(list_comp))

#4

print("4. Using numpy broadcasting operations \n"+str(u*v.reshape(4,1)))


1. Using the function outer in numpy: 
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
2. Using a nested for loop: 
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
3. Using a list comprehension: 
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
4. Using numpy broadcasting operations 
[[ 2  6 10 14]
 [ 4 12 20 28]
 [ 6 18 30 42]
 [ 8 24 40 56]]


3\. **Matrix masking**

Create a 10 by 6 matrix of float random numbers, distributed between 0 and 3 according to a flat distribution.

After creating the matrix, set all entries $< 0.3$ to zero using a mask.

In [2]:
a = np.random.rand(10,6) * 3
print(a)

for row in a:
    for ind, ele in enumerate(row):
        row[ind] = 1 if ele>0.3 else 0
print(a)

[[0.49693753 2.84049614 0.89944048 1.61790711 0.90226374 1.86300704]
 [0.08795128 2.241662   2.58181591 0.40242573 0.289146   1.85710126]
 [0.26799748 2.8995027  0.59422747 0.38495511 0.03274657 0.83738643]
 [0.68882438 1.56139699 2.48028461 0.95756899 0.79676468 0.88929947]
 [0.15227417 2.72431981 2.57639085 1.6901189  0.41102968 0.11752062]
 [2.03240578 2.05512515 2.22530194 1.73497518 1.29178579 1.13992833]
 [0.93435836 0.15644082 0.56976389 1.16603323 1.31601077 0.42102856]
 [2.33203074 2.52738095 0.9667389  0.42478089 0.87002534 0.61504154]
 [0.84060957 1.96238655 1.1283999  0.33052573 1.52534432 2.13061576]
 [2.87196707 2.0023544  1.20076255 2.67009784 0.89357531 2.38201557]]
[[1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 0. 1.]
 [0. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


4\. **Trigonometric functions**

Use `np.linspace` to create an array of 100 numbers between $0$ and $2\pi$ (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the `sin` and `cos` functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

In [5]:
arr1 = np.linspace(start = 0, stop = np.pi*2, num=100, endpoint=True, retstep=False, dtype=None, axis=0)
arr_reversed = arr1[::-1]
print("Reverse the array using the slice notation \n" +str(arr_reversed))
arr_10th = arr1[::10]
print("Extract every 10th element using the slice notation \n"+str(arr_10th))

arr_sin_cos = np.where(np.absolute(np.sin(arr1)-np.cos(arr1))<0.1,arr1,None)

arr_sin_cos = set(arr_sin_cos)
arr_sin_cos.remove(None)
print("Extracted elements absolute difference between the sin and cos functions evaluated for that element is  <0.1: \n"+ str(arr_sin_cos))

Reverse the array using the slice notation 
[6.28318531 6.21971879 6.15625227 6.09278575 6.02931923 5.96585272
 5.9023862  5.83891968 5.77545316 5.71198664 5.64852012 5.58505361
 5.52158709 5.45812057 5.39465405 5.33118753 5.26772102 5.2042545
 5.14078798 5.07732146 5.01385494 4.95038842 4.88692191 4.82345539
 4.75998887 4.69652235 4.63305583 4.56958931 4.5061228  4.44265628
 4.37918976 4.31572324 4.25225672 4.1887902  4.12532369 4.06185717
 3.99839065 3.93492413 3.87145761 3.8079911  3.74452458 3.68105806
 3.61759154 3.55412502 3.4906585  3.42719199 3.36372547 3.30025895
 3.23679243 3.17332591 3.10985939 3.04639288 2.98292636 2.91945984
 2.85599332 2.7925268  2.72906028 2.66559377 2.60212725 2.53866073
 2.47519421 2.41172769 2.34826118 2.28479466 2.22132814 2.15786162
 2.0943951  2.03092858 1.96746207 1.90399555 1.84052903 1.77706251
 1.71359599 1.65012947 1.58666296 1.52319644 1.45972992 1.3962634
 1.33279688 1.26933037 1.20586385 1.14239733 1.07893081 1.01546429
 0.95199777 0.888531

5\. **Matrices**

Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [6]:
ten_by_ten = np.arange(1,11)
ten_by_ten = ten_by_ten*ten_by_ten[:,None]

print("10x10 matrix: \n"+str(ten_by_ten))
trace = np.trace(ten_by_ten)



flipped = np.fliplr(ten_by_ten) #flipped it

anti_diag = np.diag(flipped) 
print("Anti-Diagonal Matrix: \n"+str(anti_diag))

one_upwards = [ten_by_ten[i][i-1] for i in range(1,len(ten_by_ten))]
print("diagonal offset by 1 upwards Matrix: \n"+str(one_upwards))

10x10 matrix: 
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
Anti-Diagonal Matrix: 
[10 18 24 28 30 30 28 24 18 10]
diagonal offset by 1 upwards Matrix: 
[2, 6, 12, 20, 30, 42, 56, 72, 90]


6\. **Broadcasting**

Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles.

The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [7]:
cities = [ "Chicago", "Springfield", "Saint-Louis", "Tulsa", "Oklahoma City", "Amarillo","Santa Fe", "Albuquerque", "Flagstaff", "Los Angeles"]
distances = [0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448]
grid = np.tile(distances,len(distances))

print("2D grid:")
grid

2D grid:


array([   0,  198,  303,  736,  871, 1175, 1475, 1544, 1913, 2448,    0,
        198,  303,  736,  871, 1175, 1475, 1544, 1913, 2448,    0,  198,
        303,  736,  871, 1175, 1475, 1544, 1913, 2448,    0,  198,  303,
        736,  871, 1175, 1475, 1544, 1913, 2448,    0,  198,  303,  736,
        871, 1175, 1475, 1544, 1913, 2448,    0,  198,  303,  736,  871,
       1175, 1475, 1544, 1913, 2448,    0,  198,  303,  736,  871, 1175,
       1475, 1544, 1913, 2448,    0,  198,  303,  736,  871, 1175, 1475,
       1544, 1913, 2448,    0,  198,  303,  736,  871, 1175, 1475, 1544,
       1913, 2448,    0,  198,  303,  736,  871, 1175, 1475, 1544, 1913,
       2448])

In [8]:
# 1 mile = 1.609344 km


f = lambda x: x * 1.609344

print("Km Grid:")
km_grid = np.array([i*1.609344 for i in grid]).reshape(grid.shape)
km_grid

Km Grid:


array([   0.      ,  318.650112,  487.631232, 1184.477184, 1401.738624,
       1890.9792  , 2373.7824  , 2484.827136, 3078.675072, 3939.674112,
          0.      ,  318.650112,  487.631232, 1184.477184, 1401.738624,
       1890.9792  , 2373.7824  , 2484.827136, 3078.675072, 3939.674112,
          0.      ,  318.650112,  487.631232, 1184.477184, 1401.738624,
       1890.9792  , 2373.7824  , 2484.827136, 3078.675072, 3939.674112,
          0.      ,  318.650112,  487.631232, 1184.477184, 1401.738624,
       1890.9792  , 2373.7824  , 2484.827136, 3078.675072, 3939.674112,
          0.      ,  318.650112,  487.631232, 1184.477184, 1401.738624,
       1890.9792  , 2373.7824  , 2484.827136, 3078.675072, 3939.674112,
          0.      ,  318.650112,  487.631232, 1184.477184, 1401.738624,
       1890.9792  , 2373.7824  , 2484.827136, 3078.675072, 3939.674112,
          0.      ,  318.650112,  487.631232, 1184.477184, 1401.738624,
       1890.9792  , 2373.7824  , 2484.827136, 3078.675072, 3939.

7\. **Prime numbers sieve**

Compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).

  * Constract a shape (N,) boolean array, which is the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (with `timeit`); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [9]:
def prime_computer(N):
    
    tmp = np.ones(N, dtype=bool)
    tmp[0] = tmp[1] = False
    for i in range(2, N):
        if tmp[i]: 
            tmp[i*i::i] = False
    return np.flatnonzero(tmp)

In [10]:
import timeit

start_time = timeit.default_timer()
prime_computer(100)
print("N=100 time(sec): "+str(timeit.default_timer() - start_time))
print(prime_computer(100))

N=100 time(sec): 0.0001510459997007274
[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97]


In [11]:
start_time = timeit.default_timer()
prime_computer(1000000)
print("N=1000000 time(sec): "+str(timeit.default_timer() - start_time))
print(prime_computer(1000000))

N=1000000 time(sec): 0.14733143100011148
[     2      3      5 ... 999961 999979 999983]


8\. **Diffusion using random walk**

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of many random walkers after a given amount of time.

*Hint*: create a 2D array where each row represents a walker, and each column represents a time step.

  * Take 1000 walkers and let them walk for 200 steps
  * Use `randint` to create a 2D array of size $walkers \times steps$ with values -1 or 1
  * Calculate the walking distances for each walker (e.g. by summing the elements in each row)
  * Take the square of the previously-obtained array (element-wise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * **Optional**: plot the average distances ($\sqrt(distance^2)$) as a function of time (step)