1\. **Reductions**

Find the total mean, and the mean for each row and column of the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [2]:
import numpy as np
m = np.arange(12).reshape((3,4))
totalMean =  np.mean(m)

print(f"Total mean: {totalMean}")

rowMean = np.mean(m, axis=1)
print(f"Row mean: {rowMean}")

columnMean = np.mean(m, axis=0)
print(f"Column mean: {columnMean}")

Total mean: 5.5
Row mean: [1.5 5.5 9.5]
Column mean: [4. 5. 6. 7.]


2\. **Outer product**

Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [ ]:
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])

# outer product utilizzando numpy.outer
outer_np = np.outer(u,v)
print(f"Outer product with numpy.outer: \n{outer_np}")

# outer product utilizzando un ciclo for
outer_for = []
for a in u:
    for b in v:
        outer_for.append(a*b)
        
outer_for = (np.array(outer_for)).reshape(4,4)
print(f"\nOuter product with for loop: \n{outer_for}")

# outer product utilizzando broadcast
outer_broad = []
for a in u:
    outer_broad.append(list(a*v))
    
outer_broad = (np.array(outer_broad)).reshape(4,4)
print(f"\nOuter product with outer_broad: \n{outer_broad}")

3\. **Matrix masking**

Create a 10 by 6 matrix of float random numbers, distributed between 0 and 3 according to a flat distribution.

After creating the matrix, set all entries $< 0.3$ to zero using a mask.

In [63]:
matr = np.random.uniform(0,3,[10,6])
print(f"Matrix: \n{matr}")

#creo la maschera
mask = (matr < 0.3)

#applico la maschera
matr[mask] = 0
print(f"\nMatrix with mask (<0.3 -> 0):\n{matr}")

Matrix: 
[[2.54259687 1.2256034  2.83485302 1.32010776 2.73101691 1.21554214]
 [0.725859   2.90850041 2.10683247 0.72281341 2.18182571 2.26351804]
 [0.24318785 0.39856062 0.47932214 2.28412612 2.51696816 2.51809352]
 [1.11230083 2.47862606 1.44768713 0.69515997 2.33119696 0.64374676]
 [1.7343956  0.02606463 2.40525603 0.2362515  2.00550462 2.56558913]
 [2.42098718 0.2159788  2.69426043 2.55734044 1.40973847 2.65039306]
 [2.31020783 2.62459532 0.79436774 0.40050615 0.55372718 0.64661434]
 [0.33573277 0.48677609 0.41516987 0.04875139 2.58716958 1.73954199]
 [1.58526314 2.39810936 0.80857114 1.26485869 0.94520981 2.66050975]
 [1.69258175 0.90083442 2.49267428 2.39186743 2.05129748 1.85898565]]

Matrix with mask (<0.3 -> 0):
[[2.54259687 1.2256034  2.83485302 1.32010776 2.73101691 1.21554214]
 [0.725859   2.90850041 2.10683247 0.72281341 2.18182571 2.26351804]
 [0.         0.39856062 0.47932214 2.28412612 2.51696816 2.51809352]
 [1.11230083 2.47862606 1.44768713 0.69515997 2.33119696 0.643

4\. **Trigonometric functions**

Use `np.linspace` to create an array of 100 numbers between $0$ and $2\pi$ (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the `sin` and `cos` functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

In [98]:
import math
ar = np.linspace(0,2*math.pi,100)
print(f"Original array:\n {ar}")

slice_ar = vec[0:100:10]
print(f"\nSlice elem array:\n {slice_ar}")

rev_ar = ar[::-1]
print(f"\nReverse array:\n {rev_ar}")

mask = (abs(np.sin(ar)-np.cos(ar))<0.1)
abs_ar = ar[mask] 
print(f"\nAbs of sin-cos of array<0.1:\n {abs_ar}")

Original array:
 [0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.

5\. **Matrices**

Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [25]:
#creo la matrice delle moltiplicazioni
rng = np.arange(1, 10+1)
mult_table = rng * rng[:, None]
print(f"10 by 10 multiplication table: \n{mult_table}")

#trace della matrice
trace_m = np.trace(mult_table)
print(f"\nTrace of the matrix: {trace_m}")

#estraggo l'anti-diagonale della matrice
ant_diag = np.fliplr(mult_table).diagonal() #prima inverto la matrice left-right poi estraggo la diagonale
print(f"\nAnti-diagonal matrix: {ant_diag}")

#estraggo la diagonale della matrice con offset 1
off_diag = mult_table.diagonal(1)
print(f"\nDiagonal offset by 1 upwards: {off_diag}")

10 by 10 multiplication table: 
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]

Trace of the matrix: 385

Anti-diagonal matrix: [10 18 24 28 30 30 28 24 18 10]

Diagonal offset by 1 upwards: [ 2  6 12 20 30 42 56 72 90]


6\. **Broadcasting**

Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles.

The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [26]:
pos_miles = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])
print(pos_miles)

[   0  198  303  736  871 1175 1475 1544 1913 2448]


7\. **Prime numbers sieve**

Compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).

  * Constract a shape (N,) boolean array, which is the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (with `timeit`); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [114]:
import math
import timeit

#funzione che calcola se un numero è primo (True-False)
def is_prime(n):
    if n % 2 == 0 and n > 2: 
        return False
    return all(n % i for i in range(3, int(math.sqrt(n)) + 1, 2))

#funzione che restituisce un vettore di numeri primi contenuti nel vettore 1-N 
def calc_prime(N):
    vec = np.arange(1, N)
    mask = (vec<0)
    for i in range(vec.size):
        if (is_prime(vec[i])):
            mask[i]=True
    prime_vec=vec[mask]
    return prime_vec

#calcolo e stampo le prestazioni al variare di N
for x in range (100, 20000, 1000):
    time = timeit.timeit(stmt='calc_prime(x)', globals=globals(), number=1)
    print(f"performances with N={x}: {time}")
#--> aumentando N il tempo di esecuzione aumenta

def calc_prime_er(N):
    vec = np.arange(1, N)
    mask = (vec>0)
    #caso base con 1
    #caso base con 2
    for i in range(1,vec.size,1):
        #print(f"\n{vec[i]}\n")
        if vec[i]%2==0:
            mask[i]=False
            
    for i in range(2,vec.size,1):
        for m in range(2,vec.size,1):
            if vec[m]%i==0:
                mask[i]=False
    mask[0]=True
    prime_vec=vec[mask]
    print(mask)
    return prime_vec

print(f"TEST: {calc_prime_er(100)}")
            

performances with N=100: 0.00013419999959296547
performances with N=1100: 0.0010781999999380787
performances with N=2100: 0.001971199999388773
performances with N=3100: 0.0025294999995821854
performances with N=4100: 0.0034789000001183013
performances with N=5100: 0.006446600000344915
performances with N=6100: 0.006265499999244639
performances with N=7100: 0.006985300000451389
performances with N=8100: 0.009897400000227208
performances with N=9100: 0.009755099999892991
performances with N=10100: 0.010563599999841244
performances with N=11100: 0.01983490000020538
performances with N=12100: 0.021709399999963352
performances with N=13100: 0.018223300000499876
performances with N=14100: 0.015847300000132236
performances with N=15100: 0.015343799999754992
performances with N=16100: 0.017117299999881652
performances with N=17100: 0.017895999999382184
performances with N=18100: 0.018820700000105717
performances with N=19100: 0.019806700000117416

2


3


4


5


6


7


8


9


10


11


12



8\. **Diffusion using random walk**

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of many random walkers after a given amount of time.

*Hint*: create a 2D array where each row represents a walker, and each column represents a time step.

  * Take 1000 walkers and let them walk for 200 steps
  * Use `randint` to create a 2D array of size $walkers \times steps$ with values -1 or 1
  * Calculate the walking distances for each walker (e.g. by summing the elements in each row)
  * Take the square of the previously-obtained array (element-wise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * **Optional**: plot the average distances ($\sqrt(distance^2)$) as a function of time (step)