1\. **Reductions**

Find the total mean, and the mean for each row and column of the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [1]:
import numpy as np

In [11]:
m = np.arange(12).reshape((3,4))
print("The matrix is \n",m)

total_mean = np.mean(m)
print("The total mean of matrix is:", total_mean)

counter = 1
for i in m:
    row_mean = np.mean(i)
    print("Mean of the row ",counter,"is", str(row_mean))
    counter+=1

m_transpose = np.transpose(m)
counter = 1
for i in m_transpose:
    col_mean = np.mean(i)
    print("Mean of the column ",counter,"is", str(col_mean))
    counter+=1

The matrix is 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
The total mean of matrix is: 5.5
Mean of the row  1 is 1.5
Mean of the row  2 is 5.5
Mean of the row  3 is 9.5
Mean of the column  1 is 4.0
Mean of the column  2 is 5.0
Mean of the column  3 is 6.0
Mean of the column  4 is 7.0


2\. **Outer product**

Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [20]:
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])

#Using the function outer in numpy
outer_1 = np.outer(u,v)
print("Outer product using the function outer in numpy: \n", outer_1)

#Using a nested for loop or a list comprehension
outer_2 = np.ones((4,4))
row_counter, col_counter = 0,0
for i in u:
    for j in v:
        outer_2[row_counter][col_counter] = i*j
        col_counter += 1
    col_counter = 0
    row_counter+=1
print("Outer product Using a nested for loop: \n", outer_2)

#Using numpy broadcasting operations
outer_3 = u[:,np.newaxis]*v
print("Outer product using numpy broadcasting operations: \n", outer_3)

Outer product using the function outer in numpy: 
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
Outer product Using a nested for loop: 
 [[ 2.  4.  6.  8.]
 [ 6. 12. 18. 24.]
 [10. 20. 30. 40.]
 [14. 28. 42. 56.]]
Outer product using numpy broadcasting operations: 
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. **Matrix masking**

Create a 10 by 6 matrix of float random numbers, distributed between 0 and 3 according to a flat distribution.

After creating the matrix, set all entries $< 0.3$ to zero using a mask.

In [23]:
m = np.random.uniform(0,3,(10,6))
print("Obtained Matrix: \n",m)

mask = ( m > 0.3 )
n = np.zeros((10,6)) + m*np.logical_and(mask, m) 
print("\nFiltered Matrix: \n",n)

Obtained Matrix: 
 [[0.89224996 2.12439211 1.36171797 2.89137254 0.6605666  0.05409115]
 [2.88881975 1.99457193 1.85904469 1.25353053 1.42029063 1.34747002]
 [2.3536179  2.94287243 2.63168251 0.20767251 2.63694672 1.26582261]
 [0.62794757 2.15077381 2.52499497 1.25900911 2.8034578  2.23338957]
 [1.18610589 0.16287606 1.63248749 2.28594949 1.2056349  2.26806644]
 [0.68706339 0.93154442 2.9727125  2.9419251  2.73282212 1.27612633]
 [0.832314   1.28049738 2.7547028  1.30261168 0.65858882 1.22889995]
 [2.26671664 2.65113126 0.3851265  1.35413944 1.49923876 0.88174617]
 [2.27376805 0.83004833 2.61385349 1.89434615 1.7352629  1.35025195]
 [2.03035209 0.77829164 0.15959353 2.7373909  0.12043613 1.34735944]]

Filtered Matrix: 
 [[0.89224996 2.12439211 1.36171797 2.89137254 0.6605666  0.        ]
 [2.88881975 1.99457193 1.85904469 1.25353053 1.42029063 1.34747002]
 [2.3536179  2.94287243 2.63168251 0.         2.63694672 1.26582261]
 [0.62794757 2.15077381 2.52499497 1.25900911 2.8034578  2.2333

4\. **Trigonometric functions**

Use `np.linspace` to create an array of 100 numbers between $0$ and $2\pi$ (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the `sin` and `cos` functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

In [44]:
import math

m = np.linspace(0, 2*math.pi, 100)
#print("The array is:", m)

m_10 = m[::9]
print("\nThe every 10th element in matrice: ",m_10)

m_rev = m[::-1]
print("\nThe reverse of the matrice:", m_rev)

m_list = [m[i] for i in range(100) if 
          (abs(math.sin(m[i]) - math.cos(m[i])) < 0.1)]
print("\nThe list of elements where |sin-cos|<0.1:", m_list)


The every 10th element in matrice:  [0.         0.57119866 1.14239733 1.71359599 2.28479466 2.85599332
 3.42719199 3.99839065 4.56958931 5.14078798 5.71198664 6.28318531]

The reverse of the matrice: [6.28318531 6.21971879 6.15625227 6.09278575 6.02931923 5.96585272
 5.9023862  5.83891968 5.77545316 5.71198664 5.64852012 5.58505361
 5.52158709 5.45812057 5.39465405 5.33118753 5.26772102 5.2042545
 5.14078798 5.07732146 5.01385494 4.95038842 4.88692191 4.82345539
 4.75998887 4.69652235 4.63305583 4.56958931 4.5061228  4.44265628
 4.37918976 4.31572324 4.25225672 4.1887902  4.12532369 4.06185717
 3.99839065 3.93492413 3.87145761 3.8079911  3.74452458 3.68105806
 3.61759154 3.55412502 3.4906585  3.42719199 3.36372547 3.30025895
 3.23679243 3.17332591 3.10985939 3.04639288 2.98292636 2.91945984
 2.85599332 2.7925268  2.72906028 2.66559377 2.60212725 2.53866073
 2.47519421 2.41172769 2.34826118 2.28479466 2.22132814 2.15786162
 2.0943951  2.03092858 1.96746207 1.90399555 1.84052903 1.77706

5\. **Matrices**

Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [54]:
m = np.arange(1, 11)
n = m[:,np.newaxis]*m
print(n)
print("The trace of the matrix: ", np.matrix.trace(n))
n_rev = n[::-1]
print("The anti-diagonal matrix: ", np.matrix.diagonal(n[::-1]))
print("The diagonal with offset by 1: ", np.matrix.diagonal(n,offset=1))

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
The trace of the matrix:  385
The anti-diagonal matrix:  [10 18 24 28 30 30 28 24 18 10]
The diagonal with offset by 1:  [ 2  6 12 20 30 42 56 72 90]


6\. **Broadcasting**

Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles.

The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [57]:
miles = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])
factor = 1.609
kms = np.array([i*factor for i in miles])

dist_miles = abs(miles[:,np.newaxis]-miles)
print("The distance between cities in miles: \n",dist_miles)
dist_km = np.round(abs(kms[:,np.newaxis]-kms),1)
print("The distance between cities in kms: \n",dist_km)

The distance between cities in miles: 
 [[   0  198  303  736  871 1175 1475 1544 1913 2448]
 [ 198    0  105  538  673  977 1277 1346 1715 2250]
 [ 303  105    0  433  568  872 1172 1241 1610 2145]
 [ 736  538  433    0  135  439  739  808 1177 1712]
 [ 871  673  568  135    0  304  604  673 1042 1577]
 [1175  977  872  439  304    0  300  369  738 1273]
 [1475 1277 1172  739  604  300    0   69  438  973]
 [1544 1346 1241  808  673  369   69    0  369  904]
 [1913 1715 1610 1177 1042  738  438  369    0  535]
 [2448 2250 2145 1712 1577 1273  973  904  535    0]]
The distance between cities in kms: 
 [[   0.   318.6  487.5 1184.2 1401.4 1890.6 2373.3 2484.3 3078.  3938.8]
 [ 318.6    0.   168.9  865.6 1082.9 1572.  2054.7 2165.7 2759.4 3620.2]
 [ 487.5  168.9    0.   696.7  913.9 1403.  1885.7 1996.8 2590.5 3451.3]
 [1184.2  865.6  696.7    0.   217.2  706.4 1189.1 1300.1 1893.8 2754.6]
 [1401.4 1082.9  913.9  217.2    0.   489.1  971.8 1082.9 1676.6 2537.4]
 [1890.6 1572.  1403.   70

7\. **Prime numbers sieve**

Compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).

  * Constract a shape (N,) boolean array, which is the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (with `timeit`); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [65]:
import timeit
def prime(n):
    if n == 0:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
    return True
N = 99
m = np.arange(N)
starttime = timeit.default_timer()
mask = [prime(m[i]) for i in m] 
prime_numbers = m[mask]
endtime= timeit.default_timer() - starttime
print("Mask: ",mask)
print("Prime numbers: ",prime_numbers)
print("Execution time: ",endtime,"seconds")


Mask:  [False, True, True, True, False, True, False, True, False, False, False, True, False, True, False, False, False, True, False, True, False, False, False, True, False, False, False, False, False, True, False, True, False, False, False, False, False, True, False, False, False, True, False, True, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, True, False, True, False, False, False, False, False, True, False, False, False, True, False, True, False, False, False, False, False, True, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, True, False]
Prime numbers:  [ 1  2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83
 89 97]
Execution time:  0.000739299925044179 seconds


8\. **Diffusion using random walk**

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of many random walkers after a given amount of time.

*Hint*: create a 2D array where each row represents a walker, and each column represents a time step.

  * Take 1000 walkers and let them walk for 200 steps
  * Use `randint` to create a 2D array of size $walkers \times steps$ with values -1 or 1
  * Calculate the walking distances for each walker (e.g. by summing the elements in each row)
  * Take the square of the previously-obtained array (element-wise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * **Optional**: plot the average distances ($\sqrt(distance^2)$) as a function of time (step)

In [88]:
m = np.random.randint(-1,2,(1000, 200)) # random matric to describe 1000 walkers and their 200 steps
m[m == 0] = -1
print("The random matric: \n",m)
distance = m.sum(axis=1) 
#print("The distance covered by each walker is \n",distance)
square_distance=np.square(distances)
#print("The square of the distance covered by each walker is \n", square_distance)
mean_steps=square_distance.mean(axis=0)
#print("The mean of distances at each step is \n", mean_steps)

The random matric: 
 [[-1 -1 -1 ... -1 -1 -1]
 [ 1 -1 -1 ... -1  1 -1]
 [-1 -1 -1 ... -1 -1  1]
 ...
 [-1 -1  1 ... -1  1 -1]
 [ 1 -1 -1 ... -1  1 -1]
 [-1 -1 -1 ... -1 -1 -1]]
