1\. **Reductions**

Find the total mean, and the mean for each row and column of the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [12]:
import numpy as np
m = np.arange(12).reshape((3,4))
print(m, '\n')

(rig, col) = m.shape

rig_means = []
col_means = []
somma = 0

for i in range(rig):
    rig_means.append(sum(m[i,:])/col)
    somma += sum(m[i,:])
    
total_mean = somma/(rig*col)

for j in range(col): 
    col_means.append(sum(m[:,j]/rig))

print('The total mean of the matrix is: ', total_mean, '\n')
for i in range(rig):
    print('The mean for the row ',str(i+1), 'is: ', rig_means[i], '\n')
for j in range(col):
    print('The mean for the column ', str(j+1),'is: ', col_means[j], '\n' )


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

The total mean of the matrix is:  5.5 

The mean for the row  1 is:  1.5 

The mean for the row  2 is:  5.5 

The mean for the row  3 is:  9.5 

The mean for the column  1 is:  4.0 

The mean for the column  2 is:  5.0 

The mean for the column  3 is:  6.0 

The mean for the column  4 is:  7.0 



2\. **Outer product**

Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [18]:
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])

#Method 1
product1 = np.outer(u,v)
print('Outer product found using the function outer: \n', product1, '\n')

#Method 2
def outer_loop(u,v):
    product2 = []
    for el_u in u:
        product_rig = [el_u*el_v for el_v in v]
        product2.append(product_rig)
    return np.array(product2)

product2 = outer_loop(u,v)
print('Outer product found using the for loop and list comprehension: \n', product2, '\n')

#Method 3
product3 = u[:,np.newaxis]*v
print('Outer product found using the numpy broadcasting operations : \n', product3, '\n')

Outer product found using the function outer: 
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]] 

Outer product found using the for loop and list comprehension: 
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]] 

Outer product found using the numpy broadcasting operations : 
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]] 



3\. **Matrix masking**

Create a 10 by 6 matrix of float random numbers, distributed between 0 and 3 according to a flat distribution.

After creating the matrix, set all entries $< 0.3$ to zero using a mask.

In [40]:
import numpy.random as npr

m = np.random.uniform(0,3,(10,6))
print('Matrix of float random number: \n', m, '\n')

mask = ( m > 0.3 )
m_filtered = np.zeros((10,6)) + m*np.logical_and(mask, m) 
print('Matrix filtered using the mask: \n', m_filtered, '\n')

Matrix of float random number: 
 [[1.11262727 2.77857323 1.74580345 0.68511136 1.56923407 0.11876504]
 [1.38394566 1.36148266 2.08408146 2.60312058 1.75086207 1.01563238]
 [1.14371024 0.21589454 0.48626977 1.29521716 0.12970165 2.05489995]
 [0.06621416 1.61068157 2.07817691 0.91762147 1.97752039 1.78868558]
 [0.88297099 0.83458565 2.29985418 0.32035187 2.959694   1.55343336]
 [2.51477115 2.05443265 1.48500085 0.87268164 2.17206198 0.62497984]
 [1.32096186 0.58874211 1.66951405 1.98147655 1.61200516 0.05920478]
 [0.12590772 1.45298261 2.42977391 1.7798152  0.99019082 1.51669932]
 [0.84892129 0.95378647 1.45388273 2.3369125  2.41620598 0.29941984]
 [2.51347191 1.32347396 1.73434022 1.42265616 0.34407692 2.0988741 ]] 

Matrix filtered using the mask: 
 [[1.11262727 2.77857323 1.74580345 0.68511136 1.56923407 0.        ]
 [1.38394566 1.36148266 2.08408146 2.60312058 1.75086207 1.01563238]
 [1.14371024 0.         0.48626977 1.29521716 0.         2.05489995]
 [0.         1.61068157 2.0781769

4\. **Trigonometric functions**

Use `np.linspace` to create an array of 100 numbers between $0$ and $2\pi$ (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the `sin` and `cos` functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

In [71]:
import math

t = np.linspace(0,2*math.pi, 100)
n = []
i = 0

while True:
    try: 
        n.append(t[10*i])
        i += 1
    except:
        break

n = np.array(n)
n_inverted = n.copy()
for i in range(n.shape[0]):
    n_inverted[n.shape[0]-1-i] = n[i]
n = n_inverted

l = []

for el in n:
    print(abs(np.sin(el) - np.cos(el)))
    if abs(np.sin(el) - np.cos(el)) < 0.1:
        l.append(el)

print(l) #è vuota...non ce n'è nessuno


-1.3818943502867786
-1.2910340818569783
-0.6973683448699075
0.16789410852218212
0.9677686088851172
1.3907364452926037
1.2720687820320902
0.657981866115799
-0.21236232847641823
-1.0
[]


5\. **Matrices**

Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

6\. **Broadcasting**

Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles.

The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

7\. **Prime numbers sieve**

Compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).

  * Constract a shape (N,) boolean array, which is the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (with `timeit`); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

8\. **Diffusion using random walk**

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of many random walkers after a given amount of time.

*Hint*: create a 2D array where each row represents a walker, and each column represents a time step.

  * Take 1000 walkers and let them walk for 200 steps
  * Use `randint` to create a 2D array of size $walkers \times steps$ with values -1 or 1
  * Calculate the walking distances for each walker (e.g. by summing the elements in each row)
  * Take the square of the previously-obtained array (element-wise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * **Optional**: plot the average distances ($\sqrt(distance^2)$) as a function of time (step)