1\. **Reductions**

Find the total mean, and the mean for each row and column of the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [53]:
import numpy as np
m = np.arange(12).reshape((3,4))
print("Total mean:" , m.mean())
cm= np.mean(m,axis=0)
rm= np.mean(m,axis=1)
print("columns mean:",cm)
print("rows mean:",rm)
    

Total mean: 5.5
columns mean: [4. 5. 6. 7.]
rows mean: [1.5 5.5 9.5]


2\. **Outer product**

Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [55]:
#1
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
out=np.outer(u,v)
print ('1:\n',out,'\n\n')
#3

u_v =u * v.reshape(4,1)
print('3:\n',u_v.T)



1:
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]] 


3:
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. **Matrix masking**

Create a 10 by 6 matrix of float random numbers, distributed between 0 and 3 according to a flat distribution.

After creating the matrix, set all entries $< 0.3$ to zero using a mask.

In [52]:

w=3*np.random.rand(10,6)
print('random 10*6 matrix is:\n\n',w,'\n\n')
w[w<0.3]=0
print ('after masking:\n\n',w)

random 10*6 matrix is:

 [[0.97465237 1.07830262 1.70698308 1.91266656 1.20016839 1.4824436 ]
 [1.86272459 1.74696461 2.12643313 0.10533255 0.75191367 2.54682211]
 [2.81741002 2.1061774  1.85023157 2.19490968 2.30567257 1.72100956]
 [2.088571   2.29009606 2.89110029 2.20745302 2.29835619 1.06133315]
 [1.08168643 2.77092259 2.39385422 1.0717632  1.83863768 0.16501889]
 [0.86382777 0.73423547 0.6300527  0.45253608 2.09041394 0.17160325]
 [0.56459734 2.28074496 2.55697246 0.70884556 2.18703875 1.12630141]
 [0.45654404 0.13670751 0.2240465  0.56205452 1.97454721 0.03209925]
 [1.43102836 1.31589158 2.80898028 1.32441877 2.85204709 0.08441458]
 [2.54692056 2.35690611 2.24496771 1.69378169 0.6137007  2.37778083]] 


after masking:

 [[0.97465237 1.07830262 1.70698308 1.91266656 1.20016839 1.4824436 ]
 [1.86272459 1.74696461 2.12643313 0.         0.75191367 2.54682211]
 [2.81741002 2.1061774  1.85023157 2.19490968 2.30567257 1.72100956]
 [2.088571   2.29009606 2.89110029 2.20745302 2.29835619 

4\. **Trigonometric functions**

Use `np.linspace` to create an array of 100 numbers between $0$ and $2\pi$ (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the `sin` and `cos` functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

In [80]:
import math
w=math.pi
h=np.linspace(0, 2*w, 100)
print('array is: \n',h,'\n\n')
print ('Extract every 10th element:\n',h[::10],'\n\n')
print ('Reverse the array:\n',h[::-1],'\n\n')
mask=abs(np.cos(h)-np.sin(h))<0.1
print ('absolute difference between the sin and cos functions evaluated for that element is  <0.1:\n',h[mask])


array is: 
 [0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505

5\. **Matrices**

Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [96]:
x = range(1,11)
y = range(1,11)

matrice = np.array([[i*j for j in x] for i in y])
print ("a matrix that shows the 10 by 10 multiplication table.\n",matrice,'\n\n')
print ('the trace of the matrix: \n',np.trace(matrice),'\n\n')
print ('anti-diagonal matrix:\n',np.fliplr(matrice).diagonal(),'\n\n')
print ('the diagonal offset by 1 upwards :\n',np.diagonal(matrice,1))

a matrix that shows the 10 by 10 multiplication table.
 [[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]] 


the trace of the matrix: 
 385 


anti-diagonal matrix:
 [10 18 24 28 30 30 28 24 18 10] 


the diagonal offset by 1 upwards :
 [ 2  6 12 20 30 42 56 72 90]


6\. **Broadcasting**

Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles.

The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [101]:
import numpy as np
pos=np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])
d= np.abs(pos-pos[:, np.newaxis])
print("distances:","\n",d,'\n\n')
d_km = d*1.609344
print("distance array in km:","\n" ,d_km.round(2))

distances: 
 [[   0  198  303  736  871 1175 1475 1544 1913 2448]
 [ 198    0  105  538  673  977 1277 1346 1715 2250]
 [ 303  105    0  433  568  872 1172 1241 1610 2145]
 [ 736  538  433    0  135  439  739  808 1177 1712]
 [ 871  673  568  135    0  304  604  673 1042 1577]
 [1175  977  872  439  304    0  300  369  738 1273]
 [1475 1277 1172  739  604  300    0   69  438  973]
 [1544 1346 1241  808  673  369   69    0  369  904]
 [1913 1715 1610 1177 1042  738  438  369    0  535]
 [2448 2250 2145 1712 1577 1273  973  904  535    0]] 


distance array in km: 
 [[   0.    318.65  487.63 1184.48 1401.74 1890.98 2373.78 2484.83 3078.68
  3939.67]
 [ 318.65    0.    168.98  865.83 1083.09 1572.33 2055.13 2166.18 2760.02
  3621.02]
 [ 487.63  168.98    0.    696.85  914.11 1403.35 1886.15 1997.2  2591.04
  3452.04]
 [1184.48  865.83  696.85    0.    217.26  706.5  1189.31 1300.35 1894.2
  2755.2 ]
 [1401.74 1083.09  914.11  217.26    0.    489.24  972.04 1083.09 1676.94
  2537.94]
 [189

7\. **Prime numbers sieve**

Compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).

  * Constract a shape (N,) boolean array, which is the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (with `timeit`); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [ ]:
import timeit

def Sieve(n):
    prime = [True for i in range(n + 1)]
    p = 2
    while (p * p <= n):
        if (prime[p] == True):   
            for i in range(p ** 2, n + 1, p):
                prime[i] = False
        p += 1
    prime[0]= False
    prime[1]= False
    for p in range(n + 1):
        if prime[p]:
            print (p) 
            
#The performance increase with greater N.
starttime = timeit.default_timer()
SieveOfEratosthenes(2000)
print("The time", timeit.default_timer() - starttime)

8\. **Diffusion using random walk**

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of many random walkers after a given amount of time.

*Hint*: create a 2D array where each row represents a walker, and each column represents a time step.

  * Take 1000 walkers and let them walk for 200 steps
  * Use `randint` to create a 2D array of size $walkers \times steps$ with values -1 or 1
  * Calculate the walking distances for each walker (e.g. by summing the elements in each row)
  * Take the square of the previously-obtained array (element-wise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * **Optional**: plot the average distances ($\sqrt(distance^2)$) as a function of time (step)

In [ ]:
u = 2 * np.random.randint(0, 2, size=(1000, 200))-1
print(u)
walking_distance = u.sum(1)
print("\n Walking distance for each walker:\n", u.sum(1))
walking_distances_square = np.square(walking_distance)
print("\n", walking_distances_square)
mean_distance_square = []
mean = 0
for i in walking_distances_square:
    mean += i
    mean_distance_square.append(np.mean(mean))
print("Mean:\n" , mean_distance_square)