1\. **Reductions**

Find the total mean, and the mean for each row and column of the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [1]:
import numpy as np
m = np.arange(12).reshape((3,4))
print(m)
print('The total mean : ', np.mean(m))
#Depending on the axis, we calculate a different mean
print('The mean of the colums :',  np.mean(m, axis = 0))
print('The mean of the rows :', np.mean(m, axis = 1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
The total mean :  5.5
The mean of the colums : [4. 5. 6. 7.]
The mean of the rows : [1.5 5.5 9.5]


2\. **Outer product**

Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [2]:
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
print("Using outer :\n ",  np.outer(u,v))

print("\nUsing a for loo :")
res = []
for i in u: 
    res.append(i*v)
print(np.array(res))
        
print("\nUsing numpy broadcasting operations : ",)
#we modify the u matrix from a line to a colum to use broadcasting operations
print(u[:,np.newaxis]*v)

Using outer :
  [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]

Using a for loo :
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]

Using numpy broadcasting operations : 
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. **Matrix masking**

Create a 10 by 6 matrix of float random numbers, distributed between 0 and 3 according to a flat distribution.

After creating the matrix, set all entries $< 0.3$ to zero using a mask.

In [3]:
import numpy.random as npr
#We use uniform function to have a flat distribution
a =  npr.uniform(size=(10,6), low = 0, high = 3)
print(a)

#we create mask for all numbers < 0.3
mask = (a < 0.3)
filtered_a = a[mask]
print("The filtered matrix : \n", filtered_a)


[[1.29931078 2.68578013 1.78679414 1.56828325 2.324032   2.01762828]
 [1.36159544 1.33709315 0.3623089  2.87363011 2.39323795 2.16464884]
 [1.82634929 2.65477515 0.62004893 2.29138293 0.46730573 1.97276648]
 [0.10064036 1.20090122 1.42073799 1.27714372 0.59938203 1.60934764]
 [0.2529698  0.32411232 2.13097785 0.17802561 1.79879893 0.52997031]
 [1.86319553 2.38402638 1.53728375 1.05379089 0.2162014  1.69864274]
 [2.44459443 0.04328986 1.24313611 1.05716794 2.83740535 0.65545036]
 [1.18910847 2.9351195  2.14828573 2.46066339 0.59075745 1.92701549]
 [2.88814178 1.85110492 2.24683094 2.04612353 0.97262746 0.97063679]
 [2.04283494 2.02823911 0.68354339 1.24501702 2.30129203 1.48078751]]
The filtered matrix : 
 [0.10064036 0.2529698  0.17802561 0.2162014  0.04328986]


4\. **Trigonometric functions**

Use `np.linspace` to create an array of 100 numbers between $0$ and $2\pi$ (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the `sin` and `cos` functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

In [5]:
import math

a = np.linspace(0,math.pi/2, 100)
print(a)
print("\nReverse : ", a[::-1])

[0.         0.01586663 0.03173326 0.04759989 0.06346652 0.07933315
 0.09519978 0.11106641 0.12693304 0.14279967 0.1586663  0.17453293
 0.19039955 0.20626618 0.22213281 0.23799944 0.25386607 0.2697327
 0.28559933 0.30146596 0.31733259 0.33319922 0.34906585 0.36493248
 0.38079911 0.39666574 0.41253237 0.428399   0.44426563 0.46013226
 0.47599889 0.49186552 0.50773215 0.52359878 0.53946541 0.55533203
 0.57119866 0.58706529 0.60293192 0.61879855 0.63466518 0.65053181
 0.66639844 0.68226507 0.6981317  0.71399833 0.72986496 0.74573159
 0.76159822 0.77746485 0.79333148 0.80919811 0.82506474 0.84093137
 0.856798   0.87266463 0.88853126 0.90439789 0.92026451 0.93613114
 0.95199777 0.9678644  0.98373103 0.99959766 1.01546429 1.03133092
 1.04719755 1.06306418 1.07893081 1.09479744 1.11066407 1.1265307
 1.14239733 1.15826396 1.17413059 1.18999722 1.20586385 1.22173048
 1.23759711 1.25346374 1.26933037 1.28519699 1.30106362 1.31693025
 1.33279688 1.34866351 1.36453014 1.38039677 1.3962634  1.412130

5\. **Matrices**

Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

6\. **Broadcasting**

Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles.

The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

7\. **Prime numbers sieve**

Compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).

  * Constract a shape (N,) boolean array, which is the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (with `timeit`); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

8\. **Diffusion using random walk**

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of many random walkers after a given amount of time.

*Hint*: create a 2D array where each row represents a walker, and each column represents a time step.

  * Take 1000 walkers and let them walk for 200 steps
  * Use `randint` to create a 2D array of size $walkers \times steps$ with values -1 or 1
  * Calculate the walking distances for each walker (e.g. by summing the elements in each row)
  * Take the square of the previously-obtained array (element-wise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * **Optional**: plot the average distances ($\sqrt(distance^2)$) as a function of time (step)