1\. **Reductions**

Find the total mean, and the mean for each row and column of the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [2]:
import numpy as np
#4.1
m = np.arange(12).reshape((3,4))
print(m)
print(m.mean())
print(m.mean(0))
print(m.mean(1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
5.5
[4. 5. 6. 7.]
[1.5 5.5 9.5]


2\. **Outer product**

Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [3]:
u = np.array([1, 3, 5, 7])
print(u)

v = np.array([2, 4, 6, 8])
print(v)
print(f' outerproduct solution:\n {np.outer(u, v, out=None)}')

s=[]
for i in u:
    sum = []
    for j in v:
        sum.append(i*j)
    s.append(sum) 

print(f'for loop solution:\n{ np.matrix(s)}')

import numpy as np
u = np.array([1, 3, 5, 7])
v = np.array([[2],[4],[6],[8]])

q=u*v
q_transpose = q.transpose()

print(f'Transposed Array:\n{q_transpose}')

[1 3 5 7]
[2 4 6 8]
 outerproduct solution:
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
for loop solution:
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
Transposed Array:
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. **Matrix masking**

Create a 10 by 6 matrix of float random numbers, distributed between 0 and 3 according to a flat distribution.

After creating the matrix, set all entries $< 0.3$ to zero using a mask.

In [4]:
matrix1=np.random.uniform(0, 3, (10, 6))
print(matrix1)

mask = (matrix1 <0.3 )
print("the mask:", mask, '\n')

filtered_matrix1 = matrix1[mask]

print("the filtered array:", filtered_matrix1, '\n')



print("are matrix1 and filtered_matrix1 the same object?", np.may_share_memory(matrix1, filtered_matrix1), '\n')


matrix1[matrix1 <0.3] = 0
print("the modified array:", matrix1, '\n')

[[0.08961864 1.93977022 1.69170439 1.99443709 2.38388255 1.74988123]
 [1.53829431 1.17261184 0.06770242 2.14812954 0.69302786 0.57172323]
 [2.56489907 1.87843125 2.90305329 1.79257289 0.28439423 2.22072591]
 [0.39165555 0.45562258 0.92116757 2.3574266  1.51625845 1.32772541]
 [1.30917829 2.83688512 1.63424832 0.9143567  0.49294293 0.6461275 ]
 [2.39822307 0.57644119 0.6644666  0.99564991 2.70332092 0.79653598]
 [2.2653033  0.45685304 1.90526217 0.42832406 1.38982849 0.92120261]
 [0.10601714 1.18152411 1.35684177 0.3704997  1.36950092 1.73041769]
 [2.25649789 1.31808081 2.8378279  2.96552016 1.15080866 1.15573535]
 [2.76244253 1.81599933 1.33354971 2.86014651 0.00602433 2.17315972]]
the mask: [[ True False False False False False]
 [False False  True False False False]
 [False False False False  True False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [ True False False False 

4\. **Trigonometric functions**

Use `np.linspace` to create an array of 100 numbers between $0$ and $2\pi$ (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the `sin` and `cos` functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

In [5]:

import math as mt
import numpy.random as npr

# or by number of points:
a=np.linspace(0, (2*mt.pi), 100) # start, end, num-points (convenient to plot a function, for example)
list_temp=[]
list_reverse=[]


list_temp=a
list_temp=a[0::10]
list_temp=list_temp[1:]
print(list_temp)

list_reverse=list_temp[::-1]
print(list_reverse)

list_final=[]
for a in list_reverse:
    if ((abs(mt.sin(a)))-(abs(mt.cos(a))))<=0:
        list_final.append(a)
                              
print(list_final)        
        

[0.63466518 1.26933037 1.90399555 2.53866073 3.17332591 3.8079911
 4.44265628 5.07732146 5.71198664]
[5.71198664 5.07732146 4.44265628 3.8079911  3.17332591 2.53866073
 1.90399555 1.26933037 0.63466518]
[5.711986642890533, 3.8079910952603555, 3.173325912716963, 2.53866073017357, 0.6346651825433925]


5\. **Matrices**

Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [6]:
import numpy as np

def mult_table(n):
    rng = np.arange(1, n+1)
    return rng * rng[:, None]

print("matrix is ")
print(mult_table(10))

a=mult_table(10).trace()
print("trace is",a)


flipped_arr = np.fliplr(mult_table(10))
print("anti-diagonal matrix is")
print(flipped_arr.diagonal())

print("diagonal matrix starting from 1st element is")

print(np.diagonal(mult_table(10), offset=1))

matrix is 
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
trace is 385
anti-diagonal matrix is
[10 18 24 28 30 30 28 24 18 10]
diagonal matrix starting from 1st element is
[ 2  6 12 20 30 42 56 72 90]


6\. **Broadcasting**

Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles.

The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [7]:

mileposts = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])

distance_array = np.abs(mileposts - mileposts[:, np.newaxis]) 

distance_array

print(distance_array)
km= (1.61*distance_array)
print(km)


[[   0  198  303  736  871 1175 1475 1544 1913 2448]
 [ 198    0  105  538  673  977 1277 1346 1715 2250]
 [ 303  105    0  433  568  872 1172 1241 1610 2145]
 [ 736  538  433    0  135  439  739  808 1177 1712]
 [ 871  673  568  135    0  304  604  673 1042 1577]
 [1175  977  872  439  304    0  300  369  738 1273]
 [1475 1277 1172  739  604  300    0   69  438  973]
 [1544 1346 1241  808  673  369   69    0  369  904]
 [1913 1715 1610 1177 1042  738  438  369    0  535]
 [2448 2250 2145 1712 1577 1273  973  904  535    0]]
[[   0.    318.78  487.83 1184.96 1402.31 1891.75 2374.75 2485.84 3079.93
  3941.28]
 [ 318.78    0.    169.05  866.18 1083.53 1572.97 2055.97 2167.06 2761.15
  3622.5 ]
 [ 487.83  169.05    0.    697.13  914.48 1403.92 1886.92 1998.01 2592.1
  3453.45]
 [1184.96  866.18  697.13    0.    217.35  706.79 1189.79 1300.88 1894.97
  2756.32]
 [1402.31 1083.53  914.48  217.35    0.    489.44  972.44 1083.53 1677.62
  2538.97]
 [1891.75 1572.97 1403.92  706.79  489.44    

7\. **Prime numbers sieve**

Compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).

  * Constract a shape (N,) boolean array, which is the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (with `timeit`); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [12]:
def SieveOfEratosthenes(num):
    prime = [True for i in range(num+1)]

    p = 2
    while (p * p <= num):        
        if (prime[p] == True):
  
            for i in range(p * p, num+1, p):
                prime[i] = False
        p += 1
    for p in range(2, num+1):
        if prime[p]:
            print(p)
  
  
if __name__ == '__main__':
    num = 99
    print("Following are the prime numbers smaller"),
    print("than or equal to", num)
    SieveOfEratosthenes(num)

Following are the prime numbers smaller
than or equal to 99
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97


8\. **Diffusion using random walk**

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of many random walkers after a given amount of time.

*Hint*: create a 2D array where each row represents a walker, and each column represents a time step.

  * Take 1000 walkers and let them walk for 200 steps
  * Use `randint` to create a 2D array of size $walkers \times steps$ with values -1 or 1
  * Calculate the walking distances for each walker (e.g. by summing the elements in each row)
  * Take the square of the previously-obtained array (element-wise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * **Optional**: plot the average distances ($\sqrt(distance^2)$) as a function of time (step)

In [8]:
n_stories = 1000 # number of walkers
t_max = 200
t = np.arange(t_max)
steps = 2 * np.random.randint(-1, 1, (n_stories, t_max)) +1
np.unique(steps)
print(steps)

dist = np.cumsum(steps, axis=1) # axis = 1: dimension of time >>> 

print(dist)

length = dist*dist

print(length)


mean=np.mean(length,axis=0)

print("mean is ", mean)

[[-1  1 -1 ...  1  1 -1]
 [ 1 -1  1 ... -1  1  1]
 [-1  1  1 ... -1  1 -1]
 ...
 [ 1 -1  1 ...  1 -1 -1]
 [-1 -1 -1 ...  1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]]
[[ -1   0  -1 ... -10  -9 -10]
 [  1   0   1 ... -14 -13 -12]
 [ -1   0   1 ... -10  -9 -10]
 ...
 [  1   0   1 ...  -8  -9 -10]
 [ -1  -2  -3 ...  16  15  14]
 [ -1  -2  -3 ...  20  19  18]]
[[  1   0   1 ... 100  81 100]
 [  1   0   1 ... 196 169 144]
 [  1   0   1 ... 100  81 100]
 ...
 [  1   0   1 ...  64  81 100]
 [  1   4   9 ... 256 225 196]
 [  1   4   9 ... 400 361 324]]
mean is  [  1.      1.968   2.992   4.108   5.064   6.396   7.408   8.528   9.792
  10.84   11.912  12.756  13.672  14.424  15.616  16.48   17.848  18.46
  19.816  20.536  22.04   23.54   24.928  25.792  26.224  27.128  28.272
  28.956  29.92   30.7    31.48   32.872  33.712  34.5    35.632  36.252
  36.632  36.944  37.856  38.992  39.68   40.668  42.064  42.832  43.336
  44.296  45.328  46.336  47.824  48.936  50.024  51.012  51.576  52.208
  53.264  54.8