1\. **Reductions**

Find the total mean, and the mean for each row and column of the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [47]:
import numpy as np 
m = np.arange(12).reshape((3,4))
print(m)
print("mean:", m.mean())
print("mean for columns:", m.mean(axis=0))
print("mean for rows:", m.mean(axis=1))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
mean: 5.5
mean for columns: [4. 5. 6. 7.]
mean for rows: [1.5 5.5 9.5]


2\. **Outer product**

Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [48]:
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
z= np.outer(u, v)
print(z)



[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


In [27]:

O = []
for i in u:
    for j in v:
        
        O.append(i * j)
arr = np.array(O)
m = arr.reshape(4,4)
print(m)

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


In [52]:
print(u[:, None] * v) 

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. **Matrix masking**

Create a 10 by 6 matrix of float random numbers, distributed between 0 and 3 according to a flat distribution.

After creating the matrix, set all entries $< 0.3$ to zero using a mask.

In [34]:
import numpy.random as npr
arr2 = npr.uniform(0,4,size = (10,6))

print(arr2,"\n")

mask = (arr2 < 0.3)
arr2[mask] = 0

print(arr2)




[[2.6010745  2.96956413 2.91255915 2.38707287 2.61988315 3.88809715]
 [1.29115828 2.85728513 1.67608033 1.12012266 1.3371427  2.02968211]
 [0.03780766 3.93846215 3.29795899 2.20140581 3.47653606 2.17500382]
 [0.45979216 2.43275987 2.06205321 1.19633145 0.2495252  0.520178  ]
 [3.83205709 1.4701255  0.75806969 0.31774793 2.98345644 0.83430979]
 [2.60377461 3.02223223 1.75343417 0.79903882 1.66472577 1.28630886]
 [1.61043116 0.32046568 1.84000916 2.12846804 0.6791866  0.00809068]
 [1.14490731 0.51282519 1.24251624 0.41632914 3.59861593 2.22052512]
 [1.45958202 1.62926217 2.67099438 0.39736082 1.93623994 3.26101455]
 [2.33360126 3.7065578  0.36098529 0.2871802  1.49896971 3.63134539]] 

[[2.6010745  2.96956413 2.91255915 2.38707287 2.61988315 3.88809715]
 [1.29115828 2.85728513 1.67608033 1.12012266 1.3371427  2.02968211]
 [0.         3.93846215 3.29795899 2.20140581 3.47653606 2.17500382]
 [0.45979216 2.43275987 2.06205321 1.19633145 0.         0.520178  ]
 [3.83205709 1.4701255  0.75806

In [ ]:
4\. **Trigonometric functions**

Use `np.linspace` to create an array of 100 numbers between $0$ and $2\pi$ (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the `sin` and `cos` functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

In [51]:
import numpy as np
a = np.linspace(0,np.pi*2,100)
print(a)
every_10 = a[::10]
print(every_10)

reverse = a[::-1]
print(reverse)

ext_trig=np.abs(np.sin(a)-np.cos(a)) < 0.1
print (a[ext_trig])






[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

5\. **Matrices**

Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [66]:
my_matrix_1 = np.arange(1, 11)
my_matrix_2 = np.arange(1, 11)

multiplication = np.array([[i*j for j in my_matrix_1] for i in my_matrix_2]).reshape(10,10)
print(multiplication)
print("\n")
print (multiplication.trace())
print("\n")
[multiplication[i][-(i+1)] for i in range(len(multiplication))]
print("\n")
print (multiplication.diagonal(offset=1))


[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


385




[ 2  6 12 20 30 42 56 72 90]


6\. **Broadcasting**

Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles.

The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [67]:
pos_in_miles= np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])
x =  pos_in_miles[np.newaxis, :]
y =  pos_in_miles[:, np.newaxis]
a = x - y
print(a)



[[    0   198   303   736   871  1175  1475  1544  1913  2448]
 [ -198     0   105   538   673   977  1277  1346  1715  2250]
 [ -303  -105     0   433   568   872  1172  1241  1610  2145]
 [ -736  -538  -433     0   135   439   739   808  1177  1712]
 [ -871  -673  -568  -135     0   304   604   673  1042  1577]
 [-1175  -977  -872  -439  -304     0   300   369   738  1273]
 [-1475 -1277 -1172  -739  -604  -300     0    69   438   973]
 [-1544 -1346 -1241  -808  -673  -369   -69     0   369   904]
 [-1913 -1715 -1610 -1177 -1042  -738  -438  -369     0   535]
 [-2448 -2250 -2145 -1712 -1577 -1273  -973  -904  -535     0]]


7\. **Prime numbers sieve**

Compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).

  * Constract a shape (N,) boolean array, which is the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (with `timeit`); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [76]:
prime_num = np.ones((100,), dtype=bool)
prime_num[:2] = 0
prime = np.arange(0,100)


maximum = int(np.sqrt(len(prime_num)))
for i in range(2, maximum):
    prime_num[2*i::i] = False
    
m = prime[prime_num]
print(m)

%timeit prime[prime_num]





[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97]
575 ns ± 2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
[  2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.
  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.  29.
  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.  43.
  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.  57.
  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.  71.
  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.  85.
  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.  99.
 100.]


In [84]:
n = 100
num_list = [_ for _ in range (2, n + 1) ]
prime_nums = []

while num_list:
    p = num_list [0]
    prime_nums.append (p)
    for i in range (p, n + 1, p):
        if i in num_list: num_list.remove (i)

print (primes)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


8\. **Diffusion using random walk**

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of many random walkers after a given amount of time.

*Hint*: create a 2D array where each row represents a walker, and each column represents a time step.

  * Take 1000 walkers and let them walk for 200 steps
  * Use `randint` to create a 2D array of size $walkers \times steps$ with values -1 or 1
  * Calculate the walking distances for each walker (e.g. by summing the elements in each row)
  * Take the square of the previously-obtained array (element-wise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * **Optional**: plot the average distances ($\sqrt(distance^2)$) as a function of time (step)

In [134]:
import matplotlib.pyplot as plt
N = 200
matrix_w = 2*npr.randint(0,2,size=(1000, N))-1
#print(matrix_w)


arr = [sum(i) for i in matrix_w]
print(arr)
print(" ")


arr2 = [ np.square(i) for i in arr]
print(arr2)
print(" ")



# arr3 = [ np.sqrt(i) for i in arr2]
print(arr3)

## plt.plot(xs), plt.xlabel('N'),plt.ylabel('x(N)')


[28, -4, -6, -6, -10, -4, 10, 22, 42, -36, -8, -2, -18, 22, -10, -6, 6, 10, 10, -16, 12, 8, -6, -26, 30, 4, -10, 16, -24, 8, 2, 4, -20, 8, 2, -2, 8, 8, 2, 14, -16, -32, -4, 4, 2, 22, 26, 4, -14, -16, -16, 8, -16, 6, -4, -34, 0, -12, -10, -2, -18, 4, 2, -10, -22, -26, -6, 4, 2, -16, -18, 16, 26, 8, -6, -28, -2, -6, 30, -18, -10, 6, -6, 0, -16, 10, 12, -6, 12, 6, 18, -14, 18, 8, 12, 28, -14, 6, -6, 2, -10, 2, -10, -2, -12, 16, -6, -38, 10, 8, 18, 14, 16, -2, 8, -10, -20, 10, -8, 2, 8, 10, 0, 8, -14, 18, -24, 10, -4, 0, 10, -4, 16, 6, 6, 12, -4, 2, -12, -36, 14, 0, 14, 8, -28, -26, -4, -2, 28, -2, 2, 6, -4, 2, -12, 4, -6, 10, 16, 2, 32, 12, -2, 12, -16, -28, -36, 22, -24, 16, -14, 12, 0, -4, 12, -12, -6, 10, -14, 10, -6, 0, 14, -12, 16, 12, 4, -2, 22, 4, -4, -20, 4, -14, -12, 8, -10, 4, 2, 10, -14, 4, -4, 6, 24, 8, 0, 4, -10, 4, 0, -6, 16, 6, -12, -32, 18, -16, 16, -12, 0, -4, 2, -24, 26, -4, 2, -6, -8, -10, 8, -12, -2, 2, 2, -18, -10, -16, 0, -12, 18, -20, 8, -2, 4, 24, 2, -24, -2, 14, 2