1\. **Reductions**

Find the total mean, and the mean for each row and column of the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [1]:
#importo modulo
import numpy as np
import timeit

#Media Totale
m = np.arange(12).reshape((3,4))
print('Total Mean of the matrix: ', m.mean(), '\n')

#Media righe
med_rig = m.mean(axis = 1)
for rig in range(med_rig.shape[0]):
    print('Mean of the row', str(rig+1),': ', med_rig[rig])
print('\n')

#Media colonne
med_col = m.mean(axis = 0)
for col in range(med_col.shape[0]):
    print('Mean of the column', str(col + 1), ': ', med_col[col])
print('\n')

Total Mean of the matrix:  5.5 

Mean of the row 1 :  1.5
Mean of the row 2 :  5.5
Mean of the row 3 :  9.5


Mean of the column 1 :  4.0
Mean of the column 2 :  5.0
Mean of the column 3 :  6.0
Mean of the column 4 :  7.0




2\. **Outer product**

Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [2]:
#Metodo 1 : Outer Function
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])
print('Outer product with outer function:\n', np.outer(u,v), '\n')

#Metodo 2 : List Comprehension
outer2 = np.array([el_u * v for el_u in u])
print('Outer product with list comprehension and loop:\n', outer2, '\n')

#Metodo 3 : Broadcasting

outer3 = np.tile(u,(4,1)).T * v
print('Outer product with broadcast:\n', outer3, '\n')

Outer product with outer function:
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]] 

Outer product with list comprehension and loop:
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]] 

Outer product with broadcast:
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]] 



3\. **Matrix masking**

Create a 10 by 6 matrix of float random numbers, distributed between 0 and 3 according to a flat distribution.

After creating the matrix, set all entries $< 0.3$ to zero using a mask.

In [3]:
randmat = np.random.uniform(0,3,(10,6))
print('Original Matrix:\n', randmat, '\n')
mask = (randmat < 0.3)
randmat[mask] = 0
print('Filtered Matrix:\n', randmat, '\n')

Original Matrix:
 [[0.98328684 2.36170852 0.7882543  2.9152471  0.39949213 0.79837902]
 [2.05841504 0.07504106 0.35024984 1.423656   1.44761487 2.6124537 ]
 [1.44298577 1.49561666 1.92703148 0.15498591 0.68334044 0.42689832]
 [0.54308664 2.37426065 2.38235819 0.22613389 2.44868561 0.23465852]
 [1.67376921 0.44928219 0.22869585 2.96816628 0.88571719 2.94429769]
 [1.96428823 2.56544754 1.2085282  2.00106816 2.26061875 1.73116914]
 [0.73616861 1.37663289 1.22442053 2.82125252 2.00771353 2.77083602]
 [2.5702634  2.88777437 2.10394408 2.60140228 2.61673119 0.74863717]
 [2.41727165 0.1483898  1.57988309 1.2111577  1.80293137 2.33899019]
 [1.27627924 0.24063642 2.84008514 2.50157526 2.38612579 2.26403677]] 

Filtered Matrix:
 [[0.98328684 2.36170852 0.7882543  2.9152471  0.39949213 0.79837902]
 [2.05841504 0.         0.35024984 1.423656   1.44761487 2.6124537 ]
 [1.44298577 1.49561666 1.92703148 0.         0.68334044 0.42689832]
 [0.54308664 2.37426065 2.38235819 0.         2.44868561 0.     

4\. **Trigonometric functions**

Use `np.linspace` to create an array of 100 numbers between $0$ and $2\pi$ (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the `sin` and `cos` functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

In [4]:
import math

time = np.linspace(0,2*math.pi, 100)
print('Original Time Array:\n',time,'\n')

time_ten = time[[(10*(k+1) - 1) for k in range(10)]]
print('10th elements time array:\n', time_ten,'\n')

time_ten_rev = time_ten[[-k for k in range(1 , time_ten.shape[0]+1)]]
print('Reverse Array:\n', time_ten_rev,'\n')

phi = 0.1
low_diff_sincos = time[abs(np.cos(time)-np.sin(time)) < phi]
print('Elements where the absolute difference between the sin and cos function evalueted for that element is <',str(phi),'\n',low_diff_sincos)

Original Time Array:
 [0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.521587

5\. **Matrices**

Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [5]:
u = np.arange(1,11)
multiplication_table10 = np.outer(u,u)
print('10 by 10 multiplication table: \n', multiplication_table10,'\n')

print('Matrix trace: ',np.trace(multiplication_table10),'\n')

antdiag = np.diag(np.fliplr(multiplication_table10))
print('Anti-diagonal: ', antdiag, type(antdiag),'\n')
antdiag_mat = np.fliplr(np.tril(np.triu(np.fliplr(multiplication_table10))))
print('Anti-diagonal Matrix:\n', antdiag_mat, '\n')
#In here I didn't understand if the request was to print the anti-diagonal elements in an array, or
#the anti-diagonal matrix, so I did both

diag_1up = np.diag(multiplication_table10, +1)
print('The diagonal offset by 1 upwards:\n',diag_1up, type(diag_1up))

10 by 10 multiplication table: 
 [[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]] 

Matrix trace:  385 

Anti-diagonal:  [10 18 24 28 30 30 28 24 18 10] <class 'numpy.ndarray'> 

Anti-diagonal Matrix:
 [[ 0  0  0  0  0  0  0  0  0 10]
 [ 0  0  0  0  0  0  0  0 18  0]
 [ 0  0  0  0  0  0  0 24  0  0]
 [ 0  0  0  0  0  0 28  0  0  0]
 [ 0  0  0  0  0 30  0  0  0  0]
 [ 0  0  0  0 30  0  0  0  0  0]
 [ 0  0  0 28  0  0  0  0  0  0]
 [ 0  0 24  0  0  0  0  0  0  0]
 [ 0 18  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]] 

The diagonal offset by 1 upwards:
 [ 2  6 12 20 30 42 56 72 90] <class 'numpy.ndarr

6\. **Broadcasting**

Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles.

The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [6]:
position = np.array([0,198,303,736,871,1175,1475,1544,1913,2448])
distances_miles = abs(np.tile(position,(position.shape[0],1)).T - position)
print('2D grid distances among city alont Route 66 (in miles): \n', distances_miles,'\n')
conv = 1.60934
distances_km = distances_miles * conv
print('2D grid distances among city alont Route 66 (in km): \n ', distances_km)

2D grid distances among city alont Route 66 (in miles): 
 [[   0  198  303  736  871 1175 1475 1544 1913 2448]
 [ 198    0  105  538  673  977 1277 1346 1715 2250]
 [ 303  105    0  433  568  872 1172 1241 1610 2145]
 [ 736  538  433    0  135  439  739  808 1177 1712]
 [ 871  673  568  135    0  304  604  673 1042 1577]
 [1175  977  872  439  304    0  300  369  738 1273]
 [1475 1277 1172  739  604  300    0   69  438  973]
 [1544 1346 1241  808  673  369   69    0  369  904]
 [1913 1715 1610 1177 1042  738  438  369    0  535]
 [2448 2250 2145 1712 1577 1273  973  904  535    0]] 

2D grid distances among city alont Route 66 (in km): 
  [[   0.       318.64932  487.63002 1184.47424 1401.73514 1890.9745
  2373.7765  2484.82096 3078.66742 3939.66432]
 [ 318.64932    0.       168.9807   865.82492 1083.08582 1572.32518
  2055.12718 2166.17164 2760.0181  3621.015  ]
 [ 487.63002  168.9807     0.       696.84422  914.10512 1403.34448
  1886.14648 1997.19094 2591.0374  3452.0343 ]
 [1184.47

7\. **Prime numbers sieve**

Compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).

  * Constract a shape (N,) boolean array, which is the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (with `timeit`); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [7]:
def findPrimes(N):
    mask = np.array(np.ones(N,),bool)
    #Identify the multiples
    for num in range(2,N):
        for k in range(2,N):
            if num*k >= N or mask[num*k] == 0:
                break
            mask[num*k] = 0
    primes = np.arange(0,N)[mask]
    return primes

N = 99
loops = 1000
primes = findPrimes(99)
print('Prime numbers in the 0 -',N,'range: ',primes,'\n')

t = timeit.timeit('findPrimes(N)', globals = globals(), number = loops)
time = t/loops
print('Performances of my algorithm (sec): ', time, '\n')

#Sieve f Eratosthenes
def eratosthenes(N):
    mask = np.array(np.ones(N,),bool)
    #Identify the multiples
    for num in range(2,N):
        if mask[num] == 0:
            continue
        else:
            for k in range(2,N):
                if num*k >= N or mask[num*k] == 0:
                    break
                mask[num*k] = 0
    primes = np.arange(0,N)[mask]
    return primes

t_era = timeit.timeit('eratosthenes(N)', globals = globals(), number = loops)
time_era = t_era/loops
print('Prime numbers in the 0 -',N,'range, found with Eratosthenes sieve:\n',eratosthenes(N),'\n')
print('Eratosthenes Algoritm Performance (sec): ',time_era, '\n')

Prime numbers in the 0 - 99 range:  [ 0  1  2  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43
 45 47 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91
 93 95 97] 

Performances of my algorithm (sec):  0.00025273428099999997 

Prime numbers in the 0 - 99 range, found with Eratosthenes sieve:
 [ 0  1  2  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43
 45 47 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91
 93 95 97] 

Eratosthenes Algoritm Performance (sec):  0.00036553622599999993 



8\. **Diffusion using random walk**

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of many random walkers after a given amount of time.

*Hint*: create a 2D array where each row represents a walker, and each column represents a time step.

  * Take 1000 walkers and let them walk for 200 steps
  * Use `randint` to create a 2D array of size $walkers \times steps$ with values -1 or 1
  * Calculate the walking distances for each walker (e.g. by summing the elements in each row)
  * Take the square of the previously-obtained array (element-wise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * **Optional**: plot the average distances ($\sqrt(distance^2)$) as a function of time (step)

In [8]:
nwalkers = 1000
nsteps = 200
walkers = np.random.randint(0,2,(nwalkers,nsteps))
walkers[walkers == 0] = -1
distances = walkers.sum(axis = 1)
print('Distances for each walker:\n',distances,'\n', distances.shape[0])
#distances_square = np.square(distances)
walkers_square = np.square(walkers)

Distances for each walker:
 [ 12  24   0  18  22  18 -16 -10  18   2  10   8  10 -12  20  -4   8   8
   6 -16 -18 -14   4   0 -10   0  -8   8   6 -20  36   4  10  24   0  12
 -14   8   6  -2 -40   6  -2   0 -12   2 -18   0 -20 -34  14  -8  -4  -6
   2   2  18  14  -4   4  18  10   4   8 -10   8   4 -12   0 -10  -4 -12
   8 -24  -2   8   2   2  12  20   8   8   6   0 -30   2  16  20  -2  -2
  -8  18 -10   4  12   2   0 -12   4 -26  -4 -14   4  24  16   0   6 -20
 -22   4  12   8 -10  -6  20 -10   6   2  -4  12 -34   0 -20   0  26 -12
 -18  -6 -24   2  -2  16   8   4  -2  -6   8  18  12 -24   0 -10   4  -2
  18  28  -8   8  -8  -6   4   8   4  -4  -2   2  -8 -10  22   8  16  -8
 -18 -12  -2 -12 -22  -2   4 -34  10  -4  -6  22  -8 -14   0  10  -2 -22
 -12  -4 -10  -8  -8  16  -2 -30   0 -10   6  -8  16  10   8  -6 -28 -20
   4 -38 -14 -10   8 -14 -16   8 -28  -8  18  -4 -20  10   4  -6 -14 -14
   8 -10  -2  -8 -16   0 -10  -6  14  -6   0 -24  22   8 -12   4   0 -12
  -4  26 -42  -2  22 -2