In [ ]:
import  numpy as np

ex1
total mean :

In [ ]:
m = np.arange(12).reshape((3,4))
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
t=m.shape[0]*m.shape[1]
t

12

In [ ]:
a=m.sum()
total_mean=a/t
print(f' total mean is {total_mean}')

 total mean is 5.5


calculate mean for each column:

In [ ]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#just show the columns in new form and use that to calclate the mean for each column
for i in range(m.shape[1]):
  print(m[:,i])

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [ ]:
for i in range(m.shape[1]):
  print((m[:,i].sum())/m.shape[0])

4.0
5.0
6.0
7.0


calculate mean for each row:


In [ ]:
#just show the roes in new form and use that to calclate the mean for each row.

for i in range(m.shape[0]):
  print(m[i,:])

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
for i in range(m.shape[0]):
  print((m[i,:].sum())/m.shape[1])

1.5
5.5
9.5


ex 2:
Find the outer product of the following vectors:


In [ ]:
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])

Using the function outer in numpy:


In [ ]:
outer_product=np.outer(u,v)
print(outer_product)

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


Using a nested for loop:

In [ ]:
u.shape[0]

4

In [ ]:
outerproduct=np.ones((u.shape[0],v.shape[0]))
for i in range(u.shape[0]):
  #print('dhh',u[i])
  for j in range(v.shape[0]):
    #print(v[j])
    outerproduct[i][j]=int(u[i]*v[j])
print(outerproduct)



[[ 2.  4.  6.  8.]
 [ 6. 12. 18. 24.]
 [10. 20. 30. 40.]
 [14. 28. 42. 56.]]


Using numpy broadcasting operations:


In [ ]:
print(u.shape)

(4,)


In [ ]:
t=v.reshape((1,4))
t

array([[2, 4, 6, 8]])

In [ ]:
U=u.reshape((4,1))
U

array([[1],
       [3],
       [5],
       [7]])

In [ ]:
pp=t*U
print(pp)

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


ex 3
 Matrix masking



In [ ]:
matrix=np.random.uniform(0,3,(6,10))
my_mask=(matrix<0.3)
print(my_mask)
t=matrix[my_mask]=0
print('---------------------------')
print(matrix)

[[False False False False False  True False False False False]
 [False False  True False False False  True False False  True]
 [False False  True  True False False False False False  True]
 [False False False False False False False False False False]
 [False False False False  True False False False False False]
 [False False False False False False False False False False]]
---------------------------
[[1.39134764 2.73437419 1.28327943 0.74992109 0.34334824 0.
  1.4855762  2.01947032 2.54980425 2.46949901]
 [0.59349436 0.82743504 0.         2.5685099  1.27815089 2.47186013
  0.         2.11593107 1.234671   0.        ]
 [2.29499198 1.93960597 0.         0.         0.96072653 1.77735392
  1.56966137 2.08359847 2.69466493 0.        ]
 [2.62533524 1.04067169 1.85613024 1.87067818 1.80314279 2.2197081
  2.75632111 1.06834417 0.56133639 0.40150725]
 [2.66146827 2.92172991 0.50354821 2.8964032  0.         0.69790058
  2.66976578 0.74543118 1.3790133  2.86712917]
 [2.05057704 1.82392086 0.7

ex 4
Trigonometric functions

In [ ]:
import math
x=np.linspace(0,2*math.pi,100)
x.shape

(100,)

Extract every 10th element using the slice notation

In [ ]:
#with for loop
mylist=[next]
i=0
while i<x.shape[0]:
  mylist.append(x[i])
  i+=10
print(mylist)


[<built-in function next>, 0.0, 0.6346651825433925, 1.269330365086785, 1.9039955476301778, 2.53866073017357, 3.173325912716963, 3.8079910952603555, 4.442656277803748, 5.07732146034714, 5.711986642890533]


Extract every 10th element using the slice notation


In [ ]:
secondlist=[]
secondlist=x[::10]
print(f'every 10th elemt in x {secondlist}')

every 10th elemt in x [0.         0.63466518 1.26933037 1.90399555 2.53866073 3.17332591
 3.8079911  4.44265628 5.07732146 5.71198664]


Reverse the array using the slice notation


In [ ]:
reverse=x[::-1]
print(f'reverse of the array x :/n {reverse}')

reverse of the array x :/n [6.28318531 6.21971879 6.15625227 6.09278575 6.02931923 5.96585272
 5.9023862  5.83891968 5.77545316 5.71198664 5.64852012 5.58505361
 5.52158709 5.45812057 5.39465405 5.33118753 5.26772102 5.2042545
 5.14078798 5.07732146 5.01385494 4.95038842 4.88692191 4.82345539
 4.75998887 4.69652235 4.63305583 4.56958931 4.5061228  4.44265628
 4.37918976 4.31572324 4.25225672 4.1887902  4.12532369 4.06185717
 3.99839065 3.93492413 3.87145761 3.8079911  3.74452458 3.68105806
 3.61759154 3.55412502 3.4906585  3.42719199 3.36372547 3.30025895
 3.23679243 3.17332591 3.10985939 3.04639288 2.98292636 2.91945984
 2.85599332 2.7925268  2.72906028 2.66559377 2.60212725 2.53866073
 2.47519421 2.41172769 2.34826118 2.28479466 2.22132814 2.15786162
 2.0943951  2.03092858 1.96746207 1.90399555 1.84052903 1.77706251
 1.71359599 1.65012947 1.58666296 1.52319644 1.45972992 1.3962634
 1.33279688 1.26933037 1.20586385 1.14239733 1.07893081 1.01546429
 0.95199777 0.88853126 0.82506474 0.7

Extract elements where the absolute difference between the sin and cos functions evaluated for that element is <0.1

In [ ]:
mask2=x[abs(np.sin(x)-np.cos(x))<0.1]
print([abs(np.sin(x)-np.cos(x))<0.1])
print("\r\n")
print(x[abs(np.sin(x)-np.cos(x))<0.1])



[array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])]


[0.76159822 0.82506474 3.87145761 3.93492413]


ex 5
Create a matrix that shows the 10 by 10 multiplication table. 

In [ ]:
def mult_table(n):
    rng = np.arange(1, n+1)
    return rng * rng[:, None]
t=mult_table(10)
print(t)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [ ]:
trace=np.trace(t)
print(f'the trace of 10 by 10 multiplication table is : {trace}')

the trace of 10 by 10 multiplication table is : 385


Extract the anti-diagonal matrix (this should be array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10]))



In [ ]:
anti=np.flipud(t)
antidiagonal=np.diagonal(anti)
print(f'the trace of 10 by 10 multiplication table is : {antidiagonal}')

the trace of 10 by 10 multiplication table is : [10 18 24 28 30 30 28 24 18 10]


Extract the diagonal offset by 1 upwards (this should be array([ 2, 6, 12, 20, 30, 42, 56, 72, 90]))


In [ ]:
offset=np.diagonal(t,offset=1)
print(f'the trace of 10 by 10 multiplication table is : {offset}')

the trace of 10 by 10 multiplication table is : [ 2  6 12 20 30 42 56 72 90]


ex 6
Broadcasting

In [ ]:
#gird with nested for
grid=np.zeros((10,10))
positions=np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])
for i in range(grid.shape[0]):
  for j in range(grid.shape[1]):
    grid[i][j]=abs(positions[i]-positions[j])
print(grid)
print(grid.shape)

[[   0.  198.  303.  736.  871. 1175. 1475. 1544. 1913. 2448.]
 [ 198.    0.  105.  538.  673.  977. 1277. 1346. 1715. 2250.]
 [ 303.  105.    0.  433.  568.  872. 1172. 1241. 1610. 2145.]
 [ 736.  538.  433.    0.  135.  439.  739.  808. 1177. 1712.]
 [ 871.  673.  568.  135.    0.  304.  604.  673. 1042. 1577.]
 [1175.  977.  872.  439.  304.    0.  300.  369.  738. 1273.]
 [1475. 1277. 1172.  739.  604.  300.    0.   69.  438.  973.]
 [1544. 1346. 1241.  808.  673.  369.   69.    0.  369.  904.]
 [1913. 1715. 1610. 1177. 1042.  738.  438.  369.    0.  535.]
 [2448. 2250. 2145. 1712. 1577. 1273.  973.  904.  535.    0.]]
(10, 10)


with boradcasting:

In [ ]:
f1=np.array([[0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448]])
f2=np.array([[0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448]])
f3=f2.reshape((10,1))
print(f3)

[[   0]
 [ 198]
 [ 303]
 [ 736]
 [ 871]
 [1175]
 [1475]
 [1544]
 [1913]
 [2448]]


In [ ]:
final=abs(f3-f2)
print(final)

[[   0  198  303  736  871 1175 1475 1544 1913 2448]
 [ 198    0  105  538  673  977 1277 1346 1715 2250]
 [ 303  105    0  433  568  872 1172 1241 1610 2145]
 [ 736  538  433    0  135  439  739  808 1177 1712]
 [ 871  673  568  135    0  304  604  673 1042 1577]
 [1175  977  872  439  304    0  300  369  738 1273]
 [1475 1277 1172  739  604  300    0   69  438  973]
 [1544 1346 1241  808  673  369   69    0  369  904]
 [1913 1715 1610 1177 1042  738  438  369    0  535]
 [2448 2250 2145 1712 1577 1273  973  904  535    0]]


In [ ]:
#conver mile to km
km_distance=final*1.60934
print(km_distance)
print(km_distance.shape)

[[   0.       318.64932  487.63002 1184.47424 1401.73514 1890.9745
  2373.7765  2484.82096 3078.66742 3939.66432]
 [ 318.64932    0.       168.9807   865.82492 1083.08582 1572.32518
  2055.12718 2166.17164 2760.0181  3621.015  ]
 [ 487.63002  168.9807     0.       696.84422  914.10512 1403.34448
  1886.14648 1997.19094 2591.0374  3452.0343 ]
 [1184.47424  865.82492  696.84422    0.       217.2609   706.50026
  1189.30226 1300.34672 1894.19318 2755.19008]
 [1401.73514 1083.08582  914.10512  217.2609     0.       489.23936
   972.04136 1083.08582 1676.93228 2537.92918]
 [1890.9745  1572.32518 1403.34448  706.50026  489.23936    0.
   482.802    593.84646 1187.69292 2048.68982]
 [2373.7765  2055.12718 1886.14648 1189.30226  972.04136  482.802
     0.       111.04446  704.89092 1565.88782]
 [2484.82096 2166.17164 1997.19094 1300.34672 1083.08582  593.84646
   111.04446    0.       593.84646 1454.84336]
 [3078.66742 2760.0181  2591.0374  1894.19318 1676.93228 1187.69292
   704.89092  593.84

ex 7
 Prime numbers sieve
 each True values in the prime array is correspondig to a prime number 

consider the first prime number=2
by changing the p value in code you can set it to 1.

In [ ]:
def SieveOfEratosthenes(num):
#Constract a shape (N,) boolean array, which is the mask
    prime = np.array([True for i in range(num+1)])
    p = 2
    while (p * p <= num):
        if (prime[p] == True):
  
#Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
            for i in range(p * p, num+1, p):
                prime[i] = False
        p += 1
  
#Apply the mask to obtain an array of ordered prime numbers
    for p in range(2, num+1):
        if prime[p]:
            print(p)
    print(prime)
  
  

num = 100
SieveOfEratosthenes(num)

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
[ True  True  True  True False  True False  True False False False  True
 False  True False False False  True False  True False False False  True
 False False False False False  True False  True False False False False
 False  True False False False  True False  True False False False  True
 False False False False False  True False False False False False  True
 False  True False False False False False  True False False False  True
 False  True False False False False False  True False False False  True
 False False False False False  True False False False False False False
 False  True False False False]


**Check the performances (with timeit); how does it scale with N?**
with increasing N the time also increases from 8 microsecont to 33 ms

In [ ]:
#previous function without pritn method for just compare the time
def new_SieveOfEratosthenes(num):
#Constract a shape (N,) boolean array, which is the mask
    prime = np.array([True for i in range(num+1)])
    p = 2
    while (p * p <= num):
        if (prime[p] == True):
  
#Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
            for i in range(p * p, num+1, p):
                prime[i] = False
        p += 1

#Apply the mask to obtain an array of ordered prime numbers
print('for N=10')
%timeit [new_SieveOfEratosthenes(10)]
print('for N=100')

%timeit [new_SieveOfEratosthenes(100)]
print('for N=10000')

%timeit [new_SieveOfEratosthenes(10000)]

for N=10
5.88 µs ± 183 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
for N=100
31.3 µs ± 793 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
for N=10000
3.05 ms ± 154 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


ex 8
Diffusion using random walk

Take 1000 walkers and let them walk for 200 steps
Use randint to create a 2D array of size  with values -1 or 1

In [ ]:
def my_func(waker,time):
  sum=[]
  distance=[]
  table=np.zeros((waker,time))
  for i in range(table.shape[0]):
    t=np.random.randint(-1,1,time)
    #create mask to convert 0 to 1 because we want 2 values(-1,1)
    t[t==0]=1
    for j in range(t.shape[0]):
      table[i][j]=t[j]
  print(table)
  for i in range(table.shape[0]):
    sum.append(table[i].sum())
  #print('he walking distances for each walker')
  return(sum)


In [ ]:
my_func(10,5)

[[-1.  1. -1.  1.  1.]
 [-1.  1.  1. -1.  1.]
 [ 1. -1.  1. -1.  1.]
 [-1. -1. -1.  1.  1.]
 [ 1.  1. -1. -1. -1.]
 [ 1. -1. -1. -1.  1.]
 [ 1.  1. -1. -1.  1.]
 [-1.  1. -1. -1.  1.]
 [-1. -1.  1. -1.  1.]
 [ 1.  1.  1.  1.  1.]]


[1.0, 1.0, 1.0, -1.0, -1.0, -1.0, 1.0, -1.0, -1.0, 5.0]

Take the square of the previously-obtained array (element-wise)


In [ ]:
sqrt_list=(np.array(my_func(10,5))**2)
print(sqrt_list)


[[-1.  1.  1.  1.  1.]
 [-1. -1.  1. -1.  1.]
 [-1. -1. -1.  1.  1.]
 [-1. -1. -1. -1. -1.]
 [-1.  1.  1.  1. -1.]
 [ 1.  1. -1. -1.  1.]
 [-1.  1.  1.  1.  1.]
 [ 1. -1.  1. -1.  1.]
 [-1.  1.  1.  1.  1.]
 [-1.  1. -1.  1. -1.]]
[ 9.  1.  1. 25.  1.  1.  9.  1.  9.  1.]


In [ ]:
#second approach
r=np.square(my_func(10,5))
print(r)

[[-1.  1.  1. -1.  1.]
 [-1. -1.  1. -1. -1.]
 [ 1.  1.  1.  1.  1.]
 [-1. -1. -1.  1.  1.]
 [-1.  1.  1. -1. -1.]
 [-1.  1.  1. -1. -1.]
 [-1. -1.  1.  1.  1.]
 [ 1.  1.  1. -1.  1.]
 [-1. -1. -1. -1.  1.]
 [-1.  1. -1. -1.  1.]]
[ 1.  9. 25.  1.  1.  1.  1.  9.  9.  1.]


ompute the mean of the squared distances at each step (i.e. the mean along the columns)

In [ ]:
def mean(waker,time):
  mean=[]
  table=np.zeros((waker,time))
  for i in range(table.shape[0]):
    t=np.random.randint(-1,1,time)
    #create mask to convert 0 to 1 because we want 2 values(-1,1)
    t[t==0]=1
    for j in range(t.shape[0]):
      table[i][j]=t[j]
  #print(table)
  for i in range(table.shape[1]):
    #print(table[:,i])
    mean.append(table[:,i].sum())
  return np.array(mean)/table.shape[0]

In [ ]:
mean(10,3)

array([ 0. ,  0.4, -0.2])

In [ ]:
m=np.array([[1,2,3],[5,6,7],[8,9,10]])
m

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
r=np.mean(mean(10,5),axis=0)
print(r)

0.16
