1\. **Reductions**

Find the total mean, and the mean for each row and column of the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [18]:
import numpy as np

import math

m = np.arange(12).reshape((3,4))
print(m) 

print("The total mean of the matrix is:", np.mean(m)) 
print("The mean for each column is:", np.mean(m,axis=0)) 
print("The mean for each row is:", np.mean(m,axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
The total mean of the matrix is: 5.5
The mean for each column is: [4. 5. 6. 7.]
The mean for each row is: [1.5 5.5 9.5]


2\. **Outer product**

Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [20]:
import numpy as np
import math

u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])

#outer function
outer1=np.outer(u,v)
print(outer1)
    
#for loop
outer2=np.zeros((4, 4))
for i in range(4):
    for j in range(4):
        outer2[i][j]=u[i]*v[j]
print(outer2)

#broadcasting
outer3 = np.tile(u,(4,1)).T * v
print(outer3)

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
[[ 2.  4.  6.  8.]
 [ 6. 12. 18. 24.]
 [10. 20. 30. 40.]
 [14. 28. 42. 56.]]
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. **Matrix masking**

Create a 10 by 6 matrix of float random numbers, distributed between 0 and 3 according to a flat distribution.

After creating the matrix, set all entries $< 0.3$ to zero using a mask.

In [1]:
import numpy as np
import numpy.random as npr
import math

m = 3*npr.rand(10, 6)
print(m)
    
mask = (m >= 0.3)
print(mask)

m[mask] = 0
print (m)

[[2.94792847 2.28429044 2.15415802 0.30241783 2.67892527 2.32011434]
 [1.27210669 0.04841201 0.03575811 1.36143993 2.66136076 0.80249703]
 [0.73387382 1.81845646 0.27989837 0.28588632 2.38120278 1.69238794]
 [2.62712412 2.01677617 2.07073336 0.86248084 2.33248504 0.78964122]
 [0.27482581 0.02968842 2.92728968 1.32174217 2.9247679  2.55224472]
 [0.33694914 0.10181739 2.72705739 0.03272196 1.83585317 1.1021785 ]
 [1.69216224 0.80758839 0.5581942  1.29603705 1.88925642 2.59058725]
 [0.15126737 2.83274706 0.96199866 1.65160423 1.11816073 0.79852823]
 [1.98376277 0.77903876 1.84166561 2.85827059 2.79774752 2.42692856]
 [1.25646152 2.93659475 0.46818463 1.75283902 0.87125532 2.5662092 ]]
[[ True  True  True  True  True  True]
 [ True False False  True  True  True]
 [ True  True False False  True  True]
 [ True  True  True  True  True  True]
 [False False  True  True  True  True]
 [ True False  True False  True  True]
 [ True  True  True  True  True  True]
 [False  True  True  True  True  Tru

4\. **Trigonometric functions**

Use `np.linspace` to create an array of 100 numbers between $0$ and $2\pi$ (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the `sin` and `cos` functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

In [25]:
import numpy as np
import numpy.random as npr
import math

v=np.linspace(0,2*np.pi,100)
print(v)

print(v[::10]) #extract every 10th element
print(v[::-1])

extraction=[]
for value in v:
    if abs(np.sin(value)-np.cos(value))<0.1:
        extraction.append(value)

print(extraction)


[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

5\. **Matrices**

Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [3]:
import numpy as np
import math

m= np.zeros((10, 10))
for i in range(10):
    for j in range(10):
        m[i][j]=(i+1)*(j+1)

print(m)
print("The trace is: ", np.trace(m), '\n')

ant_m = np.diag(np.fliplr(m))
print('The anti-diagonal is: ', ant_m, type(ant_m),'\n')

m_diag = np.diag(m, +1)
print('The diagonal offset by 1 upwards is:\n', m_diag, type(m_diag))

[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  2.   4.   6.   8.  10.  12.  14.  16.  18.  20.]
 [  3.   6.   9.  12.  15.  18.  21.  24.  27.  30.]
 [  4.   8.  12.  16.  20.  24.  28.  32.  36.  40.]
 [  5.  10.  15.  20.  25.  30.  35.  40.  45.  50.]
 [  6.  12.  18.  24.  30.  36.  42.  48.  54.  60.]
 [  7.  14.  21.  28.  35.  42.  49.  56.  63.  70.]
 [  8.  16.  24.  32.  40.  48.  56.  64.  72.  80.]
 [  9.  18.  27.  36.  45.  54.  63.  72.  81.  90.]
 [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]]
The trace is:  385.0 

The anti-diagonal is:  [10. 18. 24. 28. 30. 30. 28. 24. 18. 10.] <class 'numpy.ndarray'> 

The diagonal offset by 1 upwards is:
 [ 2.  6. 12. 20. 30. 42. 56. 72. 90.] <class 'numpy.ndarray'>


6\. **Broadcasting**

Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles.

The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [4]:
import numpy as np
import math

pos = np.array([0,198,303,736,871,1175,1475,1544,1913,2448])
dmiles = abs(np.tile(pos,(pos.shape[0],1)).T - pos)
print('2D grid distances among city alont Route 66 (in miles): \n', dmiles,'\n')

conv = 1.60934
dkm = dmiles * conv
print('2D grid distances among city alont Route 66 (in km): \n ', dkm)

2D grid distances among city alont Route 66 (in miles): 
 [[   0  198  303  736  871 1175 1475 1544 1913 2448]
 [ 198    0  105  538  673  977 1277 1346 1715 2250]
 [ 303  105    0  433  568  872 1172 1241 1610 2145]
 [ 736  538  433    0  135  439  739  808 1177 1712]
 [ 871  673  568  135    0  304  604  673 1042 1577]
 [1175  977  872  439  304    0  300  369  738 1273]
 [1475 1277 1172  739  604  300    0   69  438  973]
 [1544 1346 1241  808  673  369   69    0  369  904]
 [1913 1715 1610 1177 1042  738  438  369    0  535]
 [2448 2250 2145 1712 1577 1273  973  904  535    0]] 

2D grid distances among city alont Route 66 (in km): 
  [[   0.       318.64932  487.63002 1184.47424 1401.73514 1890.9745
  2373.7765  2484.82096 3078.66742 3939.66432]
 [ 318.64932    0.       168.9807   865.82492 1083.08582 1572.32518
  2055.12718 2166.17164 2760.0181  3621.015  ]
 [ 487.63002  168.9807     0.       696.84422  914.10512 1403.34448
  1886.14648 1997.19094 2591.0374  3452.0343 ]
 [1184.47

7\. **Prime numbers sieve**

Compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).

  * Constract a shape (N,) boolean array, which is the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (with `timeit`); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [6]:
import numpy as np
import math
import timeit

def findPrimes(N):
    mask = np.array(np.ones(N,),bool)
    #Identify the multiples
    for num in range(2,N):
        for k in range(2,N):
            if num*k >= N or mask[num*k] == 0:
                break
            mask[num*k] = 0
    primes = np.arange(0,N)[mask]
    return primes

N = 99
loops = 1000
primes = findPrimes(99)
print('Prime numbers in the 0 -',N,'range: ',primes,'\n')

t = timeit.timeit('findPrimes(N)', globals = globals(), number = loops)
time = t/loops
print('Performances of my algorithm (sec): ', time, '\n')

#Sieve f Eratosthenes
def eratosthenes(N):
    mask = np.array(np.ones(N,),bool)
    #Identify the multiples
    for num in range(2,N):
        if mask[num] == 0:
            continue
        else:
            for k in range(2,N):
                if num*k >= N or mask[num*k] == 0:
                    break
                mask[num*k] = 0
    primes = np.arange(0,N)[mask]
    return primes

t_era = timeit.timeit('eratosthenes(N)', globals = globals(), number = loops)
time_era = t_era/loops
print('Prime numbers in the 0 -',N,'range, found with Eratosthenes sieve:\n',eratosthenes(N),'\n')
print('Eratosthenes Algoritm Performance (sec): ',time_era, '\n')


Prime numbers in the 0 - 99 range:  [ 0  1  2  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43
 45 47 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91
 93 95 97] 

Performances of my algorithm (sec):  0.0009638846199999307 

Prime numbers in the 0 - 99 range, found with Eratosthenes sieve:
 [ 0  1  2  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43
 45 47 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91
 93 95 97] 

Eratosthenes Algoritm Performance (sec):  0.0010444061910000074 



8\. **Diffusion using random walk**

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of many random walkers after a given amount of time.

*Hint*: create a 2D array where each row represents a walker, and each column represents a time step.

  * Take 1000 walkers and let them walk for 200 steps
  * Use `randint` to create a 2D array of size $walkers \times steps$ with values -1 or 1
  * Calculate the walking distances for each walker (e.g. by summing the elements in each row)
  * Take the square of the previously-obtained array (element-wise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * **Optional**: plot the average distances ($\sqrt(distance^2)$) as a function of time (step)

In [7]:
import numpy as np
import numpy.random as npr
import math

nwalkers = 1000
nsteps = 200
walkers = np.random.randint(0,2,(nwalkers,nsteps))
walkers[walkers == 0] = -1
distances = walkers.sum(axis = 1)
print('Distances for each walker:\n',distances,'\n', distances.shape[0])
#distances_square = np.square(distances)
walkers_square = np.square(walkers)


Distances for each walker:
 [ -8   4  -8  14   8   8 -10 -12   6  10  -8  10 -20 -20   0   4  18   8
 -16  -8   8  -8  12  30  -4  12  -6 -12  24   0 -26   0  16  -2   8 -18
   4  -4   8  22 -16 -14  10  -6  -4  22 -10  20 -16  -2  -2  -4  -4   0
 -12  12 -10   2 -32   8 -10  -4 -36  -4 -16  16  26   2  10  -4  -8   4
  10   0  14  12   2  20 -20 -22  -4 -16   4   2 -16 -16  -2  28  -6 -18
  26   2 -16  22  26   2 -14  20  -6  -4  26  26  12  30   2 -22   2  -6
   8 -22  24   2 -12 -16   0  -6 -10  14  -6 -26   0 -14  20   6  26 -18
  -2  16  -6  -8  -4   2   6   2  14   4   4   0  -2 -16  -8 -12  -2  36
 -18  -8  38 -20  32  22 -24  14 -14   4  24  -2 -20 -14 -14 -24  -4  -4
  10   0 -12 -24 -16  12 -10   6 -28 -20   2  14 -20   2 -30  -8  -6  -8
  26 -22 -10  -4  22   8  -2   8   8 -10  10  -4   0 -38  -6  32 -26  32
   6  14 -12   4 -12   0 -16   6  10   6 -16  -4   6   4 -32 -14   4 -12
  22  20   6  24   8  -6  -6   8 -26 -14 -14  32 -12 -20  -2   4  12 -18
  -4  -2  10  -6  12 -2