1\. **Reductions**

Find the total mean, and the mean for each row and column of the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [2]:
import numpy as np

m = np.arange(12).reshape((3,4))

shape_m = m.shape
row = []
column = []
total = 0

for i in range(shape_m[1]):
    mean_row = 0
    for j in range(shape_m[0]):
        mean_row = mean_row + m[j][i]
    row.append(mean_row/shape_m[0])
    total = total + mean_row

total = total/(shape_m[0]*shape_m[1])

for j in range(shape_m[0]):
    mean_column = 0
    for i in range(shape_m[1]):
        mean_column = mean_column + m[j][i]
    column.append(mean_column/shape_m[1])
    
print("matrix: \n",m)
print("")
print("rows' means: ",row)
print("")
print("columns' means: ",column)
print("")
print("total mean: ",total)

matrix: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

rows' means:  [4.0, 5.0, 6.0, 7.0]

columns' means:  [1.5, 5.5, 9.5]

total mean:  5.5


2\. **Outer product**

Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [19]:
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])

#1
w = np.outer(u, v)
print(w)

#2
w = np.empty([len(u),len(v)])

for i in range(len(u)):
    for j in range(len(v)):
        w[i,j] = u[i]*v[j]

print("")    
print(w)

#3
w = (np.tile(u, (1, 1)).T)*v

print("")    
print(w)

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]

[[ 2.  4.  6.  8.]
 [ 6. 12. 18. 24.]
 [10. 20. 30. 40.]
 [14. 28. 42. 56.]]

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. **Matrix masking**

Create a 10 by 6 matrix of float random numbers, distributed between 0 and 3 according to a flat distribution.

After creating the matrix, set all entries $< 0.3$ to zero using a mask.

In [20]:
mat = np.random.uniform(0,4,[10,6])



[[1.07294392 1.47528781 0.87382653 2.22025714 0.49870427 0.8514895 ]
 [3.82937533 2.48102777 1.03959719 3.17122645 2.44174395 3.6391229 ]
 [1.31067123 1.10153486 2.66498913 3.64584579 0.43668131 1.42124246]
 [2.0913663  2.02287665 2.26511642 2.87348197 3.53123412 1.57004723]
 [1.65534816 1.66278654 1.92888573 3.82128986 1.4255955  2.3717619 ]
 [0.16557811 3.03785357 1.10053517 1.35765533 3.89122798 0.19794456]
 [0.10799469 3.12641161 1.01439427 2.42726853 3.23361946 1.45802733]
 [3.12684097 3.28812399 3.58466321 0.2270344  3.09475167 1.6786641 ]
 [3.12457733 3.12663357 2.84322907 3.26148251 1.34668386 0.98487738]
 [0.26495507 0.33832882 3.41383883 1.54666419 2.13821114 0.57143122]]


4\. **Trigonometric functions**

Use `np.linspace` to create an array of 100 numbers between $0$ and $2\pi$ (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the `sin` and `cos` functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

5\. **Matrices**

Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

6\. **Broadcasting**

Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles.

The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

7\. **Prime numbers sieve**

Compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).

  * Constract a shape (N,) boolean array, which is the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (with `timeit`); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

8\. **Diffusion using random walk**

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of many random walkers after a given amount of time.

*Hint*: create a 2D array where each row represents a walker, and each column represents a time step.

  * Take 1000 walkers and let them walk for 200 steps
  * Use `randint` to create a 2D array of size $walkers \times steps$ with values -1 or 1
  * Calculate the walking distances for each walker (e.g. by summing the elements in each row)
  * Take the square of the previously-obtained array (element-wise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * **Optional**: plot the average distances ($\sqrt(distance^2)$) as a function of time (step)