1\. **Reductions**

Find the total mean, and the mean for each row and column of the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [3]:
import pandas as pd
import numpy as np

m = np.arange(12).reshape((3,4))
print(m)

mean = np.mean(m)

# mean for columns and rows
mean_column = np.mean(m, axis=0)
mean_row = np.mean(m, axis=1)

print('total mean: ',mean)
print('row mean: ', mean_row)
print('column mean: ',mean_column)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
total mean:  5.5
row mean:  [1.5 5.5 9.5]
column mean:  [4. 5. 6. 7.]


2\. **Outer product**

Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [9]:
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])

# 1 - outer

result1 = np.outer(u,v)
print('result for 1')
print( result1 )

#2 for loop

result2 = []
for i in range(len(u)):
    row = []
    for j in range(len(v)):
        row.append(u[i] * v[j])
    result2.append(row)

print('result for 2')
print( result2 )


#3 broadcasting

u_v = u * v.reshape(4,1)
print('result for 3')
result3 = u_v.transpose()
print(result3)

result for 1
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
result for 2
[[2, 4, 6, 8], [6, 12, 18, 24], [10, 20, 30, 40], [14, 28, 42, 56]]
result for 3
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. **Matrix masking**

Create a 10 by 6 matrix of float random numbers, distributed between 0 and 3 according to a flat distribution.

After creating the matrix, set all entries $< 0.3$ to zero using a mask.

In [13]:
start = np.linspace(0, 0.5,10)
end = np.linspace(2.5, 3,10)

matrix = np.linspace(start,end,6)
print(matrix)

for i in range(0,3):
    matrix[:,i] = [0]

print('result after mask')
print(matrix)

[[0.         0.05555556 0.11111111 0.16666667 0.22222222 0.27777778
  0.33333333 0.38888889 0.44444444 0.5       ]
 [0.5        0.55555556 0.61111111 0.66666667 0.72222222 0.77777778
  0.83333333 0.88888889 0.94444444 1.        ]
 [1.         1.05555556 1.11111111 1.16666667 1.22222222 1.27777778
  1.33333333 1.38888889 1.44444444 1.5       ]
 [1.5        1.55555556 1.61111111 1.66666667 1.72222222 1.77777778
  1.83333333 1.88888889 1.94444444 2.        ]
 [2.         2.05555556 2.11111111 2.16666667 2.22222222 2.27777778
  2.33333333 2.38888889 2.44444444 2.5       ]
 [2.5        2.55555556 2.61111111 2.66666667 2.72222222 2.77777778
  2.83333333 2.88888889 2.94444444 3.        ]]
[[0.         0.         0.         0.16666667 0.22222222 0.27777778
  0.33333333 0.38888889 0.44444444 0.5       ]
 [0.         0.         0.         0.66666667 0.72222222 0.77777778
  0.83333333 0.88888889 0.94444444 1.        ]
 [0.         0.         0.         1.16666667 1.22222222 1.27777778
  1.3333333

4\. **Trigonometric functions**

Use `np.linspace` to create an array of 100 numbers between $0$ and $2\pi$ (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the `sin` and `cos` functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

In [8]:
import math
import matplotlib.pyplot as plt

arr = np.linspace(0,2*math.pi,100)
print(arr)

result1 = arr[::10] # extracts every 10th element
result1 = result1[1::]
print('After every 10th element is extracted')
print(result1)


result2 = result1[::-1] # reverse the array
print('Reverse array')
print(result2)


elements = np.abs(np.sin(arr)-np.cos(arr)) < 0.1
print('Extracted elements that |sin-cos| < 0.1')
result3 = arr[elements]
print(result3)

#Optional


[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

5\. **Matrices**

Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [19]:
arr1 = range(1,11) 
arr2 = range(1,11)

# Create matrix by using
mult_table = [[i*j for j in arr1] for i in arr2]
matrix = np.array(mult_table)
print(matrix)
print("Trace: ",np.trace(matrix))

#Extract the anti-diagonal matrix
result = np.fliplr(matrix).diagonal()
print("Anti-diagonal :", result)

#Extract the diagonal offset by 1 upwards
print("Diagonal offset: " ,np.diagonal(matrix,1))

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
Trace:  385
Anti-diagonal : [10 18 24 28 30 30 28 24 18 10]
Diagonal offset:  [ 2  6 12 20 30 42 56 72 90]


6\. **Broadcasting**

Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles.

The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [20]:
position = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])
print("position:", position)
distance = np.abs(position-position[:, np.newaxis])
print("distances:","\n",distance)

distance_km = distance * 1.609
print("distances in km:")
print(distance_km)

in miles: [   0  198  303  736  871 1175 1475 1544 1913 2448]
distances: 
 [[   0  198  303  736  871 1175 1475 1544 1913 2448]
 [ 198    0  105  538  673  977 1277 1346 1715 2250]
 [ 303  105    0  433  568  872 1172 1241 1610 2145]
 [ 736  538  433    0  135  439  739  808 1177 1712]
 [ 871  673  568  135    0  304  604  673 1042 1577]
 [1175  977  872  439  304    0  300  369  738 1273]
 [1475 1277 1172  739  604  300    0   69  438  973]
 [1544 1346 1241  808  673  369   69    0  369  904]
 [1913 1715 1610 1177 1042  738  438  369    0  535]
 [2448 2250 2145 1712 1577 1273  973  904  535    0]]
distance array in km: 
 [[   0.        318.650112  487.631232 1184.477184 1401.738624 1890.9792
  2373.7824   2484.827136 3078.675072 3939.674112]
 [ 318.650112    0.        168.98112   865.827072 1083.088512 1572.329088
  2055.132288 2166.177024 2760.02496  3621.024   ]
 [ 487.631232  168.98112     0.        696.845952  914.107392 1403.347968
  1886.151168 1997.195904 2591.04384  3452.04288

7\. **Prime numbers sieve**

Compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).

  * Constract a shape (N,) boolean array, which is the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (with `timeit`); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [1]:
import timeit

# Sieve of Erathosthenes
def SieveOfEratosthenes(n):
    prime_num = []
    prime = [True for i in range(n + 1)]

    prime[0]= False
    prime[1]= False
    p = 2

    while (p * p <= n):
        if (prime[p] == True):
            for i in range(p ** 2, n + 1, p):
                prime[i] = False
        p += 1
        
    for p in range(n + 1):
        if prime[p] == True:
            prime_num.append(p)
    return prime_num
            

# measure the time
starttime = timeit.default_timer()
print(SieveOfEratosthenes(1000))
endtime = timeit.default_timer()
print("The time difference is :", endtime - starttime)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997]
The time difference is : 0.00118830000000969


8\. **Diffusion using random walk**

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of many random walkers after a given amount of time.

*Hint*: create a 2D array where each row represents a walker, and each column represents a time step.

  * Take 1000 walkers and let them walk for 200 steps
  * Use `randint` to create a 2D array of size $walkers \times steps$ with values -1 or 1
  * Calculate the walking distances for each walker (e.g. by summing the elements in each row)
  * Take the square of the previously-obtained array (element-wise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * **Optional**: plot the average distances ($\sqrt(distance^2)$) as a function of time (step)