Q1

In [1]:
import numpy as np

m = np.arange(12).reshape((3,4))
print("Mean:", m.mean())


for i in range(3):
  print("row %d mean: "%(i+1), np.mean(m[i]))


for i in range(4):
  print("column %d mean: "%(i+1), np.mean(m, axis = 0)[i])

Mean: 5.5
row 1 mean:  1.5
row 2 mean:  5.5
row 3 mean:  9.5
column 1 mean:  4.0
column 2 mean:  5.0
column 3 mean:  6.0
column 4 mean:  7.0


Q2

In [2]:
import numpy as np


u = np.array([1, 3, 5, 7]) 
v = np.array([2, 4, 6, 8])


print(np.outer(u,v))
out= np.zeros((u.shape[0],v.shape[0])) 
for i in range(u.shape[0]):
    for j in range(v.shape[0]):
        out[i][j]= u[i]*v[j]  

print(out)

out2=u*v.reshape(len(v),1)   

print(out2)

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
[[ 2.  4.  6.  8.]
 [ 6. 12. 18. 24.]
 [10. 20. 30. 40.]
 [14. 28. 42. 56.]]
[[ 2  6 10 14]
 [ 4 12 20 28]
 [ 6 18 30 42]
 [ 8 24 40 56]]


Q3

In [3]:
m= 3*np.random.rand(10, 6)
elon= m <0.3   ##creating the mask
m[elon]=0  ##applying the condition
print(m)


[[1.82407528 1.70323524 1.61137418 2.24561931 1.63103424 0.83836652]
 [2.57903907 0.62015529 0.         0.39584814 1.67389292 1.613528  ]
 [0.         2.66787835 2.60396393 0.58209588 1.4224874  1.38208178]
 [1.91240117 0.78240042 2.49481187 2.44925647 0.77650193 0.48063757]
 [1.83560377 0.98840871 1.39750835 0.30978798 2.35540138 0.        ]
 [0.         0.         0.79275043 1.52834779 1.70364068 0.36071818]
 [2.17131517 2.91080226 0.34233196 0.99562946 0.36274198 2.33565137]
 [0.         1.4849496  1.30099077 0.54601219 2.16782144 0.53052075]
 [0.86546539 0.37024941 2.00451127 1.58268635 1.15959844 0.6002337 ]
 [2.85162102 2.58856472 2.57015206 1.83425501 2.1612116  0.34223186]]


Q4

In [4]:
import numpy as np
import math


arr=np.linspace(0,2*math.pi,100)
elon=(np.absolute((np.sin(arr)-np.cos(arr)))<0.1)
print("Extracting :  \n")

print(arr[0:100:10]) 

print("Reversing :   \n")

print(arr[::-1])



v= arr[elon]

print("Secondary ext :   \n")

print(v)

Extracting :  

[0.         0.63466518 1.26933037 1.90399555 2.53866073 3.17332591
 3.8079911  4.44265628 5.07732146 5.71198664]
Reversing :   

[6.28318531 6.21971879 6.15625227 6.09278575 6.02931923 5.96585272
 5.9023862  5.83891968 5.77545316 5.71198664 5.64852012 5.58505361
 5.52158709 5.45812057 5.39465405 5.33118753 5.26772102 5.2042545
 5.14078798 5.07732146 5.01385494 4.95038842 4.88692191 4.82345539
 4.75998887 4.69652235 4.63305583 4.56958931 4.5061228  4.44265628
 4.37918976 4.31572324 4.25225672 4.1887902  4.12532369 4.06185717
 3.99839065 3.93492413 3.87145761 3.8079911  3.74452458 3.68105806
 3.61759154 3.55412502 3.4906585  3.42719199 3.36372547 3.30025895
 3.23679243 3.17332591 3.10985939 3.04639288 2.98292636 2.91945984
 2.85599332 2.7925268  2.72906028 2.66559377 2.60212725 2.53866073
 2.47519421 2.41172769 2.34826118 2.28479466 2.22132814 2.15786162
 2.0943951  2.03092858 1.96746207 1.90399555 1.84052903 1.77706251
 1.71359599 1.65012947 1.58666296 1.52319644 1.45972

Q5

In [5]:
import numpy as np


m=np.arange(1,11)
xx=m*m.reshape(len(m),1) 

print("Trace", xx.trace()) 
flpp=np.flip(xx, axis=0) 

antiD=np.diag(flpp)   

print("Anti-diagonal: ", antiD)
newD=np.diag(xx,1) 



print("Diagonal: ",newD)

Trace 385
Anti-diagonal:  [10 18 24 28 30 30 28 24 18 10]
Diagonal:  [ 2  6 12 20 30 42 56 72 90]


Q6

In [6]:
position = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])
d = np.abs(position - position[:, np.newaxis])


x = 1.6
d_km = x * d
print(d_km)

[[   0.   316.8  484.8 1177.6 1393.6 1880.  2360.  2470.4 3060.8 3916.8]
 [ 316.8    0.   168.   860.8 1076.8 1563.2 2043.2 2153.6 2744.  3600. ]
 [ 484.8  168.     0.   692.8  908.8 1395.2 1875.2 1985.6 2576.  3432. ]
 [1177.6  860.8  692.8    0.   216.   702.4 1182.4 1292.8 1883.2 2739.2]
 [1393.6 1076.8  908.8  216.     0.   486.4  966.4 1076.8 1667.2 2523.2]
 [1880.  1563.2 1395.2  702.4  486.4    0.   480.   590.4 1180.8 2036.8]
 [2360.  2043.2 1875.2 1182.4  966.4  480.     0.   110.4  700.8 1556.8]
 [2470.4 2153.6 1985.6 1292.8 1076.8  590.4  110.4    0.   590.4 1446.4]
 [3060.8 2744.  2576.  1883.2 1667.2 1180.8  700.8  590.4    0.   856. ]
 [3916.8 3600.  3432.  2739.2 2523.2 2036.8 1556.8 1446.4  856.     0. ]]


Q7

In [9]:
import numpy as np
import timeit




def optimus(N):
    num=[x for x in range(N+1)]
    
    elon=[] 
    
    for i in range (N+1):
        
        prime=True
        for x in range (i):
            if(x>1 and i%x==0): 
                prime=False
        elon.append(prime) 
        
    num=np.array(num)
    optimus=num[elon]
    return optimus


print("Prime numbers between 0-99:\n",optimus(99))
N=100

start=timeit.default_timer()
optimus(N)

end=timeit.default_timer()

time=end-start
print("When N =", N, "execution time is", time)


N=200
start=timeit.default_timer()
optimus(N)

end=timeit.default_timer()

time=end-start

print("When N =", N, "execution time is", time)
N=400
start=timeit.default_timer()
optimus(N)
end=timeit.default_timer()
time=end-start
print("When N =", N, "execution time is", time)



### ??????????##########
def erat(N):
    d=np.arange(0,N+1)
    era_elon = np.full(N+1, True)
    for i in range(2, int(N**.5 + 1)):        
        if (era_elon[i] == True): 
            era_elon[i**2::i] = False   
    d = d[era_elon]
    return d


erat(99)




Prime numbers between 0-99:
 [ 0  1  2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79
 83 89 97]
When N = 100 execution time is 0.0005746999999978186
When N = 200 execution time is 0.001697899999999919
When N = 400 execution time is 0.007035800000000592


array([ 0,  1,  2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47,
       53, 59, 61, 67, 71, 73, 79, 83, 89, 97])

Q8

In [10]:
import numpy as np

walks=np.random.randint(-1,2,(1000,200)) ##random matrix
wd=walks.sum(axis=1) 
sqwd=np.square(wd)
mean=wd.mean(axis=0)
print(walks)

print("Every walkers distance:\n", wd)

print("Mean distances:\n", mean)

[[-1  1  1 ...  1  0  1]
 [ 1  0 -1 ...  1 -1  1]
 [ 1 -1  1 ...  0  0 -1]
 ...
 [ 0  0  1 ...  0 -1  1]
 [-1 -1 -1 ...  1  0 -1]
 [ 1  0 -1 ...  0 -1  1]]
Every walkers distance:
 [ 23 -12  18 -12  -1 -16   4 -22  15  -6 -10  -7 -26  -9  15  -6  -6   5
  -2 -10 -10  15   9   6   4   2  23  -1   6   8  -4   1  -2   1  -2 -18
  18   4  16 -12 -11   8   3   1  -4   9   2 -15  -7   4 -13 -34   4  -6
  11  16  -8  -3 -14  -5 -21  -8 -24   8  -4  12  -8   7 -16  -2  -5  -2
  -5 -11   7  11  -2   7  25 -13  10 -36  13   8  12  -2   5  -6   0   6
  -4   1 -18   9 -12   9   8   1   6   0   1 -10  -7 -17  -4 -18   7  -2
 -15  -1  -1   0 -11   0   7   5  -4  -7  15  -1  -5  -7   0  -2  -3  -6
 -12   5  -6 -11   0  -5 -10  22   0   1 -20   6  -4   5 -10   5 -20  12
   2  -8  11   0  -1  -9  -5  14  20   6   8  -6 -13   3  -1 -18  -6  14
   3   3  27  -4  -8  10  10   0  -7  -4 -34 -45  21 -12   3   4  -8  15
 -10  -4 -20  32 -12  12  -1 -11   6   0  -2  -3   4   1 -19  -1  15  -7
 -10  -4  -6  38