In [1]:
# Import for the whole program
import pandas as pd
import numpy as np
import struct
import pandas as pd
import random

1\. **Text files**

Perform the following operations on plain `txt` files:

+ create a list of integrer numbers and then save it to a text file named `data_int.txt`. Run the `cat` command to print the content of the file.
+ create a matrix of 5x5 floats and then save it to a text file named `data_float.txt`. Use the `cat` command to print the content of the file.
+ load the `txt` file of the previous point and convert it to a `csv` file by hand.

In [2]:
#list of integers
dataW = random.sample(range(0, 100), 25)
# Create new file on folder Es6SupportFiles
f = open('Es6Files/data_int.txt', 'w')
# Write on the file
f.write(' '.join([str(i) for i in dataW]))
f.close()

# Read from the file
from os import system
system("cat Es6Files/data_int.txt")
print()

# 5x5 matrix
dataMW = np.reshape(dataW, (5, 5))
# Create new file on folder Es6SupportFiles
f = open('Es6Files/data_int.txt', 'w')
# Write on the file
f.write(np.array2string(dataMW))
f.close()

system("cat Es6Files/data_int.txt")
print()


out = ""
with open('Es6Files/data_int.txt', mode = 'r', ) as f:
    for line in f:
		# delete square brakets
        line = line.replace("[", "")
        line = line.replace("]", "")
        l = line.split(" ")
		# concat the splitted elemnt without considering empty fields
        w = ','.join([str(i) for i in l if str(i)!= ''])
        out = out+w
f = open('Es6Files/data_int.txt', 'w')
# Write on the file
f.write(out)
f.close()

system("cat Es6Files/data_int.txt")
print()

64 41 79 93 88 75 80 38 69 91 4 25 94 72 74 86 92 12 42 54 99 52 55 66 21
[[64 41 79 93 88]
 [75 80 38 69 91]
 [ 4 25 94 72 74]
 [86 92 12 42 54]
 [99 52 55 66 21]]
64,41,79,93,88
75,80,38,69,91
4,25,94,72,74
86,92,12,42,54
99,52,55,66,21


2\. **JSON files**

Load the file *user_data.json*, which can be found at:

- https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

and filter the data by the "CreditCardType" when it equals to "American Express". Than save the data to a new CSV file.

In [7]:
f = open('Es6Files/user_data.json')

import json
data = json.load(f)
f.close()
# Filter using list comprehension
filtered = [i for i in data if i["CreditCardType"] == "American Express"]

import csv
# Create the csv file
f = open('Es6Files/user_data_filtered.csv', 'w')
 
 
# create the csv writer object
csv_writer = csv.writer(f)
 
# Counter variable used for writing
# headers to the CSV file
count = 0
for el in filtered:
    if count == 0:
        # Writing headers of CSV file
        header = el.keys()
        csv_writer.writerow(header)
        count += 1
    # Writing data of CSV file
    csv_writer.writerow(el.values())
    print(el)
f.close()


{'ID': '2', 'JobTitle': 'Investment  Advisor', 'EmailAddress': 'Clint_Thorpe5003@bulaffy.com', 'FirstNameLastName': 'Clint Thorpe', 'CreditCard': '7083-8766-0251-2345', 'CreditCardType': 'American Express'}
{'ID': '12', 'JobTitle': 'Retail Trainee', 'EmailAddress': 'Phillip_Carpenter9505@famism.biz', 'FirstNameLastName': 'Phillip Carpenter', 'CreditCard': '3657-0088-0820-5247', 'CreditCardType': 'American Express'}
{'ID': '28', 'JobTitle': 'Project Manager', 'EmailAddress': 'Russel_Graves1378@extex.org', 'FirstNameLastName': 'Russel Graves', 'CreditCard': '6718-4818-8011-6024', 'CreditCardType': 'American Express'}
{'ID': '39', 'JobTitle': 'Stockbroker', 'EmailAddress': 'Leanne_Newton1268@typill.biz', 'FirstNameLastName': 'Leanne Newton', 'CreditCard': '5438-0816-4166-4847', 'CreditCardType': 'American Express'}
{'ID': '57', 'JobTitle': 'Budget Analyst', 'EmailAddress': 'Tony_Giles1960@iatim.tech', 'FirstNameLastName': 'Tony Giles', 'CreditCard': '8130-3425-7573-7745', 'CreditCardType'

3\. **CSV files with Pandas**

Load the file from this url:

- https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

with Pandas. 

+ explore and print the DataFrame
+ calculate, using `groupby()`, the average value of each feature, separately for each class
+ save the file in a JSON format.

In [4]:
# explore and print the DataFrame
f = open('Es6Files/mushrooms_categorized.csv')
df = pd.read_csv(f)
f.close()
print(df)

#average value of each feature, separately for each class
meaned = df.groupby('class').mean()

# save the file in a JSON format
f = open('Es6Files/mushrooms_categorized_mod.json', 'w')
meaned.to_json(f)
f.close()


      class  cap-shape  cap-surface  cap-color  bruises  odor  \
0         1          5            2          4        1     6   
1         0          5            2          9        1     0   
2         0          0            2          8        1     3   
3         1          5            3          8        1     6   
4         0          5            2          3        0     5   
...     ...        ...          ...        ...      ...   ...   
8119      0          3            2          4        0     5   
8120      0          5            2          4        0     5   
8121      0          2            2          4        0     5   
8122      1          3            3          4        0     8   
8123      0          5            2          4        0     5   

      gill-attachment  gill-spacing  gill-size  gill-color  ...  \
0                   1             0          1           4  ...   
1                   1             0          0           4  ...   
2                 

4\. **Reading the credit card numbers**

Get the binary file named *credit_card.dat* from this address:

- https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

and convert the data into the real credit card number, knowing that:
- each line corresponds to a credit card number, which consists of 16 characters (which are numbers in the 0-9 range) divided in 4 blocks, with a whitespace between each block
- each character is written using a 6 bit binary representation (including the whitespace)
- the final 4 bits of each line are a padding used to determine the end of the line, and can be ignored

*Hint*: convert the binary numbers to the decimal representation first, and then use the `chr()` function to convert the latter to a char

In [5]:
# string where we will copy the values
data=""

with open("Es6Files/credit_card.dat","rb") as f:
	for line in f:
		for j in range(0, len(line),6):
			# Read 6 bits to 6
			bin=line[j:j+6]
			# add to the string
			data+=chr(int(bin,2))
		data+="\n"
print(data)  


7648 5673 3775 2271

3257 8247 3354 2266

2722 0001 4011 6652

0661 3063 3742 3150

0432 1608 1462 4742

5827 2027 8785 7303

5774 8528 2087 1117

8140 1210 6352 2845

5764 1133 7301 7100

6456 1737 4126 6726

1228 8631 7382 0000

7051 0160 5374 3166

0618 3587 1630 6376

1545 5454 7444 5636

6735 3116 3202 6834

7287 5011 1547 8413

7033 2607 3328 4200

2568 5244 1874 5024

1684 2253 7570 7118

0672 2576 0575 6631

6332 8353 8787 1340

1813 3361 1175 4211

2477 6450 8840 2368

5512 3505 2563 1326

3083 7882 0621 0025

4521 5148 8045 0334

7563 3654 8713 5787

8324 2664 0476 5561

0565 2504 7168 3510

5107 5507 1767 0738

2462 1821 2448 1443

2788 0638 6861 6554

5851 5873 5474 0547

0670 1004 4013 2655

5874 5506 3048 0806

2805 5401 8462 1260

5083 8406 6310 1862

1076 1445 3013 2266

8440 4804 4844 5277

4758 6141 0686 1387

7586 0675 0315 2568

2544 1258 7432 5165

3474 5023 4434 5626

1410 0270 0434 5086

7315 4446 1104 4215

0224 7742 8300 0266

0170 2700 3145 0640

2006 2437 805

5\. **Write data to a binary file**

a) Start from the `data/data_000637.txt` file that we have used during the previous lectures, and convert it to a binary file according to the format defined below:

*Hints*:
- Read the first 10 lines using Pandas
- Iterate over the DataFrame rows
- For every row, ``pack'' the values (features) into a single 64-bit word, according to the format specified above. Use bit-wise shifts and operators to do so.
- Write each 64-bit word to a binary file. You can use `struct` in this way:
```
binary_file.write( struct.pack('<q', word) )
```
where `word` is the 64-bit word.
- Close the file after completing the loop.

b) Check that the binary file is correctly written by reading it with the code used in the lecture `06_OSEMN.ipynb`, and verify that the content of the `txt` and binary files is consistent.

c) What is the difference of the size on disk between equivalent `txt` and binary files?

In [12]:
# Read the file to be converted to binary, convert to dataframe, loc first 10 row
data=pd.DataFrame(pd.read_csv('Es6Files/data_000637.txt',sep=",")).loc[0:9]
with open('Es6Files/binary_file.dat','wb') as bf:
	for line in data.values:
		# Line in .txt file is in the form [         1          0        123 3869200167       2374         26]
		#                                            ^line[0]   ^line[1]      ....              ^line[4]    ^ line[5]
		w	= (line[5]<<0) # Shift the bits of the last element left by 0 and put in w
		w	= (line[4]<<5) | w
		w	= (line[3]<<17) | w
		w	= (line[2]<<49) | w
		w	= (line[1]<<58) | w
		w	= (line[0]<<62) | w
		bf.write(struct.pack('<q', w))


# Professor code
with open('Es6Files/binary_file.dat', 'rb') as file:
    file_content = file.read()
    word_counter = 0
    word_size = 8 # size of the word in bytes
    for i in range(0, len(file_content), word_size):
        word_counter += 1
        if word_counter > 10: break
        word = struct.unpack('<q', file_content[i : i + word_size])[0] # get an 8-byte word
        head     = (word >> 62) & 0x3
        fpga     = (word >> 58) & 0xF
        tdc_chan = (word >> 49) & 0x1FF
        orb_cnt  = (word >> 17) & 0xFFFFFFFF
        bx       = (word >> 5 ) & 0xFFF
        tdc_meas = (word >> 0 ) & 0x1F
        #if i == 0: print ('{0}\t{1}\t{2}\t{3}\t{4}\t{5}'.format('HEAD', 'FPGA', 'CHANNEL', 'ORBIT_CNT', 'BX_CNT', 'TDC_MEAS'))
        print('{0}\t{1}\t{2}\t{3}\t{4}\t{5}'.format(head, fpga, tdc_chan, orb_cnt, bx, tdc_meas))
        entry = {'HEAD' : head, 'FPGA' : fpga, 'CHANNEL' : tdc_chan, 'ORBIT_CNT' : orb_cnt, 'BX_CNT' : bx, 'TDC_MEAS' : tdc_meas}
        df = df.append(entry, ignore_index=True)


# The binary file size is 10.5 MB while the .txt file is 33.2 MB


1	0	123	3869200167	2374	26
1	0	124	3869200167	2374	27
1	0	63	3869200167	2553	28
1	0	64	3869200167	2558	19
1	0	64	3869200167	2760	25
1	0	63	3869200167	2762	4
1	0	61	3869200167	2772	14
1	0	139	3869200167	2776	0
1	0	62	3869200167	2774	21
1	0	60	3869200167	2788	7
