In [1]:
import pandas as pd
import numpy as np
import csv
import numpy.random as npr

1\. **Text files**

Perform the following operations on plain `txt` files:

+ create a list of integrer numbers and then save it to a text file named `data_int.txt`. Run the `cat` command to print the content of the file.
+ create a matrix of 5x5 floats and then save it to a text file named `data_float.txt`. Use the `cat` command to print the content of the file.
+ load the `txt` file of the previous point and convert it to a `csv` file by hand.

In [2]:
numbers_list = [i for i in range(30)]

out_file_name = "data_int.txt"
with open(out_file_name, 'w') as outfile:
    for i in range(len(numbers_list)):
        outfile.write(str(numbers_list[i]) + '\n')

npr.seed(123)        
random_matrix = npr.rand(5,5)

out_file_name = "data_float.txt"
with open(out_file_name, 'w') as outfile:
    for i in range(5):
        for j in range(5):
            if j == 4:
                outfile.write(str(random_matrix[i, j]) + '\n')
            else:
                outfile.write(str(random_matrix[i, j]) + ' ')

with open('data_float.csv', 'w+') as csvFile:
    writer = csv.writer(csvFile,delimiter=',')
    data = np.loadtxt("data_float.txt")
    print(type(data))
    for row in data:
        print(row)
        writer.writerow(row)

<class 'numpy.ndarray'>
[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]
[0.42310646 0.9807642  0.68482974 0.4809319  0.39211752]
[0.34317802 0.72904971 0.43857224 0.0596779  0.39804426]
[0.73799541 0.18249173 0.17545176 0.53155137 0.53182759]
[0.63440096 0.84943179 0.72445532 0.61102351 0.72244338]


2\. **JSON files**

Load the file *user_data.json*, which can be found at:

- https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

and filter the data by the "CreditCardType" when it equals to "American Express". Than save the data to a new CSV file.

In [3]:
import json 

data_input = json.load(open('user_data.json'))
data_filtered = [x for x in data_input if x['CreditCardType'] == 'American Express']
data_filtered

[{'ID': '2',
  'JobTitle': 'Investment  Advisor',
  'EmailAddress': 'Clint_Thorpe5003@bulaffy.com',
  'FirstNameLastName': 'Clint Thorpe',
  'CreditCard': '7083-8766-0251-2345',
  'CreditCardType': 'American Express'},
 {'ID': '12',
  'JobTitle': 'Retail Trainee',
  'EmailAddress': 'Phillip_Carpenter9505@famism.biz',
  'FirstNameLastName': 'Phillip Carpenter',
  'CreditCard': '3657-0088-0820-5247',
  'CreditCardType': 'American Express'},
 {'ID': '28',
  'JobTitle': 'Project Manager',
  'EmailAddress': 'Russel_Graves1378@extex.org',
  'FirstNameLastName': 'Russel Graves',
  'CreditCard': '6718-4818-8011-6024',
  'CreditCardType': 'American Express'},
 {'ID': '39',
  'JobTitle': 'Stockbroker',
  'EmailAddress': 'Leanne_Newton1268@typill.biz',
  'FirstNameLastName': 'Leanne Newton',
  'CreditCard': '5438-0816-4166-4847',
  'CreditCardType': 'American Express'},
 {'ID': '57',
  'JobTitle': 'Budget Analyst',
  'EmailAddress': 'Tony_Giles1960@iatim.tech',
  'FirstNameLastName': 'Tony Giles'

In [4]:
data_filtered_j = json.dumps(data_filtered)

with open("filtered_user_data.json", "w") as outfile:
    outfile.write(data_filtered_j)

with open('filtered_user_data.json', encoding='utf-8') as inputfile:
    df = pd.read_json(inputfile)

df.to_csv('filtered_user_data_csv.csv', encoding='utf-8', index=False)

3\. **CSV files with Pandas**

Load the file from this url:

- https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

with Pandas. 

+ explore and print the DataFrame
+ calculate, using `groupby()`, the average value of each feature, separately for each class
+ save the file in a JSON format.

In [5]:
mushrooms = pd.read_csv('mushrooms_categorized.csv')
mushrooms

class  cap-shape  cap-surface  cap-color  bruises  odor  \
0         1          5            2          4        1     6   
1         0          5            2          9        1     0   
2         0          0            2          8        1     3   
3         1          5            3          8        1     6   
4         0          5            2          3        0     5   
...     ...        ...          ...        ...      ...   ...   
8119      0          3            2          4        0     5   
8120      0          5            2          4        0     5   
8121      0          2            2          4        0     5   
8122      1          3            3          4        0     8   
8123      0          5            2          4        0     5   

      gill-attachment  gill-spacing  gill-size  gill-color  ...  \
0                   1             0          1           4  ...   
1                   1             0          0           4  ...   
2                   1             0          0           5  ...   
3                   1             0          1           5  ...   
4                   1             1          0           4  ...   
...               ...           ...        ...         ...  ...   
8119                0             0          0          11  ...   
8120                0             0          0          11  ...   
8121                0             0          0           5  ...   
8122                1             0          1           0  ...   
8123                0             0          0          11  ...   

      stalk-surface-below-ring  stalk-color-above-ring  \
0                            2                       7   
1                            2                       7   
2                            2                       7   
3                            2                       7   
4                            2                       7   
...                        ...                     ...   
8119                         2                       5   
8120                         2                       5   
8121                         2                       5   
8122                         1                       7   
8123                         2                       5   

      stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
0                          7          0           2            1          4   
1                          7          0           2            1          4   
2                          7          0           2            1          4   
3                          7          0           2            1          4   
4                          7          0           2            1          0   
...                      ...        ...         ...          ...        ...   
8119                       5          0           1            1          4   
8120                       5          0           0            1          4   
8121                       5          0           1            1          4   
8122                       7          0           2            1          0   
8123                       5          0           1            1          4   

      spore-print-color  population  habitat  
0                     2           3        5  
1                     3           2        1  
2                     3           2        3  
3                     2           3        5  
4                     3           0        1  
...                 ...         ...      ...  
8119                  0           1        2  
8120                  0           4        2  
8121                  0           1        2  
8122                  7           4        2  
8123                  4           1        2  

[8124 rows x 23 columns]

In [6]:
categories = list(mushrooms.columns.values)
mushrooms_media = mushrooms.groupby('class')[categories[1:len(categories)]].mean()
mushrooms_media

cap-shape  cap-surface  cap-color   bruises      odor  gill-attachment  \
class                                                                           
0       3.266160     1.615970   4.581749  0.653992  4.334601         0.954373   
1       3.436159     2.055158   4.421859  0.159346  3.940756         0.995403   

       gill-spacing  gill-size  gill-color  stalk-shape  ...  \
class                                                    ...   
0          0.285171   0.068441    6.622624     0.615970  ...   
1          0.028601   0.567926    2.863636     0.514811  ...   

       stalk-surface-below-ring  stalk-color-above-ring  \
class                                                     
0                      1.798479                6.098859   
1                      1.394280                5.512768   

       stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
class                                                                          
0                    6.064639        0.0    1.931559     1.125475   3.007605   
1                    5.504597        0.0    2.002043     1.009193   1.522983   

       spore-print-color  population   habitat  
class                                           
0               3.201521    3.283270  1.148289  
1               4.021450    4.031665  1.895812  

[2 rows x 22 columns]

In [7]:
mushrooms_media.to_json('mushrooms.json')

4\. **Reading the credit card numbers**

Get the binary file named *credit_card.dat* from this address:

- https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

and convert the data into the real credit card number, knowing that:
- each line corresponds to a credit card number, which consists of 16 characters (which are numbers in the 0-9 range) divided in 4 blocks, with a whitespace between each block
- each character is written using a 6 bit binary representation (including the whitespace)
- the final 4 bits of each line are a padding used to determine the end of the line, and can be ignored

*Hint*: convert the binary numbers to the decimal representation first, and then use the `chr()` function to convert the latter to a char

In [8]:
import csv

datContent = [i.strip().split() for i in open("credit_card.dat").readlines()]
for i in range(len(datContent)-1):
    string = datContent[i][0]
    card_number = []
    j = 2
    while j < len(string)-4 :
        if string[j-2:j+4] == '100000':
            j = j+6 
        else:
            card_number.append(int(string[j:j+4], 2))
            j = j+6
    print(i+1, ": card number", card_number)

1 : card number [7, 6, 4, 8, 5, 6, 7, 3, 3, 7, 7, 5, 2, 2, 7, 1]
2 : card number [3, 2, 5, 7, 8, 2, 4, 7, 3, 3, 5, 4, 2, 2, 6, 6]
3 : card number [2, 7, 2, 2, 0, 0, 0, 1, 4, 0, 1, 1, 6, 6, 5, 2]
4 : card number [0, 6, 6, 1, 3, 0, 6, 3, 3, 7, 4, 2, 3, 1, 5, 0]
5 : card number [0, 4, 3, 2, 1, 6, 0, 8, 1, 4, 6, 2, 4, 7, 4, 2]
6 : card number [5, 8, 2, 7, 2, 0, 2, 7, 8, 7, 8, 5, 7, 3, 0, 3]
7 : card number [5, 7, 7, 4, 8, 5, 2, 8, 2, 0, 8, 7, 1, 1, 1, 7]
8 : card number [8, 1, 4, 0, 1, 2, 1, 0, 6, 3, 5, 2, 2, 8, 4, 5]
9 : card number [5, 7, 6, 4, 1, 1, 3, 3, 7, 3, 0, 1, 7, 1, 0, 0]
10 : card number [6, 4, 5, 6, 1, 7, 3, 7, 4, 1, 2, 6, 6, 7, 2, 6]
11 : card number [1, 2, 2, 8, 8, 6, 3, 1, 7, 3, 8, 2, 0, 0, 0, 0]
12 : card number [7, 0, 5, 1, 0, 1, 6, 0, 5, 3, 7, 4, 3, 1, 6, 6]
13 : card number [0, 6, 1, 8, 3, 5, 8, 7, 1, 6, 3, 0, 6, 3, 7, 6]
14 : card number [1, 5, 4, 5, 5, 4, 5, 4, 7, 4, 4, 4, 5, 6, 3, 6]
15 : card number [6, 7, 3, 5, 3, 1, 1, 6, 3, 2, 0, 2, 6, 8, 3, 4]
16 : card number [7

5\. **Write data to a binary file**

a) Start from the `data/data_000637.txt` file that we have used during the previous lectures, and convert it to a binary file according to the format defined below:

*Hints*:
- Read the first 10 lines using Pandas
- Iterate over the DataFrame rows
- For every row, ``pack'' the values (features) into a single 64-bit word, according to the format specified above. Use bit-wise shifts and operators to do so.
- Write each 64-bit word to a binary file. You can use `struct` in this way:
```
binary_file.write( struct.pack('<q', word) )
```
where `word` is the 64-bit word.
- Close the file after completing the loop.

b) Check that the binary file is correctly written by reading it with the code used in the lecture `06_OSEMN.ipynb`, and verify that the content of the `txt` and binary files is consistent.

c) What is the difference of the size on disk between equivalent `txt` and binary files?

In [9]:
import pandas as pd
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt

file_name = "data_000637.txt"
data = pd.read_csv(file_name, nrows=10)
data

HEAD  FPGA  TDC_CHANNEL   ORBIT_CNT  BX_COUNTER  TDC_MEAS
0     1     0          123  3869200167        2374        26
1     1     0          124  3869200167        2374        27
2     1     0           63  3869200167        2553        28
3     1     0           64  3869200167        2558        19
4     1     0           64  3869200167        2760        25
5     1     0           63  3869200167        2762         4
6     1     0           61  3869200167        2772        14
7     1     0          139  3869200167        2776         0
8     1     0           62  3869200167        2774        21
9     1     0           60  3869200167        2788         7

In [10]:
import struct

with open("binary_data.dat", "wb") as binary_file:
    for i in range(len(data["HEAD"])): 
        
        he = 1 << 62 
        fpga = data.loc[data.index[i],"FPGA"] << 58
        tdcc = data.loc[data.index[i],"TDC_CHANNEL"] << 49
        orbit = data.loc[data.index[i],"ORBIT_CNT"] << 17
        bx = data.loc[data.index[i],"BX_COUNTER"] << 5
        tdcm = data.loc[data.index[i],"TDC_MEAS"]
    
        binary_file.write(struct.pack('<q', word))
    
    binary_file.close()
print("File saved")

File saved


In [11]:
data = {}
columns = ['HEAD', 'FPGA', 'CHANNEL', 'ORBIT_CNT', 'BX_CNT', 'TDC_MEAS']
df = pd.DataFrame({}, columns=columns)

with open('binary_data.dat', 'rb') as file:
    file_content = file.read()
    word_counter = 0
    word_size = 8 # size of the word in bytes
    for i in range(0, len(file_content), word_size):
        word_counter += 1
        if word_counter > 10: break
        word = struct.unpack('<q', file_content[i : i + word_size])[0] # get an 8-byte word
        head     = (word >> 62) & 0x3
        fpga     = (word >> 58) & 0xF
        tdc_chan = (word >> 49) & 0x1FF
        orb_cnt  = (word >> 17) & 0xFFFFFFFF
        bx       = (word >> 5 ) & 0xFFF
        tdc_meas = (word >> 0 ) & 0x1F
        #if i == 0: print ('{0}\t{1}\t{2}\t{3}\t{4}\t{5}'.format('HEAD', 'FPGA', 'CHANNEL', 'ORBIT_CNT', 'BX_CNT', 'TDC_MEAS'))
        #print('{0}\t{1}\t{2}\t{3}\t{4}\t{5}'.format(head, fpga, tdc_chan, orb_cnt, bx, tdc_meas))
        entry = {'HEAD' : head, 'FPGA' : fpga, 'CHANNEL' : tdc_chan, 'ORBIT_CNT' : orb_cnt, 'BX_CNT' : bx, 'TDC_MEAS' : tdc_meas}
        df = df.append(entry, ignore_index=True)

df

HEAD FPGA CHANNEL   ORBIT_CNT BX_CNT TDC_MEAS
0    1    0     123  3869200167   2374       26
1    1    0     124  3869200167   2374       27
2    1    0      63  3869200167   2553       28
3    1    0      64  3869200167   2558       19
4    1    0      64  3869200167   2760       25
5    1    0      63  3869200167   2762        4
6    1    0      61  3869200167   2772       14
7    1    0     139  3869200167   2776        0
8    1    0      62  3869200167   2774       21
9    1    0      60  3869200167   2788        7

In [12]:
print('The binary file is 3 times smaller then the txt file')

The binary file is 3 times smaller then the txt file
