In [1]:
import pandas as pd
import numpy as np
import json
import csv
import os


1\. **Text files**

Perform the following operations on plain `txt` files:

+ create a list of integrer numbers and then save it to a text file named `data_int.txt`. Run the `cat` command to print the content of the file.
+ create a matrix of 5x5 floats and then save it to a text file named `data_float.txt`. Use the `cat` command to print the content of the file.
+ load the `txt` file of the previous point and convert it to a `csv` file by hand.

In [2]:
int_lst = [i for i in range(10)]
 
with open('data_int.txt', 'w') as my_list_file:
  json.dump(int_lst, my_list_file)

!type data_int.txt
float_lst = np.random.uniform(low=0.1, high=1.0, size=(5,5))
 
with open('data_float.txt', 'w') as my_list_file:
  my_list_file.writelines("%s\n" % float_lst)

!type data_float.txt
read_file = pd.read_csv ('data_float.txt')
read_file.to_csv ( "data_float.csv",index=None)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[[0.85555014 0.64734536 0.89131544 0.52414013 0.45847205]
 [0.58835155 0.90739573 0.63215288 0.43008234 0.77223087]
 [0.43152287 0.18507311 0.52506451 0.76081435 0.55599743]
 [0.54522386 0.40271429 0.30240667 0.41754617 0.58455241]
 [0.32198501 0.19007675 0.37677041 0.22748477 0.88485349]]


2\. **JSON files**

Load the file *user_data.json*, which can be found at:

- https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

and filter the data by the "CreditCardType" when it equals to "American Express". Than save the data to a new CSV file.

In [3]:
data = json.load(open('user_data.json'))
filtered = [x for x in data if  (x['CreditCardType'] == 'American Express' )]
print(filtered)

with open('output.json','w') as f:
    json.dump(filtered,f,indent=3)

input_json_file='output.json'
output_csv_file='credit_cards.csv'
with open(input_json_file) as inputfile:
    df = pd.read_json(inputfile)

df.to_csv(output_csv_file, index=False)

[{'ID': '2', 'JobTitle': 'Investment  Advisor', 'EmailAddress': 'Clint_Thorpe5003@bulaffy.com', 'FirstNameLastName': 'Clint Thorpe', 'CreditCard': '7083-8766-0251-2345', 'CreditCardType': 'American Express'}, {'ID': '12', 'JobTitle': 'Retail Trainee', 'EmailAddress': 'Phillip_Carpenter9505@famism.biz', 'FirstNameLastName': 'Phillip Carpenter', 'CreditCard': '3657-0088-0820-5247', 'CreditCardType': 'American Express'}, {'ID': '28', 'JobTitle': 'Project Manager', 'EmailAddress': 'Russel_Graves1378@extex.org', 'FirstNameLastName': 'Russel Graves', 'CreditCard': '6718-4818-8011-6024', 'CreditCardType': 'American Express'}, {'ID': '39', 'JobTitle': 'Stockbroker', 'EmailAddress': 'Leanne_Newton1268@typill.biz', 'FirstNameLastName': 'Leanne Newton', 'CreditCard': '5438-0816-4166-4847', 'CreditCardType': 'American Express'}, {'ID': '57', 'JobTitle': 'Budget Analyst', 'EmailAddress': 'Tony_Giles1960@iatim.tech', 'FirstNameLastName': 'Tony Giles', 'CreditCard': '8130-3425-7573-7745', 'CreditCard

3\. **CSV files with Pandas**

Load the file from this url:

- https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

with Pandas. 

+ explore and print the DataFrame
+ calculate, using `groupby()`, the average value of each feature, separately for each class
+ save the file in a JSON format.

In [4]:
filename = "mushrooms_categorized.csv"
df = pd.read_csv(filename)
print(df)

class_ = df.groupby('class') 
class_.mean().reset_index().to_json('mushrooms_categorized.json')
   

      class  cap-shape  cap-surface  cap-color  bruises  odor  \
0         1          5            2          4        1     6   
1         0          5            2          9        1     0   
2         0          0            2          8        1     3   
3         1          5            3          8        1     6   
4         0          5            2          3        0     5   
...     ...        ...          ...        ...      ...   ...   
8119      0          3            2          4        0     5   
8120      0          5            2          4        0     5   
8121      0          2            2          4        0     5   
8122      1          3            3          4        0     8   
8123      0          5            2          4        0     5   

      gill-attachment  gill-spacing  gill-size  gill-color  ...  \
0                   1             0          1           4  ...   
1                   1             0          0           4  ...   
2                 

4\. **Reading the credit card numbers**

Get the binary file named *credit_card.dat* from this address:

- https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

and convert the data into the real credit card number, knowing that:
- each line corresponds to a credit card number, which consists of 16 characters (which are numbers in the 0-9 range) divided in 4 blocks, with a whitespace between each block
- each character is written using a 6 bit binary representation (including the whitespace)
- the final 4 bits of each line are a padding used to determine the end of the line, and can be ignored

*Hint*: convert the binary numbers to the decimal representation first, and then use the `chr()` function to convert the latter to a char

In [8]:
filename = "credit_card.dat"

with open('credit_card.dat', 'r') as file:
    empty = ''
    for row in file:
        code = ''
        for j in range(0, len(row), 6):
            code += chr(int(row[j:j+6],2))
        empty += code +'\n'

print(empty)

7648 5673 3775 2271

3257 8247 3354 2266

2722 0001 4011 6652

0661 3063 3742 3150

0432 1608 1462 4742

5827 2027 8785 7303

5774 8528 2087 1117

8140 1210 6352 2845

5764 1133 7301 7100

6456 1737 4126 6726

1228 8631 7382 0000

7051 0160 5374 3166

0618 3587 1630 6376

1545 5454 7444 5636

6735 3116 3202 6834

7287 5011 1547 8413

7033 2607 3328 4200

2568 5244 1874 5024

1684 2253 7570 7118

0672 2576 0575 6631

6332 8353 8787 1340

1813 3361 1175 4211

2477 6450 8840 2368

5512 3505 2563 1326

3083 7882 0621 0025

4521 5148 8045 0334

7563 3654 8713 5787

8324 2664 0476 5561

0565 2504 7168 3510

5107 5507 1767 0738

2462 1821 2448 1443

2788 0638 6861 6554

5851 5873 5474 0547

0670 1004 4013 2655

5874 5506 3048 0806

2805 5401 8462 1260

5083 8406 6310 1862

1076 1445 3013 2266

8440 4804 4844 5277

4758 6141 0686 1387

7586 0675 0315 2568

2544 1258 7432 5165

3474 5023 4434 5626

1410 0270 0434 5086

7315 4446 1104 4215

0224 7742 8300 0266

0170 2700 3145 0640

2006 2437 805

5\. **Write data to a binary file**

a) Start from the `data/data_000637.txt` file that we have used during the previous lectures, and convert it to a binary file according to the format defined below:

*Hints*:
- Read the first 10 lines using Pandas
- Iterate over the DataFrame rows
- For every row, ``pack'' the values (features) into a single 64-bit word, according to the format specified above. Use bit-wise shifts and operators to do so.
- Write each 64-bit word to a binary file. You can use `struct` in this way:
```
binary_file.write( struct.pack('<q', word) )
```
where `word` is the 64-bit word.
- Close the file after completing the loop.

b) Check that the binary file is correctly written by reading it with the code used in the lecture `06_OSEMN.ipynb`, and verify that the content of the `txt` and binary files is consistent.

c) What is the difference of the size on disk between equivalent `txt` and binary files?

In [9]:
import pandas as pd
import struct

N = 10  
reduced_df = pd.read_csv("data_000637.txt", nrows = N)
print(reduced_df)
    
    
with open("data_000637.dat", 'wb') as binary_file:
    for x in reduced_df.values : 
        word = (x[5] << 0 )
        word += (x[4] << 5 ) 
        word += (x[3] << 17) 
        word += (x[2] << 49) 
        word += (x[1] << 58)
        word += (x[0] << 62)
        binary_file.write(struct.pack('<q', word))
    
data={}
columns = ['HEAD', 'FPGA', 'TDC_CHANNEL', 'ORBIT_CNT', 'BX_COUNTER', 'TDC_MEAS']
dataFrame = pd.DataFrame({}, columns=columns)
    
with open('data_000637.dat', 'rb') as file:
    file = file.read()
    word_counter = 0
    word_size = 8 
for i in range(0, len(file), word_size):
    word_counter += 1
    if word_counter > reduced_df.shape[0]:
        break 
    word = struct.unpack('<q', file[i : i + word_size])[0] 
    head     = (word >> 62) & 0x3
    fpga     = (word >> 58) & 0xF
    tdc_channel = (word >> 49) & 0x1FF
    orb_cnt  = (word >> 17) & 0xFFFFFFFF
    bx_counter = (word >> 5 ) & 0xFFF
    tdc_meas = (word >> 0 ) & 0x1F
    entries = {'HEAD' : head, 'FPGA' : fpga, 'TDC_CHANNEL' : tdc_channel, 'ORBIT_CNT' : orb_cnt, 'BX_COUNTER' : bx_counter, 'TDC_MEAS' : tdc_meas}
    dataFrame = dataFrame.append(entries, ignore_index=True)

print(dataFrame)

print("The dimension of the binary file is: ",os.stat("data_000637.dat").st_size," bytes")
print("The dimension of the txt file is: ",os.stat("data_000637.txt").st_size," bytes")
print("The difference on the disk between .txt and binary file is: ",os.stat("data_000637.txt").st_size-os.stat("data_000637.dat").st_size," bytes")



   HEAD  FPGA  TDC_CHANNEL   ORBIT_CNT  BX_COUNTER  TDC_MEAS
0     1     0          123  3869200167        2374        26
1     1     0          124  3869200167        2374        27
2     1     0           63  3869200167        2553        28
3     1     0           64  3869200167        2558        19
4     1     0           64  3869200167        2760        25
5     1     0           63  3869200167        2762         4
6     1     0           61  3869200167        2772        14
7     1     0          139  3869200167        2776         0
8     1     0           62  3869200167        2774        21
9     1     0           60  3869200167        2788         7
  HEAD FPGA TDC_CHANNEL   ORBIT_CNT BX_COUNTER TDC_MEAS
0    1    0         123  3869200167       2374       26
1    1    0         124  3869200167       2374       27
2    1    0          63  3869200167       2553       28
3    1    0          64  3869200167       2558       19
4    1    0          64  3869200167       2760   

C:\Users\Alexandru Timis\AppData\Local\Temp\ipykernel_3576\1690667136.py:39: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataFrame = dataFrame.append(entries, ignore_index=True)
C:\Users\Alexandru Timis\AppData\Local\Temp\ipykernel_3576\1690667136.py:39: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataFrame = dataFrame.append(entries, ignore_index=True)
C:\Users\Alexandru Timis\AppData\Local\Temp\ipykernel_3576\1690667136.py:39: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataFrame = dataFrame.append(entries, ignore_index=True)
C:\Users\Alexandru Timis\AppData\Local\Temp\ipykernel_3576\1690667136.py:39: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas