In [2]:
import pandas as pd
import numpy as np
from os import system
import random
import csv
import struct

1\. **Text files**

Perform the following operations on plain `txt` files:

+ create a list of integrer numbers and then save it to a text file named `data_int.txt`. Run the `cat` command to print the content of the file.
+ create a matrix of 5x5 floats and then save it to a text file named `data_float.txt`. Use the `cat` command to print the content of the file.
+ load the `txt` file of the previous point and convert it to a `csv` file by hand.

In [11]:
RandomList = list(np.random.randint(low = 1,high=101,size=200))

out_file_name = "data_int.txt"
with open(out_file_name, 'w') as outfile:
    outfile.write(' '.join([str(i) for i in RandomList])) 
outfile.close()	

system("cat data_int.txt")
#create random matrix of floats
RandomMatrix = np.random.rand(5,5) 

out_file_name2 = "data_float.txt"
with open(out_file_name2, 'w') as outfile2:
    outfile2.write(np.array2string(RandomMatrix)) 
outfile2.close()

system("cat data_float.txt")

out3 = ""
with open('data_float.txt', mode='r') as outfile3:
        for line in outfile3:
            #delete square brakets
            line = line.replace("[", "")
            line = line.replace("]", "")
            l = line.split(" ")
            #concat the splitted elements without considering empty fields
            w = ','.join([str(i) for i in l if str(i)!=''])
            out3 = out3+w

outfile3 = open('data_float.txt', 'w')
outfile3.write(out3)
outfile3.close()    

58 61 88 98 29 88 7 72 21 99 89 94 90 77 67 16 3 70 70 68 44 89 10 91 24 8 62 8 85 8 66 46 10 38 90 51 6 72 59 16 74 12 69 43 20 59 94 76 85 36 92 76 19 20 38 82 53 39 100 61 61 90 73 95 87 12 90 33 58 13 54 44 56 67 51 87 55 13 37 12 22 15 39 93 37 50 59 30 62 97 4 71 51 5 91 41 96 60 85 80 51 84 51 97 25 83 56 7 24 35 38 56 44 32 3 80 72 74 41 66 23 52 54 10 40 50 20 5 13 67 23 54 73 27 88 35 26 22 57 9 95 17 87 68 43 45 37 99 46 17 71 71 59 64 27 88 42 66 60 12 39 79 47 48 3 7 65 65 33 76 73 40 43 66 13 62 78 49 39 59 16 9 12 11 99 2 13 7 40 94 61 28 57 45 48 21 92 15 99 87[[0.56491999 0.62715942 0.4300313  0.70694138 0.49075498]
 [0.84615178 0.95550213 0.53558813 0.4610033  0.94391133]
 [0.38288235 0.97185896 0.34586946 0.46790571 0.17300808]
 [0.85690035 0.60904355 0.12806991 0.30606641 0.11330311]
 [0.77622603 0.49712112 0.87271442 0.31788989 0.07436172]]

2\. **JSON files**

Load the file *user_data.json*, which can be found at:

- https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

and filter the data by the "CreditCardType" when it equals to "American Express". Than save the data to a new CSV file.

In [12]:
import json
import csv

#load the file
f = open('user_data.json')
data = json.load(f)
f.close()
# Filter the data by "CreditCardType" using list comprehension
filtered = [i for i in data if i['CreditCardType'] == 'American Express']

# Create the new csv file
f = open('user_data_filtered.csv', 'w')
# create the csv writer object
csv_writer = csv.writer(f)
 
count = 0
for el in filtered:
    if count == 0: #header
        # Writing headers of CSV file
        header = el.keys()
        csv_writer.writerow(header)
        count += 1
    # Writing data of CSV file
    csv_writer.writerow(el.values()) #elements
f.close()

3\. **CSV files with Pandas**

Load the file from this url:

- https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

with Pandas. 

+ explore and print the DataFrame
+ calculate, using `groupby()`, the average value of each feature, separately for each class
+ save the file in a JSON format.

In [13]:
# Explore and print the DataFrame
f = open('mushrooms_categorized.csv')
df = pd.read_csv(f)
f.close()
print(df)

#average value of each feature, separately for each class
av = df.groupby('class').mean()

# save the file in a JSON format
f = open('mushrooms_categorized_mod.json', 'w')
av.to_json(f)
f.close()

      class  cap-shape  cap-surface  cap-color  bruises  odor  \
0         1          5            2          4        1     6   
1         0          5            2          9        1     0   
2         0          0            2          8        1     3   
3         1          5            3          8        1     6   
4         0          5            2          3        0     5   
...     ...        ...          ...        ...      ...   ...   
8119      0          3            2          4        0     5   
8120      0          5            2          4        0     5   
8121      0          2            2          4        0     5   
8122      1          3            3          4        0     8   
8123      0          5            2          4        0     5   

      gill-attachment  gill-spacing  gill-size  gill-color  ...  \
0                   1             0          1           4  ...   
1                   1             0          0           4  ...   
2                 

4\. **Reading the credit card numbers**

Get the binary file named *credit_card.dat* from this address:

- https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

and convert the data into the real credit card number, knowing that:
- each line corresponds to a credit card number, which consists of 16 characters (which are numbers in the 0-9 range) divided in 4 blocks, with a whitespace between each block
- each character is written using a 6 bit binary representation (including the whitespace)
- the final 4 bits of each line are a padding used to determine the end of the line, and can be ignored

*Hint*: convert the binary numbers to the decimal representation first, and then use the `chr()` function to convert the latter to a char

In [14]:
s = '' #string for the converted values
with open('credit_card.dat', 'rb') as file:
    for line in file:
        for j in range(0, len(line), 6):
            word = line[j:j+6] #read 6 bits
            s+=chr(int(word,2)) #add to the string
        s+='\n'
print(s)

7648 5673 3775 2271

3257 8247 3354 2266

2722 0001 4011 6652

0661 3063 3742 3150

0432 1608 1462 4742

5827 2027 8785 7303

5774 8528 2087 1117

8140 1210 6352 2845

5764 1133 7301 7100

6456 1737 4126 6726

1228 8631 7382 0000

7051 0160 5374 3166

0618 3587 1630 6376

1545 5454 7444 5636

6735 3116 3202 6834

7287 5011 1547 8413

7033 2607 3328 4200

2568 5244 1874 5024

1684 2253 7570 7118

0672 2576 0575 6631

6332 8353 8787 1340

1813 3361 1175 4211

2477 6450 8840 2368

5512 3505 2563 1326

3083 7882 0621 0025

4521 5148 8045 0334

7563 3654 8713 5787

8324 2664 0476 5561

0565 2504 7168 3510

5107 5507 1767 0738

2462 1821 2448 1443

2788 0638 6861 6554

5851 5873 5474 0547

0670 1004 4013 2655

5874 5506 3048 0806

2805 5401 8462 1260

5083 8406 6310 1862

1076 1445 3013 2266

8440 4804 4844 5277

4758 6141 0686 1387

7586 0675 0315 2568

2544 1258 7432 5165

3474 5023 4434 5626

1410 0270 0434 5086

7315 4446 1104 4215

0224 7742 8300 0266

0170 2700 3145 0640

2006 2437 805

5\. **Write data to a binary file**

a) Start from the `data/data_000637.txt` file that we have used during the previous lectures, and convert it to a binary file according to the format defined below:

In [ ]:
from IPython.display import Image
Image("images/data_format.png")

*Hints*:
- Read the first 10 lines using Pandas
- Iterate over the DataFrame rows
- For every row, ``pack'' the values (features) into a single 64-bit word, according to the format specified above. Use bit-wise shifts and operators to do so.
- Write each 64-bit word to a binary file. You can use `struct` in this way:
```
binary_file.write( struct.pack('<q', word) )
```
where `word` is the 64-bit word.
- Close the file after completing the loop.

b) Check that the binary file is correctly written by reading it with the code used in the lecture `06_OSEMN.ipynb`, and verify that the content of the `txt` and binary files is consistent.

c) What is the difference of the size on disk between equivalent `txt` and binary files?

In [17]:
# a)
# Read the file, convert to dataframe, loc first 10 lines
data=pd.DataFrame(pd.read_csv('data_000637.txt', sep=',')).loc[0:9]
with open('binary_file.dat','wb') as binf:
    for line in data.values:
        w = (line[5]<<0) # Shift the bits of the last element left by 0 and put in w
        w += (line[4]<<5)
        w += (line[3]<<17)
        w += (line[2]<<49)
        w += (line[1]<<58)
        w += (line[0]<<62)
    binf.write(struct.pack('<q', w))
binf.close()

# b)
# Professor code
with open('data_000637.dat', 'rb') as file:
    file_content = file.read()
    word_counter = 0
    word_size = 8 # size of the word in bytes
    for i in range(0, len(file_content), word_size):
        word_counter += 1
        if word_counter > 10: break
        word = struct.unpack('<q', file_content[i : i + word_size])[0] # get an 8-byte word
        head     = (word >> 62) & 0x3
        fpga     = (word >> 58) & 0xF
        tdc_chan = (word >> 49) & 0x1FF
        orb_cnt  = (word >> 17) & 0xFFFFFFFF
        bx       = (word >> 5 ) & 0xFFF
        tdc_meas = (word >> 0 ) & 0x1F
        #if i == 0: print ('{0}\t{1}\t{2}\t{3}\t{4}\t{5}'.format('HEAD', 'FPGA', 'CHANNEL', 'ORBIT_CNT', 'BX_CNT', 'TDC_MEAS'))
        print('{0}\t{1}\t{2}\t{3}\t{4}\t{5}'.format(head, fpga, tdc_chan, orb_cnt, bx, tdc_meas))
        entry = {'HEAD' : head, 'FPGA' : fpga, 'CHANNEL' : tdc_chan, 'ORBIT_CNT' : orb_cnt, 'BX_CNT' : bx, 'TDC_MEAS' : tdc_meas}
        df = df.append(entry, ignore_index=True)


# c) The binary file size is 10.5 MB while the .txt file is 33.2 MB


1	0	122	3869200167	2374	27
1	0	123	3869200167	2374	28
1	0	62	3869200167	2553	29
1	0	63	3869200167	2558	20
1	0	63	3869200167	2760	26
1	0	62	3869200167	2762	5
1	0	60	3869200167	2772	15
1	0	138	3869200167	2776	1
1	0	61	3869200167	2774	22
1	0	59	3869200167	2788	8


/var/folders/jz/fbg3_6jd23l2_w01fdq312hh0000gn/T/ipykernel_823/4050512003.py:34: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(entry, ignore_index=True)
/var/folders/jz/fbg3_6jd23l2_w01fdq312hh0000gn/T/ipykernel_823/4050512003.py:34: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(entry, ignore_index=True)
/var/folders/jz/fbg3_6jd23l2_w01fdq312hh0000gn/T/ipykernel_823/4050512003.py:34: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(entry, ignore_index=True)
/var/folders/jz/fbg3_6jd23l2_w01fdq312hh0000gn/T/ipykernel_823/4050512003.py:34: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.appen