In [1]:
import numpy as np
import pandas as pd
import csv
import struct
import os
import math

1. Text files

create a list of integrer numbers and then save it to a text file named data_int.txt. Run the cat command to print the content of the file.

In [4]:
list1=[1,2,3,4,5]
with open("data_int.txt",'w',encoding = 'utf-8') as f:
  for i in list1:
    f.write(f'{i}\n')




In [5]:
!cat data_int.txt

1
2
3
4
5


create a matrix of 5x5 floats and then save it to a text file named data_float.txt. Use the cat command to print the content of the file.

In [6]:
matrix=np.arange(25).reshape((5,5))
print(matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


create a matrix of 5x5 floats and then save it to a text file named data_float.txt. Use the cat command to print the content of the file.

In [7]:
list2=[]
matrix2=np.array
for i in range(25):
  list2.append(np.random.uniform(0,24))
#print(list2)
matrix2=np.array([list2]).reshape((5,5))
#print(m)
print(matrix2.shape)
with open("data_float.txt",'w',encoding = 'utf-8') as f:
  for i in matrix2:
    f.write(f'{i},\n')

!cat data_float.txt

(5, 5)
[ 2.63194878  3.22187741  6.44429157 16.34052743  0.3075666 ],
[14.33359305 22.24618459 11.57318891 12.35361894 18.53187323],
[17.75046376 17.62976728  5.78945322  2.3994347  12.52679327],
[ 3.53212911 12.27329807  3.01228431  7.73456931 23.40566281],
[ 3.03611807  0.43508923 14.0971289   4.45023328 17.16471203],


load the txt file of the previous point and convert it to a csv file by hand.


In [8]:
with open('data_float.txt', 'r',encoding = 'utf-8') as f1:
  with open('data_float.csv', 'w',newline='')as f2:
    writer = csv.writer(f2)
    for line in csv.reader(f1, delimiter="'"):
      writer.writerow([f'{line}'])
      #print('l',line)
!cat data_float.csv    

"['[ 2.63194878  3.22187741  6.44429157 16.34052743  0.3075666 ],']"
"['[14.33359305 22.24618459 11.57318891 12.35361894 18.53187323],']"
"['[17.75046376 17.62976728  5.78945322  2.3994347  12.52679327],']"
"['[ 3.53212911 12.27329807  3.01228431  7.73456931 23.40566281],']"
"['[ 3.03611807  0.43508923 14.0971289   4.45023328 17.16471203],']"


2. JSON files

Load the file user_data.json, which can be found at:



In [9]:
!wget https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

--2022-12-01 07:57:35--  https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json
Resolving www.dropbox.com (www.dropbox.com)... 162.125.6.18, 2620:100:601c:18::a27d:612
Connecting to www.dropbox.com (www.dropbox.com)|162.125.6.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/raw/sz5klcdpckc39hd/user_data.json [following]
--2022-12-01 07:57:35--  https://www.dropbox.com/s/raw/sz5klcdpckc39hd/user_data.json
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uce6c5fafe3078277cfadaacc6fe.dl.dropboxusercontent.com/cd/0/inline/BxyXr2rxkLStCVnHEtqpTV9DrYlagJ6_K7S76g2wXg5j9zNyx3s_TQXyv3cpD6ck5Dy9anWYgpXG_9CW3BVKeqGV706g9cowm1SEMBUwO2r6YLLwiqvMi_GWVzjZOTqhhLg69eLIJhmyMnuztHAin0qH9u89HzbUuAuU-kePBMScIg/file# [following]
--2022-12-01 07:57:36--  https://uce6c5fafe3078277cfadaacc6fe.dl.dropboxusercontent.com/cd/0/inline/BxyXr2rxkLStCVnHEtqpTV9DrYlagJ6_K7S76g2wXg5j9zNyx3s_TQXyv3cpD6ck5Dy9anWYgp

In [10]:
import json # import the JSON module
dataset = json.load(open('user_data.json'))
print(dataset)

[{'ID': '1', 'JobTitle': 'Project Manager', 'EmailAddress': 'Remy_Crawford1065@typill.biz', 'FirstNameLastName': 'Remy Crawford', 'CreditCard': '6205-7258-7671-0612', 'CreditCardType': 'Capital One'}, {'ID': '2', 'JobTitle': 'Investment  Advisor', 'EmailAddress': 'Clint_Thorpe5003@bulaffy.com', 'FirstNameLastName': 'Clint Thorpe', 'CreditCard': '7083-8766-0251-2345', 'CreditCardType': 'American Express'}, {'ID': '3', 'JobTitle': 'Cook', 'EmailAddress': 'Russel_Hooper9403@bulaffy.com', 'FirstNameLastName': 'Russel Hooper', 'CreditCard': '6378-4461-8535-5847', 'CreditCardType': 'Discover'}, {'ID': '4', 'JobTitle': 'Business Broker', 'EmailAddress': 'Benjamin_Rowan6280@gembat.biz', 'FirstNameLastName': 'Benjamin Rowan', 'CreditCard': '5781-7635-1428-7414', 'CreditCardType': 'Discover'}, {'ID': '5', 'JobTitle': 'Loan Officer', 'EmailAddress': 'Matt_Lloyd3241@guentu.biz', 'FirstNameLastName': 'Matt Lloyd', 'CreditCard': '5771-8416-2736-1700', 'CreditCardType': 'Citibank'}, {'ID': '6', 'JobT

show a sample of that

In [11]:
dataset[1]

{'ID': '2',
 'JobTitle': 'Investment  Advisor',
 'EmailAddress': 'Clint_Thorpe5003@bulaffy.com',
 'FirstNameLastName': 'Clint Thorpe',
 'CreditCard': '7083-8766-0251-2345',
 'CreditCardType': 'American Express'}

and filter the data by the "CreditCardType" when it equals to "American Express". Than save the data to a new CSV file.

**bold text**

In [12]:
#make list and append all the CreditCardType" when it equals to "American Express"
list3=[]
for i in range(200):
  if dataset[i]['CreditCardType']=="American Express":
    list3.append(dataset[i])
print(list3)


[{'ID': '2', 'JobTitle': 'Investment  Advisor', 'EmailAddress': 'Clint_Thorpe5003@bulaffy.com', 'FirstNameLastName': 'Clint Thorpe', 'CreditCard': '7083-8766-0251-2345', 'CreditCardType': 'American Express'}, {'ID': '12', 'JobTitle': 'Retail Trainee', 'EmailAddress': 'Phillip_Carpenter9505@famism.biz', 'FirstNameLastName': 'Phillip Carpenter', 'CreditCard': '3657-0088-0820-5247', 'CreditCardType': 'American Express'}, {'ID': '28', 'JobTitle': 'Project Manager', 'EmailAddress': 'Russel_Graves1378@extex.org', 'FirstNameLastName': 'Russel Graves', 'CreditCard': '6718-4818-8011-6024', 'CreditCardType': 'American Express'}, {'ID': '39', 'JobTitle': 'Stockbroker', 'EmailAddress': 'Leanne_Newton1268@typill.biz', 'FirstNameLastName': 'Leanne Newton', 'CreditCard': '5438-0816-4166-4847', 'CreditCardType': 'American Express'}, {'ID': '57', 'JobTitle': 'Budget Analyst', 'EmailAddress': 'Tony_Giles1960@iatim.tech', 'FirstNameLastName': 'Tony Giles', 'CreditCard': '8130-3425-7573-7745', 'CreditCard

In [13]:

print(list3[4])

{'ID': '57', 'JobTitle': 'Budget Analyst', 'EmailAddress': 'Tony_Giles1960@iatim.tech', 'FirstNameLastName': 'Tony Giles', 'CreditCard': '8130-3425-7573-7745', 'CreditCardType': 'American Express'}


In [14]:
out_file = open("myfile.json", "w")
  
json.dump(list3, out_file, indent = 6)
  
out_file.close()

In [16]:
!cat myfile.json

[
      {
            "ID": "2",
            "JobTitle": "Investment  Advisor",
            "EmailAddress": "Clint_Thorpe5003@bulaffy.com",
            "FirstNameLastName": "Clint Thorpe",
            "CreditCard": "7083-8766-0251-2345",
            "CreditCardType": "American Express"
      },
      {
            "ID": "12",
            "JobTitle": "Retail Trainee",
            "EmailAddress": "Phillip_Carpenter9505@famism.biz",
            "FirstNameLastName": "Phillip Carpenter",
            "CreditCard": "3657-0088-0820-5247",
            "CreditCardType": "American Express"
      },
      {
            "ID": "28",
            "JobTitle": "Project Manager",
            "EmailAddress": "Russel_Graves1378@extex.org",
            "FirstNameLastName": "Russel Graves",
            "CreditCard": "6718-4818-8011-6024",
            "CreditCardType": "American Express"
      },
      {
            "ID": "39",
            "JobTitle": "Stockbroker",
            "EmailAddress": "Leanne_Newton1

Than save the data to a new CSV file.

convert the previous json file which CreditCardType" when it equals to "American Express" to the csv file 

in jupyter it works and newcsv has the data
but in colab sometimes it is empty aaccording to loading the data.

In [27]:
import json 

with open('myfile.json') as json_file:
    data = json.load(json_file)
print(type(data))
newData = data
 
# now we will open a file for writing
data_file = open('newcsv.csv', 'w')
 
csv_writer = csv.writer(data_file)
 
# Counter variable used for writing
# headers to the CSV file
count = 0
 
for h in newData:
    if count == 0:
 
        # Writing headers of CSV file
        header = h.keys()
        csv_writer.writerow(header)
        count += 1
    # Writing data of CSV file
    csv_writer.writerow(h.values())

<class 'list'>


In [28]:
#the final result for ex 3 is:
!cat newcsv.csv

3. CSV files with Pandas

Load the file from this url:

In [20]:
!wget https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

--2022-12-01 08:01:07--  https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv
Resolving www.dropbox.com (www.dropbox.com)... 162.125.6.18, 2620:100:6019:18::a27d:412
Connecting to www.dropbox.com (www.dropbox.com)|162.125.6.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/raw/kgshemfgk22iy79/mushrooms_categorized.csv [following]
--2022-12-01 08:01:07--  https://www.dropbox.com/s/raw/kgshemfgk22iy79/mushrooms_categorized.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://ucc3b655fbfe7f3ddf729e36e8e1.dl.dropboxusercontent.com/cd/0/inline/BxyUzAyOZWLST9NyfHfdvzBgW5Oa6blosxwKV-DZgy6UnHH_3SIdwswklRcZSKjjFWOa_xdratrIPBgXG3qIxLB-x4udYN8A5QkFYPFFGsTRG9XjfIv2S1CEuQ_XDdIJZ5LLLsvOs2DE8XOab8fNc1gMSA430VQi4PWSUWiJmmJdPg/file# [following]
--2022-12-01 08:01:08--  https://ucc3b655fbfe7f3ddf729e36e8e1.dl.dropboxusercontent.com/cd/0/inline/BxyUzAyOZWLST9NyfHfdvzBgW5Oa6blosxwKV-DZg

In [21]:
import pandas as pd

dataf = pd.read_csv('mushrooms_categorized.csv')
print(dataf) 


      class  cap-shape  cap-surface  cap-color  bruises  odor  \
0         1          5            2          4        1     6   
1         0          5            2          9        1     0   
2         0          0            2          8        1     3   
3         1          5            3          8        1     6   
4         0          5            2          3        0     5   
...     ...        ...          ...        ...      ...   ...   
8119      0          3            2          4        0     5   
8120      0          5            2          4        0     5   
8121      0          2            2          4        0     5   
8122      1          3            3          4        0     8   
8123      0          5            2          4        0     5   

      gill-attachment  gill-spacing  gill-size  gill-color  ...  \
0                   1             0          1           4  ...   
1                   1             0          0           4  ...   
2                 

In [22]:
print(dataf["class"])
print(dataf['class'].shape)
print(dataf['class'].unique())

0       1
1       0
2       0
3       1
4       0
       ..
8119    0
8120    0
8121    0
8122    1
8123    0
Name: class, Length: 8124, dtype: int64
(8124,)
[1 0]


so we have just 2 classes in class column , for each one we should run and execute groupby method.

**calculate, using groupby(), the average value of each feature, separately for each class**


In [23]:
g=dataf.groupby('class').mean()
print(g)
print(g.shape)

       cap-shape  cap-surface  cap-color   bruises      odor  gill-attachment  \
class                                                                           
0       3.266160     1.615970   4.581749  0.653992  4.334601         0.954373   
1       3.436159     2.055158   4.421859  0.159346  3.940756         0.995403   

       gill-spacing  gill-size  gill-color  stalk-shape  ...  \
class                                                    ...   
0          0.285171   0.068441    6.622624     0.615970  ...   
1          0.028601   0.567926    2.863636     0.514811  ...   

       stalk-surface-below-ring  stalk-color-above-ring  \
class                                                     
0                      1.798479                6.098859   
1                      1.394280                5.512768   

       stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
class                                                                          
0                    

save the file in a JSON format.


In [24]:
g.to_csv('final.csv')

Function to convert a CSV to JSON
Takes the file paths as arguments

In [25]:
import csv
import json
 
 
# 
def csvTojson(csvFilePath, jsonFilePath):
     
    data = {}
     
    with open(csvFilePath, encoding='utf-8') as csvf:
        csvReader = csv.DictReader(csvf)
        for rows in csvReader:
            key = rows['class']
            data[key] = rows
 
   
    with open(jsonFilePath, 'w', encoding='utf-8') as j:
        j.write(json.dumps(data, indent=4))
         
csvFilePath = r'final.csv'
jsonFilePath = r'afterGroupbywithClass.json'
 
csvTojson(csvFilePath, jsonFilePath)

In [26]:
#the final file for ex3 after groupby and savig in json format is:
!cat afterGroupbywithClass.json

{
    "0": {
        "class": "0",
        "cap-shape": "3.2661596958174903",
        "cap-surface": "1.6159695817490494",
        "cap-color": "4.581749049429658",
        "bruises": "0.6539923954372624",
        "odor": "4.334600760456274",
        "gill-attachment": "0.9543726235741445",
        "gill-spacing": "0.28517110266159695",
        "gill-size": "0.06844106463878327",
        "gill-color": "6.6226235741444865",
        "stalk-shape": "0.6159695817490495",
        "stalk-root": "1.4980988593155893",
        "stalk-surface-above-ring": "1.7756653992395437",
        "stalk-surface-below-ring": "1.7984790874524714",
        "stalk-color-above-ring": "6.098859315589354",
        "stalk-color-below-ring": "6.064638783269962",
        "veil-type": "0.0",
        "veil-color": "1.9315589353612168",
        "ring-number": "1.1254752851711027",
        "ring-type": "3.0076045627376424",
        "spore-print-color": "3.2015209125475286",
        "population": "3.283269961977186",
    

4. Reading the credit card numbers
Get the binary file named credit_card.dat from this address:

https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat
and convert the data into the real credit card number, knowing that:

In [1]:
!wget https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

--2022-12-01 10:10:18--  https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat
Resolving www.dropbox.com (www.dropbox.com)... 162.125.3.18, 2620:100:601b:18::a27d:812
Connecting to www.dropbox.com (www.dropbox.com)|162.125.3.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/raw/8m0syw2tkul3dap/credit_card.dat [following]
--2022-12-01 10:10:19--  https://www.dropbox.com/s/raw/8m0syw2tkul3dap/credit_card.dat
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc233f1057d2810212efc6c81608.dl.dropboxusercontent.com/cd/0/inline/BxyxxWqG6MEiKMyr3KOzLyzLv7RlmMZIq_fiA2Kp0jq0Upa7EoE6vMyyLVz_vST6Yo3mhvFb__mZZA4bQBuTqqDrYjX5yHVQl8uK7lLAK4eyfcQCCoHcgl0UUQqbH2Dz1LB6byvzP_5xLuuB6DhPP7jS40CUqS2ThfbFbDTsLlfDpQ/file# [following]
--2022-12-01 10:10:19--  https://uc233f1057d2810212efc6c81608.dl.dropboxusercontent.com/cd/0/inline/BxyxxWqG6MEiKMyr3KOzLyzLv7RlmMZIq_fiA2Kp0jq0Upa7EoE6vMyyLVz_vST6Yo3mhvF

In [4]:
with open('credit_card.dat' , 'r') as f:
  number = 1
  for j in f:
    if (number != 51):
      print(number, ")" , ''.join([chr(int(j[i:i+6],2)) for i in range(0, len(j), 6)]))
      number =number+1

1 ) 7648 5673 3775 2271

2 ) 3257 8247 3354 2266

3 ) 2722 0001 4011 6652

4 ) 0661 3063 3742 3150

5 ) 0432 1608 1462 4742

6 ) 5827 2027 8785 7303

7 ) 5774 8528 2087 1117

8 ) 8140 1210 6352 2845

9 ) 5764 1133 7301 7100

10 ) 6456 1737 4126 6726

11 ) 1228 8631 7382 0000

12 ) 7051 0160 5374 3166

13 ) 0618 3587 1630 6376

14 ) 1545 5454 7444 5636

15 ) 6735 3116 3202 6834

16 ) 7287 5011 1547 8413

17 ) 7033 2607 3328 4200

18 ) 2568 5244 1874 5024

19 ) 1684 2253 7570 7118

20 ) 0672 2576 0575 6631

21 ) 6332 8353 8787 1340

22 ) 1813 3361 1175 4211

23 ) 2477 6450 8840 2368

24 ) 5512 3505 2563 1326

25 ) 3083 7882 0621 0025

26 ) 4521 5148 8045 0334

27 ) 7563 3654 8713 5787

28 ) 8324 2664 0476 5561

29 ) 0565 2504 7168 3510

30 ) 5107 5507 1767 0738

31 ) 2462 1821 2448 1443

32 ) 2788 0638 6861 6554

33 ) 5851 5873 5474 0547

34 ) 0670 1004 4013 2655

35 ) 5874 5506 3048 0806

36 ) 2805 5401 8462 1260

37 ) 5083 8406 6310 1862

38 ) 1076 1445 3013 2266

39 ) 8440 4804 4844 5

ex5
a) Start from the data/data_000637.txt file that we have used during the previous lectures, and convert it to a binary file according to the format defined below:

In [2]:
!wget https://www.dropbox.com/s/ga9wi6b40cakgae/data_000637.txt -P data/   

--2022-12-01 16:13:29--  https://www.dropbox.com/s/ga9wi6b40cakgae/data_000637.txt
Resolving www.dropbox.com (www.dropbox.com)... 162.125.1.18, 2620:100:6017:18::a27d:212
Connecting to www.dropbox.com (www.dropbox.com)|162.125.1.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/raw/ga9wi6b40cakgae/data_000637.txt [following]
--2022-12-01 16:13:29--  https://www.dropbox.com/s/raw/ga9wi6b40cakgae/data_000637.txt
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uce30483878391d11f33feeb963e.dl.dropboxusercontent.com/cd/0/inline/Bxzl5PrfoDU_E3QYlVQXclHY1tUgMBb46K1YxUEqUxz9bj-ImHWenFE23KavddmUqjbJf0FHbqoFO4rUrniVT5lKrdt5b2JXjKqodoZsRXW8Yqmn_MJ3683F_hbfefniP12DMzEXMmRI9anbPhS581iT_rt91uMSZMbz-UZaNkXegg/file# [following]
--2022-12-01 16:13:30--  https://uce30483878391d11f33feeb963e.dl.dropboxusercontent.com/cd/0/inline/Bxzl5PrfoDU_E3QYlVQXclHY1tUgMBb46K1YxUEqUxz9bj-ImHWenFE23KavddmUqjbJf0F

In [3]:
import numpy as np
import pandas as pd
import csv
import struct
import os
import math

In [4]:
data = pd.read_csv("data/data_000637.txt" , nrows = 10)
with open("data_000637.dat", 'wb') as f:
    for i in data.values: 
        Word =  (i[5] << 0 ) 
        Word += (i[4] << 5 ) 
        Word += (i[3] << 17) 
        Word += (i[2] << 49) 
        Word += (i[1] << 58)
        Word += (i[0] << 62)
        f.write(struct.pack('<q', Word))
df1 = pd.DataFrame({}, columns = ['HEAD', 'FPGA', 'CHANNEL', 'ORBIT_CNT', 'BX_CNT', 'TDC_MEAS'])
#compare with original data
print(df1)
#print("dkjfkdjf")
print(data)

Empty DataFrame
Columns: [HEAD, FPGA, CHANNEL, ORBIT_CNT, BX_CNT, TDC_MEAS]
Index: []
dkjfkdjf
   HEAD  FPGA  TDC_CHANNEL   ORBIT_CNT  BX_COUNTER  TDC_MEAS
0     1     0          123  3869200167        2374        26
1     1     0          124  3869200167        2374        27
2     1     0           63  3869200167        2553        28
3     1     0           64  3869200167        2558        19
4     1     0           64  3869200167        2760        25
5     1     0           63  3869200167        2762         4
6     1     0           61  3869200167        2772        14
7     1     0          139  3869200167        2776         0
8     1     0           62  3869200167        2774        21
9     1     0           60  3869200167        2788         7


In [7]:

with open( "data_000637.dat" , 'rb') as file:
    content = file.read()
    Counter = 0
    for i in range(0, len(content), 8):
        s = 8
        Counter += 1
        if Counter > 10: 
          break
        w = struct.unpack('<q', content[i : i + s])[0] 
        head     = (w >> 62) & 0x3
        fpga     = (w >> 58) & 0xF
        tdc_chan = (w >> 49) & 0x1FF
        orb_cnt  = (w >> 17) & 0xFFFFFFFF
        bx       = (w >> 5 ) & 0xFFF
        tdc_meas = (w >> 0 ) & 0x1F
        Columns2 = {'HEAD' : head, 'FPGA' : fpga, 'CHANNEL' : tdc_chan, 'ORBIT_CNT' : orb_cnt, 'BX_CNT' : bx, 'TDC_MEAS' : tdc_meas}
        df2 = df1.append(Columns2 , ignore_index=True)



In [8]:
print(df2)
Dsize = os.path.getsize(r"data_000637.dat")
print(" dat file size:" , Dsize , "bytes")
Tsize = os.path.getsize(r"data/data_000637.txt")
print(" text file size:" , Tsize , "bytes")


  HEAD FPGA CHANNEL   ORBIT_CNT BX_CNT TDC_MEAS
0    1    0      60  3869200167   2788        7
 dat file size: 80 bytes
 text file size: 33179236 bytes


the difference

In [ ]:
print("" , abs(Dsize - Tsize))