In [1]:
import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt

1\. **Text files**

Perform the following operations on plain `txt` files:

+ create a list of integrer numbers and then save it to a text file named `data_int.txt`. Run the `cat` command to print the content of the file.
+ create a matrix of 5x5 floats and then save it to a text file named `data_float.txt`. Use the `cat` command to print the content of the file.
+ load the `txt` file of the previous point and convert it to a `csv` file by hand.

In [2]:
# list of integers 
l_int = [x for x in range(100)]
# l=["a","b","c"]
file = open("data/data_int.txt","w")

for i in l_int:
    file.write(str(i)+"\n")
file.close()


!type data\data_int.txt

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [3]:
#creating a matrix of 5x5 matrix
 
val = np.arange(25,  dtype=float).reshape(5,5)
# np.array(val,dtype=float)
print(val)

file_float= open("data/data_float.txt","w")

# for elment in file_float:
#      np.savetxt(file_float, elment, fmt='%.2f')
# file_float.close()

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]


In [4]:
np.savetxt("data/data_float.txt",val, fmt="%0.3f")
!type data\data_float.txt

0.000 1.000 2.000 3.000 4.000
5.000 6.000 7.000 8.000 9.000
10.000 11.000 12.000 13.000 14.000
15.000 16.000 17.000 18.000 19.000
20.000 21.000 22.000 23.000 24.000


In [10]:
# Concerting text to CSV

# with open("data/data_float.txt", 'r') as infile, open("data/data_float.csv", 'w') as outfile:
#         stripped = (line.strip() for line in infile)
#         lines = (line.split(",") for line in stripped if line)
#         writer = csv.writer(outfile)
#         writer.writerows(lines)
# load_txt = pd.read_fwf("data/data_float.txt",delimiter=',')



headl =['A']
read_file = pd.read_fwf (r'data/data_int.txt', delim_whitespace=True, names=['col1']) # add header 


In [11]:
# importing and converting float text file into csv file

# read_float = pd.read_table('data/data_float.txt',sep=' ',names=['A','B','C','D','E'])
# read_float.to_csv('data/data_float.csv',index=None)

!type data\data_float.txt

0.000 1.000 2.000 3.000 4.000
5.000 6.000 7.000 8.000 9.000
10.000 11.000 12.000 13.000 14.000
15.000 16.000 17.000 18.000 19.000
20.000 21.000 22.000 23.000 24.000


In [12]:
# Accessing data from pandas dataframe

df =  pd.read_csv('data/data_float.csv')
df

FileNotFoundError: [Errno 2] No such file or directory: 'data/data_float.csv'

2\. **JSON files**

Load the file *user_data.json*, which can be found at:

- https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

and filter the data by the "CreditCardType" when it equals to "American Express". Than save the data to a new CSV file.

In [13]:
# loading the json file
df =  pd.read_json('data/user_data.json')

credit_A = df[df['CreditCardType']=='American Express']
print(credit_A)
# total_number = credit.shape[0]

credit.to_csv('data/American_Express.csv',index=None)

ValueError: Expected object or value

3\. **CSV files with Pandas**

Load the file from this url:

- https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

with Pandas. 

+ explore and print the DataFrame
+ calculate, using `groupby()`, the average value of each feature, separately for each class
+ save the file in a JSON format.

In [ ]:
# loading directly from URL
# import dropbox as DBX
import io
import dropbox

import urllib.request
url = 'https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv?dl=1'
u = urllib.request.urlopen(url)
data = u.read()
u.close()

with open('data/mushrooms_categorized.csv', "wb") as f :
    f.write(data)



# url = 'https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv?dl=1'
# with urllib.request.urlopen(url) as data_file:
# #     print (data_file.read(300))
#     for line in data_file:
# #         print(line)
        
        
# grouping the data and taking the average
cat_avg =  pd.read_csv('data/mushrooms_categorized.csv')
cat_j = cat_avg.groupby('class').mean()

# print(cat_json)

In [ ]:
# writing to json file
import json
cat_j.to_json('data/class_cat.json')

# !type data\class_cat.json

js=pd.read_json('data/class_cat.json')
js

4\. **Reading the credit card numbers**

Get the binary file named *credit_card.dat* from this address:

- https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

and convert the data into the real credit card number, knowing that:
- each line corresponds to a credit card number, which consists of 16 characters (which are numbers in the 0-9 range) divided in 4 blocks, with a whitespace between each block
- each character is written using a 6 bit binary representation (including the whitespace)
- the final 4 bits of each line are a padding used to determine the end of the line, and can be ignored

*Hint*: convert the binary numbers to the decimal representation first, and then use the `chr()` function to convert the latter to a char

In [ ]:
# !type data\credit_card.dat
ind=1
char_l = 6
with open('data\credit_card.dat') as file:
    for card in file:
        code=[]
        for j in range(0,len(card),char_l):
            code.append(chr(int(card[j:j+char_l],2)))
        if ind<51:
            print(ind,"".join(code))
        ind+=1

In [ ]:
url='https://www.dropbox.com/s/aamg1apjhclecka/regression_generated.csv?dl=1'
# file = urllib.request.urlopen(url)
pl = pd.read_csv(url) 
# pl

In [ ]:
# ploting the features against labels

%matplotlib inline

pl.plot.scatter(x='features_1',y='features_2',c='label',colormap='viridis')
pl.plot.scatter(x='features_2',y='features_3',c='label',colormap='gist_rainbow')
pl.plot.scatter(x='features_1',y='features_3',c='label',colormap

5\. **Write data to a binary file**

a) Start from the `data/data_000637.txt` file that we have used during the previous lectures, and convert it to a binary file according to the format defined below:

In [ ]:
from IPython.display import Image
Image("images/data_format.png")

*Hints*:
- Read the first 10 lines using Pandas
- Iterate over the DataFrame rows
- For every row, ``pack'' the values (features) into a single 64-bit word, according to the format specified above. Use bit-wise shifts and operators to do so.
- Write each 64-bit word to a binary file. You can use `struct` in this way:
```
binary_file.write( struct.pack('<q', word) )
```
where `word` is the 64-bit word.
- Close the file after completing the loop.

b) Check that the binary file is correctly written by reading it with the code used in the lecture `06_OSEMN.ipynb`, and verify that the content of the `txt` and binary files is consistent.

c) What is the difference of the size on disk between equivalent `txt` and binary files?