In [1]:
import pandas as pd
import numpy as np
import csv

1\. **Text files**

Perform the following operations on plain `txt` files:

+ create a list of integrer numbers and then save it to a text file named `data_int.txt`. Run the `cat` command to print the content of the file.
+ create a matrix of 5x5 floats and then save it to a text file named `data_float.txt`. Use the `cat` command to print the content of the file.
+ load the `txt` file of the previous point and convert it to a `csv` file by hand.

In [4]:
#1
from random import random, seed
L = [ int(random()*10) for i in range(10) ]
print("list l:\n ", L, "\n")
with open("./data_int.txt", mode = 'w') as f:
    #f.write(str(L))
    for item in L:
        f.write("%s " % item)
print("loded txt list file:")        
!cat ./data_int.txt 
print('\n')
#2
b= np.random.random((5,5))
mat = np.matrix(b)
print("random 5*5 matrix:\n", mat, "\n")    
with open('data_float.txt','wb') as f:
    #f.write(str(mat))
    for line in mat:
        np.savetxt(f, line, fmt='%.2f')

print("data_float:")
!cat ./data_float.txt 
print('\n')
#3
f = open('./data_float.txt', 'r')
textContent = f.read()
print("loded txt file: \n", textContent)
f.close()
import zlib
lines = textContent.splitlines()
rawContent = [line.split(' ') for line in lines]
rows = zip(*[rawContent]*1)
with open('data_float.csv', 'w') as out_file:
    writer = csv.writer(out_file)
    for row in rows:
        writer.writerows(row)
print("csv file: ")
!cat ./data_float.csv 
print('\n')

list l:
  [7, 6, 7, 9, 4, 4, 4, 2, 5, 5] 

loded txt list file:
7 6 7 9 4 4 4 2 5 5 


random 5*5 matrix:
 [[0.03128159 0.97768868 0.83113427 0.05678729 0.06104486]
 [0.99099517 0.46205701 0.49435832 0.22129369 0.33182976]
 [0.90700876 0.9881851  0.13900859 0.85053668 0.71044027]
 [0.57333677 0.02926984 0.16982994 0.35206327 0.36799119]
 [0.23349939 0.67170138 0.32208409 0.17499523 0.78240004]] 

data_float:
0.03 0.98 0.83 0.06 0.06


0.99 0.46 0.49 0.22 0.33
0.91 0.99 0.14 0.85 0.71
0.57 0.03 0.17 0.35 0.37
0.23 0.67 0.32 0.17 0.78
loded txt file: 
 0.03 0.98 0.83 0.06 0.06
0.99 0.46 0.49 0.22 0.33
0.91 0.99 0.14 0.85 0.71
0.57 0.03 0.17 0.35 0.37
0.23 0.67 0.32 0.17 0.78

csv file: 
0.03,0.98,0.83,0.06,0.06

0.99,0.46,0.49,0.22,0.33

0.91,0.99,0.14,0.85,0.71

0.57,0.03,0.17,0.35,0.37

0.23,0.67,0.32,0.17,0.78





2\. **JSON files**

Load the file *user_data.json*, which can be found at:

- https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

and filter the data by the "CreditCardType" when it equals to "American Express". Than save the data to a new CSV file.

In [9]:
import numpy as np
import pandas as pd
import csv
import json    
d = json.load(open('user_data.json'))

header = ["ID","JobTitle","EmailAddress","FirstNameLastName","CreditCard", "CreditCardType"]
l=[]
for a in d:
    if a['CreditCardType'] == 'American Express':
        array= [a["ID"], a["JobTitle"], a["EmailAddress"],a["FirstNameLastName"],a["CreditCard"],a["CreditCardType"]]
        l.append(array)


with open('jsonfiltered.csv','w') as csv_file:
    writer = csv.writer(csv_file)
    writer.writerow(header)
    writer.writerow(l) 

print("csv file: ")
!cat jsonfiltered.csv 

FileNotFoundError: [Errno 2] No such file or directory: 'user_data.json'

3\. **CSV files with Pandas**

Load the file from this url:

- https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

with Pandas. 

+ explore and print the DataFrame
+ calculate, using `groupby()`, the average value of each feature, separately for each class
+ save the file in a JSON format.

In [ ]:
import numpy as np
import pandas as pd
import csv

file_1 = "mushrooms_categorized.csv"
data_1 = pd.read_csv(file_1)


gb = data_1.groupby(['class']).mean()

data_frame = pd.DataFrame(gb)

data_frame.to_json(r'./export_mean_json.json', orient = 'index')

4\. **Reading the credit card numbers**

Get the binary file named *credit_card.dat* from this address:

- https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

and convert the data into the real credit card number, knowing that:
- each line corresponds to a credit card number, which consists of 16 characters (which are numbers in the 0-9 range) divided in 4 blocks, with a whitespace between each block
- each character is written using a 6 bit binary representation (including the whitespace)
- the final 4 bits of each line are a padding used to determine the end of the line, and can be ignored

*Hint*: convert the binary numbers to the decimal representation first, and then use the `chr()` function to convert the latter to a char

In [10]:
import pandas as pd
import numpy as np
import csv
import math as m

with open('credit_card.dat', 'rb') as file:
    file_content = file.readlines()

    allcarts =[]
    word_counter = 0
    word_size = 8 
    total_digitnumber = 16+3 
    digit_length = 6         

    for row in file_content:

        if(round(len(row)/digit_length) >= total_digitnumber):

            utf_string = row.decode("utf-8")  

            utf_string = utf_string[:-4]     


            start_index = 0
            card_number=[]

            for i in range(total_digitnumber):
                end_index = start_index + digit_length
                digits_4 = utf_string[start_index:end_index]
                card_number.append(digits_4)
                start_index += digit_length    

            credit_card = ""
            for i in range(total_digitnumber):
                credit_card += chr(int(card_number[i],2))

            allcarts.append(credit_card)

    print("Number of all the Credit Card is :\n") 
    for i in allcarts:
        print(i, "\n")

FileNotFoundError: [Errno 2] No such file or directory: 'credit_card.dat'

5\. **Write data to a binary file**

a) Start from the `data/data_000637.txt` file that we have used during the previous lectures, and convert it to a binary file according to the format defined below:

In [ ]:
from IPython.display import Image
Image("images/data_format.png")

*Hints*:
- Read the first 10 lines using Pandas
- Iterate over the DataFrame rows
- For every row, ``pack'' the values (features) into a single 64-bit word, according to the format specified above. Use bit-wise shifts and operators to do so.
- Write each 64-bit word to a binary file. You can use `struct` in this way:
```
binary_file.write( struct.pack('<q', word) )
```
where `word` is the 64-bit word.
- Close the file after completing the loop.

b) Check that the binary file is correctly written by reading it with the code used in the lecture `06_OSEMN.ipynb`, and verify that the content of the `txt` and binary files is consistent.

c) What is the difference of the size on disk between equivalent `txt` and binary files?