1\. **PCA on 3D dataset**

* Generate a dataset simulating 3 features, each with N entries (N being ${\cal O}(1000)$). Each feature is made by random numbers generated according the normal distribution $N(\mu,\sigma)$ with mean $\mu_i$ and standard deviation $\sigma_i$, with $i=1, 2, 3$. Generate the 3 variables $x_{i}$ such that:
    * $x_1$ is distributed as $N(0,1)$
    * $x_2$ is distributed as $x_1+N(0,3)$
    * $x_3$ is given by $2x_1+x_2$
* Find the eigenvectors and eigenvalues using the eigendecomposition of the covariance matrix
* Find the eigenvectors and eigenvalues using the SVD. Check that the two procedures yield to same result
* What percent of the total dataset's variability is explained by the principal components? Given how the dataset was constructed, do these make sense? Reduce the dimensionality of the system so that at least 99% of the total variability is retained
* Redefine the data according to the new basis from the PCA
* Plot the data, in both the original and the new basis. The figure should have 2 rows (the original and the new basis) and 3 columns (the $[x_0, x_1]$, $[x_0, x_2]$ and $[x_1, x_2]$ projections) of scatter plots.

In [5]:
import numpy as np
from scipy import linalg as la
from matplotlib import pyplot as plt

x1 = np.random.normal(loc = 0, scale = 1, size = 1000)
x2 = x1 + np.random.normal(loc = 0, scale = 3, size = 1000)
x3 = 2*x1 + x2

#Covariance matrix
data = np.array([x1, x2, x3])
cov_matrix = np.cov(data, bias=True)

#eigenvalues 
l, V = la.eig(cov_matrix)
print("l:\n", l, '\n')
print("real(l):\n", np.real_if_close(l), '\n')
# V is the matrix of the eigenvectors
print("V:\n", V, '\n')

#SVD
U, s, Vt = la.svd(cov_matrix)
print("shapes: U =", U.shape, "S:", s.shape, "V^T:", Vt.shape, '\n')
print("Spectrum:\n", s, '\n')
print("U:\n", U, '\n')
print("V^T:\n", Vt, '\n')

l:
 [2.62203525e+01+0.j 5.68614318e-16+0.j 2.10105509e+00+0.j] 

real(l):
 [2.62203525e+01 5.68614318e-16 2.10105509e+00] 

V:
 [[-0.10877776 -0.81649658  0.56701035]
 [-0.58566525 -0.40824829 -0.70023535]
 [-0.80322078  0.40824829  0.43378534]] 

shapes: U = (3, 3) S: (3,) V^T: (3, 3) 

Spectrum:
 [2.62203525e+01 2.10105509e+00 9.50407156e-16] 

U:
 [[-0.10877776  0.56701035 -0.81649658]
 [-0.58566525 -0.70023535 -0.40824829]
 [-0.80322078  0.43378534  0.40824829]] 

V^T:
 [[-0.10877776 -0.58566525 -0.80322078]
 [ 0.56701035 -0.70023535  0.43378534]
 [-0.81649658 -0.40824829  0.40824829]] 



2\. **PCA on a nD dataset**

* Start from the dataset you have genereted in the previous exercise and add uncorrelated random noise. Such noise should be represented by other 10 uncorrelated variables normally distributed, with a standard deviation much smaller (e.g. a factor 20) than those used to generate the $x_1$ and $x_2$. Repeat the PCA procedure and compare the results with what you have obtained before.

3\. **Optional**: **PCA on the MAGIC dataset**

Perform a PCA on the magic04.data dataset.

In [ ]:
# get the dataset and its description on the proper data directory
#!wget https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.data -P data/
#!wget https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.names -P data/ 