ex1

In [3]:
import numpy as np
m = np.arange(12).reshape((3,4))
print(m.mean())
cm = np.mean(m,axis=0)
rm = np.mean(m,axis=1)
print(cm)
print(rm)

5.5
[4. 5. 6. 7.]
[1.5 5.5 9.5]


2\. **Outer product**

Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [4]:
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])

#1 Using the function outer in numpy
result = np.outer(u,v)
print(result,"\n")
#2 Using a nested for loop
mylist = []
for i in u:
    row = []
    for j in v:
        row.append(i * j)
    mylist.append(row)
print(mylist)

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]] 

[[2, 4, 6, 8], [6, 12, 18, 24], [10, 20, 30, 40], [14, 28, 42, 56]]


3\. **Matrix masking**

Create a 10 by 6 matrix of float random numbers, distributed between 0 and 3 according to a flat distribution.

After creating the matrix, set all entries $< 0.3$ to zero using a mask.

In [5]:
import numpy.random as npr
random = 3 * npr.random_sample((10, 6)) - 0
print("10 by 6 matrix of float random numbers: ")
print(random)
h = np.array(random)
filter = (random < 0.3)
random[random < 0.3] = 0
print(random)

10 by 6 matrix of float random numbers: 
[[0.02157594 1.01658792 0.65711162 0.19754389 2.52576026 1.80418704]
 [2.23003643 1.69746681 1.02029403 0.02131649 2.64062397 1.91909231]
 [1.16837635 2.46602234 2.50964595 2.2369713  0.80232343 2.5395869 ]
 [1.67026099 2.36991749 1.92331444 1.33291562 0.89610552 1.10696222]
 [0.88124888 1.73228707 0.5301483  1.13643763 2.06685456 2.15538946]
 [2.0343008  0.77173328 2.80034979 2.25302455 2.90315071 0.98157157]
 [1.13797059 0.5715967  0.21696937 0.98900612 2.0455349  1.60868906]
 [2.67018639 0.71416591 0.15958212 2.48324497 0.76729495 1.30720964]
 [1.57019859 2.99548698 1.17214245 0.68757663 0.16864544 0.26436259]
 [0.38461387 2.9446851  2.9590577  2.56758788 2.66561269 2.29280185]]
[[0.         1.01658792 0.65711162 0.         2.52576026 1.80418704]
 [2.23003643 1.69746681 1.02029403 0.         2.64062397 1.91909231]
 [1.16837635 2.46602234 2.50964595 2.2369713  0.80232343 2.5395869 ]
 [1.67026099 2.36991749 1.92331444 1.33291562 0.89610552 1.10

4\. **Trigonometric functions**

Use `np.linspace` to create an array of 100 numbers between $0$ and $2\pi$ (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the `sin` and `cos` functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

In [8]:
import math
import matplotlib.pyplot as plt

array1 = np.linspace(0,2*math.pi,100)
print(array1)

new_array = array1[::10]
print("\10th\n",new_array)

reverse_new_array =new_array[::-1] 
print("reverse\n",reverse_new_array)

mask= np.abs(np.sin(array1)-np.cos(array1)) < 0.1
print("final","\n",array1[mask])



[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

5\. **Matrices**

Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [19]:
import numpy as np
arr=[]
rows, cols=11,11
for i in range(1,rows):
    col = []
    for j in range(1,cols):
        col.append(i*j)
    arr.append(col)
m = np.array(arr)
print(m)
#Find the trace of the matrix
print("\nTrace of matrix:",np.trace(m))
x = np.fliplr(m).diagonal()
print("Anti-diagonal matrix:",x)
#Extract the diagonal offset by 1 upwards
print("Diagonal offset by 1 upwards:",np.diagonal(m,1))

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]

Trace of matrix: 385
Anti-diagonal matrix: [10 18 24 28 30 30 28 24 18 10]
Diagonal offset by 1 upwards: [ 2  6 12 20 30 42 56 72 90]


6\. **Broadcasting**

Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles.

The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
mile=np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])
print("in miles:",mile)
d= np.abs(mile-mile[:, np.newaxis])
print("distances:","\n",d)
d_km = d*1.609344
print("distance array in km:","\n" ,d_km.round(2))

in miles: [   0  198  303  736  871 1175 1475 1544 1913 2448]
distances: 
 [[   0  198  303  736  871 1175 1475 1544 1913 2448]
 [ 198    0  105  538  673  977 1277 1346 1715 2250]
 [ 303  105    0  433  568  872 1172 1241 1610 2145]
 [ 736  538  433    0  135  439  739  808 1177 1712]
 [ 871  673  568  135    0  304  604  673 1042 1577]
 [1175  977  872  439  304    0  300  369  738 1273]
 [1475 1277 1172  739  604  300    0   69  438  973]
 [1544 1346 1241  808  673  369   69    0  369  904]
 [1913 1715 1610 1177 1042  738  438  369    0  535]
 [2448 2250 2145 1712 1577 1273  973  904  535    0]]
distance array in km: 
 [[   0.    318.65  487.63 1184.48 1401.74 1890.98 2373.78 2484.83 3078.68
  3939.67]
 [ 318.65    0.    168.98  865.83 1083.09 1572.33 2055.13 2166.18 2760.02
  3621.02]
 [ 487.63  168.98    0.    696.85  914.11 1403.35 1886.15 1997.2  2591.04
  3452.04]
 [1184.48  865.83  696.85    0.    217.26  706.5  1189.31 1300.35 1894.2
  2755.2 ]
 [1401.74 1083.09  914.11  217.

7\. **Prime numbers sieve**

Compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).

  * Constract a shape (N,) boolean array, which is the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (with `timeit`); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [ ]:
import timeit

def SieveOfEratosthenes(n):
    prime = [True for i in range(n + 1)]
    p = 2
    while (p * p <= n):
        if (prime[p] == True):   
            for i in range(p ** 2, n + 1, p):
                prime[i] = False
        p += 1
    prime[0]= False
    prime[1]= False
    for j in range(n + 1):
        if prime[j]:
            print (j) 
            
#The performance of the program decreases when N increases and the time increases.
starttime = timeit.default_timer()
SieveOfEratosthenes(1000)
print("The time is:", timeit.default_timer() - starttime)

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
101
103
107
109
113
127
131
137
139
149
151
157
163
167
173
179
181
191
193
197
199
211
223
227
229
233
239
241
251
257
263
269
271
277
281
283
293
307
311
313
317
331
337
347
349
353
359
367
373
379
383
389
397
401
409
419
421
431
433
439
443
449
457
461
463
467
479
487
491
499
503
509
521
523
541
547
557
563
569
571
577
587
593
599
601
607
613
617
619
631
641
643
647
653
659
661
673
677
683
691
701
709
719
727
733
739
743
751
757
761
769
773
787
797
809
811
821
823
827
829
839
853
857
859
863
877
881
883
887
907
911
919
929
937
941
947
953
967
971
977
983
991
997
The time difference is : 0.0011187090130988508
