# **Exercise 1**

In [ ]:
import numpy as np
import pandas as pd
import random 
import csv
import itertools

In [ ]:
f = open("data_int.txt", "w")
listofnums = []
n = random.randint(1,1000)
for i in range(0,n):
  listofnums.append(random.randint(0,10000))
f.write(str(listofnums)) 
f.close()

!cat data_int.txt

[2516, 5153, 6114, 6462, 8053, 8582, 8198, 6863, 7823, 5468, 6126, 7316, 1995, 655, 7628, 5419, 3176, 9708, 5766, 7017, 6405, 2830, 2698, 6127, 677, 2441, 8015, 6698, 9224, 8154, 9147, 3251, 8798, 62, 9201, 4650, 9040, 3783, 8063, 4267, 3183, 3297, 7948, 30, 4029, 431, 9610, 5959, 2095, 3010, 3778, 5417, 9581, 2618, 1408, 3003, 3108, 4273, 5126, 3011, 7925, 9399, 9051, 4116, 5573, 3828, 6162, 4449, 5088, 1217, 8280, 8820, 1095, 909, 5426, 1618, 6332, 6616, 9156, 7182, 368, 6974, 6756, 4031, 2837, 5404, 3363, 9410, 83, 7841, 3637, 7290, 5012, 2588, 7620, 7384, 8853, 575, 6444, 7061, 1731, 1641, 4076, 1346, 5613, 2211, 2040, 1632, 3908, 1783, 2619, 477, 3114, 5005, 1790, 1514, 8622, 7427, 70, 1671, 1305, 7307, 6886, 1636, 9842, 9650, 8052, 8842, 610, 1556, 6975, 7686, 6164, 5336, 9771, 3999, 2320, 2215, 6588, 1887, 9300, 92, 3329, 1827, 4738, 9989, 3909, 8176, 9602, 5296, 8957, 8104, 1615, 7861, 4746, 3579, 7782, 4931, 1686, 7436, 2157, 1411, 8368, 1092, 3241, 6681, 0, 4923, 9298, 4478, 

In [ ]:
mat = np.random.rand(5, 5)
x = open("data_float.txt", "w")
x.write(str(mat)) 
x.close()
!cat data_float.txt

[[0.03383209 0.5855969  0.68577528 0.6684733  0.42253028]
 [0.46423355 0.37230867 0.31287001 0.03226879 0.13664692]
 [0.52455628 0.26754557 0.77697765 0.94673258 0.73541886]
 [0.3373443  0.45535402 0.1753594  0.80170973 0.83739037]
 [0.23620458 0.81707856 0.97764038 0.21823009 0.47333314]]

In [ ]:
with open("data_float.txt", 'r') as infile, open("data_float.csv", 'w') as outfile:
        stripped = (line.strip() for line in infile)
        lines = (line.split(",") for line in stripped if line)
        writer = csv.writer(outfile)
        writer.writerows(lines)

!cat data_float.csv

[[0.03383209 0.5855969  0.68577528 0.6684733  0.42253028]
[0.46423355 0.37230867 0.31287001 0.03226879 0.13664692]
[0.52455628 0.26754557 0.77697765 0.94673258 0.73541886]
[0.3373443  0.45535402 0.1753594  0.80170973 0.83739037]
[0.23620458 0.81707856 0.97764038 0.21823009 0.47333314]]


# **Exercise 2**

In [ ]:
import json

In [ ]:
data = json.load(open('user_data.json'))
datafiltered = list(filter(lambda x: x['CreditCardType'] ==  "American Express", data))

[{'ID': '1', 'JobTitle': 'Project Manager', 'EmailAddress': 'Remy_Crawford1065@typill.biz', 'FirstNameLastName': 'Remy Crawford', 'CreditCard': '6205-7258-7671-0612', 'CreditCardType': 'Capital One'}, {'ID': '2', 'JobTitle': 'Investment  Advisor', 'EmailAddress': 'Clint_Thorpe5003@bulaffy.com', 'FirstNameLastName': 'Clint Thorpe', 'CreditCard': '7083-8766-0251-2345', 'CreditCardType': 'American Express'}, {'ID': '3', 'JobTitle': 'Cook', 'EmailAddress': 'Russel_Hooper9403@bulaffy.com', 'FirstNameLastName': 'Russel Hooper', 'CreditCard': '6378-4461-8535-5847', 'CreditCardType': 'Discover'}, {'ID': '4', 'JobTitle': 'Business Broker', 'EmailAddress': 'Benjamin_Rowan6280@gembat.biz', 'FirstNameLastName': 'Benjamin Rowan', 'CreditCard': '5781-7635-1428-7414', 'CreditCardType': 'Discover'}, {'ID': '5', 'JobTitle': 'Loan Officer', 'EmailAddress': 'Matt_Lloyd3241@guentu.biz', 'FirstNameLastName': 'Matt Lloyd', 'CreditCard': '5771-8416-2736-1700', 'CreditCardType': 'Citibank'}, {'ID': '6', 'JobT

In [ ]:
pd.DataFrame(datafiltered).to_csv("/user_data.csv")

# **Exercise 3**

In [ ]:
import pandas as pd
datamush = pd.read_csv("mushrooms_categorized.csv")
print("Type: ",type(datamush))
print("length: ", len(datamush))
print("shape: ", datamush.shape)

Type:  <class 'pandas.core.frame.DataFrame'>
length:  8124
shape:  (8124, 23)


In [ ]:
print("head: \n", datamush.head())

head: 
    class  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0      1          5            2          4        1     6                1   
1      0          5            2          9        1     0                1   
2      0          0            2          8        1     3                1   
3      1          5            3          8        1     6                1   
4      0          5            2          3        0     5                1   

   gill-spacing  gill-size  gill-color  ...  stalk-surface-below-ring  \
0             0          1           4  ...                         2   
1             0          0           4  ...                         2   
2             0          0           5  ...                         2   
3             0          1           5  ...                         2   
4             1          0           4  ...                         2   

   stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-color  \
0 

In [ ]:
print("Tail: \n", datamush.tail())

Tail: 
       class  cap-shape  cap-surface  cap-color  bruises  odor  \
8119      0          3            2          4        0     5   
8120      0          5            2          4        0     5   
8121      0          2            2          4        0     5   
8122      1          3            3          4        0     8   
8123      0          5            2          4        0     5   

      gill-attachment  gill-spacing  gill-size  gill-color  ...  \
8119                0             0          0          11  ...   
8120                0             0          0          11  ...   
8121                0             0          0           5  ...   
8122                1             0          1           0  ...   
8123                0             0          0          11  ...   

      stalk-surface-below-ring  stalk-color-above-ring  \
8119                         2                       5   
8120                         2                       5   
8121                    

In [ ]:
datamush.groupby(['class']).mean()

cap-shape  cap-surface  cap-color   bruises      odor  gill-attachment  \
class                                                                           
0       3.266160     1.615970   4.581749  0.653992  4.334601         0.954373   
1       3.436159     2.055158   4.421859  0.159346  3.940756         0.995403   

       gill-spacing  gill-size  gill-color  stalk-shape  ...  \
class                                                    ...   
0          0.285171   0.068441    6.622624     0.615970  ...   
1          0.028601   0.567926    2.863636     0.514811  ...   

       stalk-surface-below-ring  stalk-color-above-ring  \
class                                                     
0                      1.798479                6.098859   
1                      1.394280                5.512768   

       stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
class                                                                          
0                    6.064639        0.0    1.931559     1.125475   3.007605   
1                    5.504597        0.0    2.002043     1.009193   1.522983   

       spore-print-color  population   habitat  
class                                           
0               3.201521    3.283270  1.148289  
1               4.021450    4.031665  1.895812  

[2 rows x 22 columns]

In [ ]:
datamush.to_json("/mushrooms_categorized.json")

# **Exercise 4**

In [ ]:
credits = pd.read_csv("credit_card.dat",header = None)
credits

0
0   1101111101101101001110001000001101011101101101...
1   1100111100101101011101111000001110001100101101...
2   1100101101111100101100101000001100001100001100...
3   1100001101101101101100011000001100111100001101...
4   1100001101001100111100101000001100011101101100...
5   1101011110001100101101111000001100101100001100...
6   1101011101111101111101001000001110001101011100...
7   1110001100011101001100001000001100011100101100...
8   1101011101111101101101001000001100011100011100...
9   1101101101001101011101101000001100011101111100...
10  1100011100101100101110001000001110001101101100...
11  1101111100001101011100011000001100001100011101...
12  1100001101101100011110001000001100111101011110...
13  1100011101011101001101011000001101011101001101...
14  1101101101111100111101011000001100111100011100...
15  1101111100101110001101111000001101011100001100...
16  1101111100001100111100111000001100101101101100...
17  1100101101011101101110001000001101011100101101...
18  1100011101101110001101001000001100101100101101...
19  1100001101101101111100101000001100101101011101...
20  1101101100111100111100101000001110001100111101...
21  1100011110001100011100111000001100111100111101...
22  1100101101001101111101111000001101101101001101...
23  1101011101011100011100101000001100111101011100...
24  1100111100001110001100111000001101111110001110...
25  1101001101011100101100011000001101011100011101...
26  1101111101011101101100111000001100111101101101...
27  1110001100111100101101001000001100101101101101...
28  1100001101011101101101011000001100101101011100...
29  1101011100011100001101111000001101011101011100...
30  1100101101001101101100101000001100011110001100...
31  1100101101111110001110001000001100001101101100...
32  1101011110001101011100011000001101011110001101...
33  1100001101101101111100001000001100011100001100...
34  1101011110001101111101001000001101011101011100...
35  1100101110001100001101011000001101011101001100...
36  1101011100001110001100111000001110001101001100...
37  1100011100001101111101101000001100011101001101...
38  1110001101001101001100001000001101001110001100...
39  1101001101111101011110001000001101101100011101...
40  1101111101011110001101101000001100001101101101...
41  1100101101011101001101001000001100011100101101...
42  1100111101001101111101001000001101011100001100...
43  1100011101001100011100001000001100001100101101...
44  1101111100111100011101011000001101001101001101...
45  1100001100101100101101001000001101111101111101...
46  1100001100011101111100001000001100101101111100...
47  1100101100001100001101101000001100101101001100...
48  1110001100011101001100101000001101001100001101...
49  1100111100001100101101101000001101111100111110...
50                                               1010

In [ ]:
creditnumbers = []
for i in credits[0]:
  listofcredit = []
  if i != "1010":
    for j in range(0,114,6):
      a = i[j:j+6]
      listofcredit.append(chr(int(a,2)))
      creditstr = ''.join(listofcredit)

    creditnumbers.append(creditstr)
    creditcard = ''.join(creditstr)

creditnumbers

      

['7648 5673 3775 2271',
 '3257 8247 3354 2266',
 '2722 0001 4011 6652',
 '0661 3063 3742 3150',
 '0432 1608 1462 4742',
 '5827 2027 8785 7303',
 '5774 8528 2087 1117',
 '8140 1210 6352 2845',
 '5764 1133 7301 7100',
 '6456 1737 4126 6726',
 '1228 8631 7382 0000',
 '7051 0160 5374 3166',
 '0618 3587 1630 6376',
 '1545 5454 7444 5636',
 '6735 3116 3202 6834',
 '7287 5011 1547 8413',
 '7033 2607 3328 4200',
 '2568 5244 1874 5024',
 '1684 2253 7570 7118',
 '0672 2576 0575 6631',
 '6332 8353 8787 1340',
 '1813 3361 1175 4211',
 '2477 6450 8840 2368',
 '5512 3505 2563 1326',
 '3083 7882 0621 0025',
 '4521 5148 8045 0334',
 '7563 3654 8713 5787',
 '8324 2664 0476 5561',
 '0565 2504 7168 3510',
 '5107 5507 1767 0738',
 '2462 1821 2448 1443',
 '2788 0638 6861 6554',
 '5851 5873 5474 0547',
 '0670 1004 4013 2655',
 '5874 5506 3048 0806',
 '2805 5401 8462 1260',
 '5083 8406 6310 1862',
 '1076 1445 3013 2266',
 '8440 4804 4844 5277',
 '4758 6141 0686 1387',
 '7586 0675 0315 2568',
 '2544 1258 7432

# **Exercise 5**