1\. **Reductions**

Find the total mean, and the mean for each row and column of the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [11]:
import numpy as np

m = np.arange(12).reshape((3,4))

tot_mean = m.mean()

row_mean = m.mean(1)
column_mean = m.mean(0)

print(f'Matrix: \n{m}')
print(f"\nTotal mean: {m.mean()}")

print(f"\nMean of each row: {row_mean}")
print(f"\nMean of each column: {column_mean}")

Matrix: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Total mean: 5.5

Mean of each row: [1.5 5.5 9.5]

Mean of each column: [4. 5. 6. 7.]


2\. **Outer product**

Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [13]:
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])

result = np.outer(u,v)
print(f"Outer product with outer function:\n{result}")

result1 = np.empty([4,4])

for i in range (u.size):
    for j in range (v.size):
        result1[i,j] = u[i]*v[j]
        
print(f"\nOuter product with nested for loop:\n{result1}")

result2 = np.empty([4,4])
for i in range (u.size):
    result2[i] = u[i]*v
    
print(f"\nOuter product with numpy broadcasting operations:\n{result2}")

Outer product with outer function:
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]

Outer product with nested for loop:
[[ 2.  4.  6.  8.]
 [ 6. 12. 18. 24.]
 [10. 20. 30. 40.]
 [14. 28. 42. 56.]]

Outer product with numpy broadcasting operations:
[[ 2.  4.  6.  8.]
 [ 6. 12. 18. 24.]
 [10. 20. 30. 40.]
 [14. 28. 42. 56.]]


3\. **Matrix masking**

Create a 10 by 6 matrix of float random numbers, distributed between 0 and 3 according to a flat distribution.

After creating the matrix, set all entries $< 0.3$ to zero using a mask.

In [14]:
m_result = np.random.uniform(0,3,[10,6])
print(f"Original Matrix:\n {m_result}")

mask = (m_result < 0.3)
m_result[mask] = 0
print(f"\nMatrix with all entries < 0.3 set to zero:\n{m_result}")

Original Matrix:
 [[1.07118267 1.14415689 1.91994814 1.31743822 2.31203763 2.8016696 ]
 [0.16155508 1.71737885 2.65832076 2.45205983 2.89647586 0.35807394]
 [2.22147933 1.2071397  0.86013363 1.18991305 1.30374612 0.92301865]
 [2.02050025 1.02659467 0.65370811 0.90176598 0.70663152 1.38024977]
 [1.52462588 2.7315711  0.23894257 1.0992285  2.81636796 2.42646857]
 [0.74097483 0.32292979 1.74760337 1.7961854  1.28986549 2.31495414]
 [2.22199106 1.52825625 1.21775374 2.23126037 1.97812658 0.95494887]
 [0.79830356 1.08098161 1.94966423 2.1331089  2.69563656 0.33015275]
 [1.98456039 0.81574544 1.63090798 1.0073339  2.63697524 2.30886901]
 [2.68605949 2.11832459 0.89842354 1.47096873 2.56869576 0.00751358]]

Matrix with all entries < 0.3 set to zero:
[[1.07118267 1.14415689 1.91994814 1.31743822 2.31203763 2.8016696 ]
 [0.         1.71737885 2.65832076 2.45205983 2.89647586 0.35807394]
 [2.22147933 1.2071397  0.86013363 1.18991305 1.30374612 0.92301865]
 [2.02050025 1.02659467 0.65370811 0.901

4\. **Trigonometric functions**

Use `np.linspace` to create an array of 100 numbers between $0$ and $2\pi$ (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the `sin` and `cos` functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

In [19]:
from math import pi,sin,cos
array_lin = np.linspace(0, 2*pi, num=100)
print(f"Original array of 100 numbers between 0 and {pi}:\n{array_lin}")

slice_a = array_lin[0:100:10]
print(f"\nExtract every 10th element: \n{slice_a}")

rev_a = array_lin[::-1]
print(f"\nReverse the array: \n{rev_a}")

mask = (abs(np.sin(array_lin)-np.cos(array_lin))<0.1)
result = array_lin[mask]
print(f"\nExtraction of elements abs(sin(element)-cos(element)) < 0.1:\n{result}")

Original array of 100 numbers between 0 and 3.141592653589793:
[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 

5\. **Matrices**

Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [36]:
matrix_multi = np.zeros([10,10])

for i in range(len(matrix_multi[0])):
    for j in range(len(matrix_multi[1])):
        matrix_multi[i,j] = (i+1)*(j+1)
print(f"Matrix of the 10 by 10 multiplication table: \n{matrix_multi}")

matrix_trace = matrix_multi.trace()
print(f"\nTrace of the matrix:\n {matrix_trace}")

matrix_anti_diag = np.fliplr(matrix_multi).diagonal()
print(f"\nAnti-diagonal matrix:\n {matrix_anti_diag}")


print(f"\nDiagonal offset by 1 upwards:\n {matrix_multi.diagonal(1)}")

Matrix of the 10 by 10 multiplication table: 
[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  2.   4.   6.   8.  10.  12.  14.  16.  18.  20.]
 [  3.   6.   9.  12.  15.  18.  21.  24.  27.  30.]
 [  4.   8.  12.  16.  20.  24.  28.  32.  36.  40.]
 [  5.  10.  15.  20.  25.  30.  35.  40.  45.  50.]
 [  6.  12.  18.  24.  30.  36.  42.  48.  54.  60.]
 [  7.  14.  21.  28.  35.  42.  49.  56.  63.  70.]
 [  8.  16.  24.  32.  40.  48.  56.  64.  72.  80.]
 [  9.  18.  27.  36.  45.  54.  63.  72.  81.  90.]
 [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]]

Trace of the matrix:
 385.0

Anti-diagonal matrix:
 [10. 18. 24. 28. 30. 30. 28. 24. 18. 10.]

Diagonal offset by 1 upwards:
 [ 2.  6. 12. 20. 30. 42. 56. 72. 90.]


6\. **Broadcasting**

Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles.

The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

7\. **Prime numbers sieve**

Compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).

  * Constract a shape (N,) boolean array, which is the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (with `timeit`); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

8\. **Diffusion using random walk**

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of many random walkers after a given amount of time.

*Hint*: create a 2D array where each row represents a walker, and each column represents a time step.

  * Take 1000 walkers and let them walk for 200 steps
  * Use `randint` to create a 2D array of size $walkers \times steps$ with values -1 or 1
  * Calculate the walking distances for each walker (e.g. by summing the elements in each row)
  * Take the square of the previously-obtained array (element-wise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * **Optional**: plot the average distances ($\sqrt(distance^2)$) as a function of time (step)