In [1]:
#1. Reductions
#Find the total mean, and the mean for each row and column of the following matrix
import numpy as np
m = np.arange(12).reshape((3,4))
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [2]:
#2. 32-bit floating point number:
def convertToFloat(b):
    s= b[0]             #Sign bit
    s = int(s)
    print("sign bit: ", s)
    exp = b[1:9]        #Exponent bits
    print("exponent bits: ", exp)
    exp= int(exp,2)     #Convert binary to decimal for getting the exponent No
    print("exponent number is: ", exp)
    f = b[9:32]         #Fraction bits
    print("Fraction bits: ", f)
    ans=0
    for i in range(len(f)):   #Fraction exponent
        if f[i] == '1':
            ans += 1/(2**i)
    f = ans
    print("fraction number is: ", f)
    floatNo = (-1)**s * (1 + f) * 2**(exp - 127)
    return floatNo

binaryNo= "11000010101100000000000000000000" #32bits
print("The float number is: ", convertToFloat(binaryNo))


sign bit:  1
exponent bits:  10000101
exponent number is:  133
Fraction bits:  01100000000000000000000
fraction number is:  0.75
The float number is:  -112.0


In [3]:
#3. Underflow and overflow
from cmath import inf
def determineOverUnderFlow():
    a = 1.0
    b = 1.0
    overflowCounter, underflowCounter=0,0

    #Determine overflow_______
    while(a != inf):
        a= a*2
        overflowCounter +=1
        #print(a)
    print("Over flow Counter: ", overflowCounter)

    #Determine underflow_______
    while(b != 0.0):
        b= b/2.0
        underflowCounter +=1
        #print(b)
    print("Under flow Counter: ", underflowCounter)

determineOverUnderFlow()

Over flow Counter:  1024
Under flow Counter:  1075


In [4]:
#4. Machine precision
def Detectprecision():
    a=7.0
    b=12
    ans=0
    # Addding an increasingly small number to 7
    while(ans != a): 
        ans = a + 1.0 * 10**-b
        b+=1
        print(ans)
    print("Machin precision is: ", b-1)

Detectprecision()

7.000000000001
7.0000000000001
7.00000000000001
7.000000000000001
7.0
Machin precision is:  16


In [5]:
#5. Quadratic solution
import math as m
#part a:
def findRoots(a,b,c):
    x1 = (-b + m.sqrt(b**2-(4*a*c))/(2*a))
    x2 = (-b - m.sqrt(b**2-(4*a*c))/(2*a))
    print("There are root1: ",x1, "& root2: ",x2)
    
findRoots(0.001,1000,0.001)

#part b:
def findRoots2(a,b,c):
    dev = 1/a
    x2 =  (-b + (b ** 2 - 4 * a * c) ** 0.5) * (0.5 * dev)
    x3 = (-b - (b ** 2 - 4 * a * c) ** 0.5) * (0.5 * dev)
    print("by re-expression formula there are root1: ",x2, "& root2: ",x3)
    #This answer is more accurate by re-expression the formula including: sqrt and division

findRoots2(0.001,1000,0.001)


#part c:
def findRoots3(a,b,c):
    r = b**2 - 4*a*c
    if r > 0:
        num_roots = 2
        x4 = (((-b) + m.sqrt(r))/(2*a))     
        x5= (((-b) - m.sqrt(r))/(2*a))
        print("There are 2 roots: %f and %f" % (x4, x5))
    elif r == 0:
        num_roots = 1
        x = (-b) / 2*a
        print("There is one root: ", x)
    else:
        num_roots = 0
        print("No roots, discriminant < 0.")

print("Apply a function for all cases")
findRoots3(0.001,1000,0.001)
    

There are root1:  498999.999999 & root2:  -500999.999999
by re-expression formula there are root1:  -9.999894245993346e-07 & root2:  -999999.999999
Apply a function for all cases
There are 2 roots: -0.000001 and -999999.999999


In [6]:
#6. The derivative
#Part a:
def f(x):
    return (x * (x-1))
#lim[f(x+d)]-f(x)]/d = ([f(1+0.01) - f(1)]/0.01)
driv=(f(1 + 0.01) - f(1)) /0.01
print("derivative is:" , driv)
print("step derivative is: 1.01, derivative in analytically : 2x -1 -> for x=1 : derivative = 1")

#part b:
dList =[10e-4, 10e-6, 10e-8, 10e-10, 10e-12]
for i in dList:
    driv =(f(1 + i) - f(1))/i
    print("derivation is: ", driv)
    
print("In each step the derivation are closed to absolute derivation which is equal to 1")


derivative is: 1.010000000000001
step derivative is: 1.01, derivative in analytically : 2x -1 -> for x=1 : derivative = 1
derivation is:  1.0009999999998895
derivation is:  1.0000100000065513
derivation is:  1.0000001005838672
derivation is:  1.000000083740371
derivation is:  1.000000082750371
In each step the derivation are closed to absolute derivation which is equal to 1


In [7]:
#7. Integral of a semicircle
import math as m
import time
#Part a:
def Integral(N):
    I=0
    for i in range(N):
        x = -1 + (i*2/N) #The span of (-1,1) is devided to 100 steps
        I+= m.sqrt(1- x**2) * 2/N
    return I

print("Real Area: ", m.pi/2)
print("Calculated Area: ", Integral(100))

#Part b: for 1 Second computation
startTime = time.time()
difTime=0
N = 100
ans =0
while(int(difTime) < 1):
    N += 100
    ans=Integral(N)
    difTime = time.time()-startTime
    print("dif time : ", int(difTime))
    
print("Execution time: ", difTime, "sec and steps for n is: ", N, "Calculated Area is: ", ans) # N is 36700

#Part b: for 60 Second computation
startTime = time.time()
difTime=0
N = 100
ans = 0
while(int(difTime) < 60):
    N += 100
    ans = Integral(N)
    difTime = time.time()-startTime
    print("dif time : ", int(difTime))
    
print("Execution time: ", difTime, "sec and steps for n is: ", N, "Calculated Area is: ", ans)  # N is 288300


Real Area:  1.5707963267948966
Calculated Area:  1.5691342555492505
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time :  0
dif time