In [1]:
import pandas as pd
import numpy as np
import csv

1\. **Text files**

In [40]:
#a)
from random import random, seed
#seed(0)
L = [ int(random()*10) for i in range(10) ]
print("list l:\n ", L, "\n")

with open("./data_int.txt", mode = 'w') as f:
    #f.write(str(L))
    for item in L:
        f.write("%s " % item)
        
print("loded txt list file:")        
!cat ./data_int.txt #read and show list
print('\n')
      
#b) 
b= np.random.random((5,5))
mat = np.matrix(b)
print("random 5*5 matrix:\n", mat, "\n")    
with open('data_float.txt','wb') as f:
    #f.write(str(mat))
    for line in mat:
        np.savetxt(f, line, fmt='%.2f')
        
print("data_float:")
!cat ./data_float.txt #read and show floattxt file
print('\n')

#c)
f = open('./data_float.txt', 'r')
textContent = f.read()
print("loded txt file: \n", textContent)
f.close()
'''
with open('./data_float.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(textContent)
'''


import zlib
lines = textContent.splitlines()
rawContent = [line.split(' ') for line in lines]
rows = zip(*[rawContent]*1)
with open('data_float.csv', 'w') as out_file:
    writer = csv.writer(out_file)
    for row in rows:
        writer.writerows(row)
print("csv file: ")
!cat ./data_float.csv #read and show csv file
print('\n')

list l:
  [5, 6, 0, 1, 3, 5, 2, 6, 1, 2] 

loded txt list file:
5 6 0 1 3 5 2 6 1 2 

random 5*5 matrix:
 [[0.94571191 0.01610061 0.51257281 0.53274395 0.86967777]
 [0.85200031 0.34894714 0.15744366 0.2943746  0.2380598 ]
 [0.5708948  0.37088368 0.95707113 0.22161501 0.71578835]
 [0.50683816 0.59950876 0.12359753 0.98491655 0.73822245]
 [0.76784081 0.66518005 0.68171556 0.21512899 0.19848909]] 

data_float:
0.95 0.02 0.51 0.53 0.87
0.85 0.35 0.16 0.29 0.24
0.57 0.37 0.96 0.22 0.72
0.51 0.60 0.12 0.98 0.74
0.77 0.67 0.68 0.22 0.20


loded txt file: 
 0.95 0.02 0.51 0.53 0.87
0.85 0.35 0.16 0.29 0.24
0.57 0.37 0.96 0.22 0.72
0.51 0.60 0.12 0.98 0.74
0.77 0.67 0.68 0.22 0.20

csv file: 
0.95,0.02,0.51,0.53,0.87
0.85,0.35,0.16,0.29,0.24
0.57,0.37,0.96,0.22,0.72
0.51,0.60,0.12,0.98,0.74
0.77,0.67,0.68,0.22,0.20




2\. **JSON files**

In [41]:
import json # import the JSON module
#!wget https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json    
data = json.load(open('user_data.json'))
#print(data)

header = ["ID","JobTitle","EmailAddress","FirstNameLastName","CreditCard", "CreditCardType"]
l=[]
for a in data:
    if a['CreditCardType'] == 'American Express':
        array= [a["ID"], a["JobTitle"], a["EmailAddress"],a["FirstNameLastName"],a["CreditCard"],a["CreditCardType"]]
        l.append(array)
              
#print(l)
with open('jsonfiltered.csv','w') as csv_file:
    writer = csv.writer(csv_file)
    writer.writerow(header)
    writer.writerow(l) #??? what about "[....]"!
          
print("csv file: ")
!cat jsonfiltered.csv #read and show csv file


csv file: 
ID,JobTitle,EmailAddress,FirstNameLastName,CreditCard,CreditCardType
"['2', 'Investment  Advisor', 'Clint_Thorpe5003@bulaffy.com', 'Clint Thorpe', '7083-8766-0251-2345', 'American Express']","['12', 'Retail Trainee', 'Phillip_Carpenter9505@famism.biz', 'Phillip Carpenter', '3657-0088-0820-5247', 'American Express']","['28', 'Project Manager', 'Russel_Graves1378@extex.org', 'Russel Graves', '6718-4818-8011-6024', 'American Express']","['39', 'Stockbroker', 'Leanne_Newton1268@typill.biz', 'Leanne Newton', '5438-0816-4166-4847', 'American Express']","['57', 'Budget Analyst', 'Tony_Giles1960@iatim.tech', 'Tony Giles', '8130-3425-7573-7745', 'American Express']","['62', 'CNC Operator', 'Owen_Allcott5125@bauros.biz', 'Owen Allcott', '4156-0107-7210-2630', 'American Express']","['68', 'Project Manager', 'Liam_Lynn3280@kideod.biz', 'Liam Lynn', '7152-3247-6053-2233', 'American Express']","['74', 'Dentist', 'Regina_Woodcock5820@yahoo.com', 'Regina Woodcock', '0208-1753-3870-8002', 'A

3\. **CSV files with Pandas**

In [42]:
#!wget https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv
file_name= "mushrooms_categorized.csv"
data = pd.read_csv(file_name)
#print(data)
#!cat mushrooms_categorized.csv

gb = data.groupby(['class']).mean()
#mean_json= gb.to_json()
#print(mean_json)

df = pd.DataFrame(gb)

df.to_json(r'./export_mean_json.json', orient = 'index')


4\. **Reading the credit card numbers**

In [43]:
#!wget https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat
import math as m

with open('credit_card.dat', 'rb') as file:
    file_content = file.readlines()
    #print(file_content)
    allcarts =[]
    word_counter = 0
    word_size = 8 # size of the word in bytes
    total_digitnumber = 16+3 #size of total digit
    digit_length = 6          #sizeof each character with whitespace
    
    
    for row in file_content:
        #print(round(len(row)/digit_length))
        if(round(len(row)/digit_length) >= total_digitnumber):
            
            utf_string = row.decode("utf-8")  #decode the line into string
            #print("1:\n", utf_string, "\n")
            utf_string = utf_string[:-4]      #remove the last 4 bit : end of line
            #print("2:\n", utf_string, "\n")
            
            start_index = 0
            card_number=[]
            
            for i in range(total_digitnumber):
                end_index = start_index + digit_length
                digits_4 = utf_string[start_index:end_index]
                card_number.append(digits_4)
                start_index += digit_length    
                #print(digits_4 ,"\n")
        
            #print("card number: ", card_number, "\n")

            credit_card = ""
            for i in range(total_digitnumber):
                credit_card += chr(int(card_number[i],2))
            
            allcarts.append(credit_card)
            
    print("Number of all the Credit Card is :\n") 
    for i in allcarts:
        print(i, "\n")
        
        


Number of all the Credit Card is :

7648 5673 3775 2271 

3257 8247 3354 2266 

2722 0001 4011 6652 

0661 3063 3742 3150 

0432 1608 1462 4742 

5827 2027 8785 7303 

5774 8528 2087 1117 

8140 1210 6352 2845 

5764 1133 7301 7100 

6456 1737 4126 6726 

1228 8631 7382 0000 

7051 0160 5374 3166 

0618 3587 1630 6376 

1545 5454 7444 5636 

6735 3116 3202 6834 

7287 5011 1547 8413 

7033 2607 3328 4200 

2568 5244 1874 5024 

1684 2253 7570 7118 

0672 2576 0575 6631 

6332 8353 8787 1340 

1813 3361 1175 4211 

2477 6450 8840 2368 

5512 3505 2563 1326 

3083 7882 0621 0025 

4521 5148 8045 0334 

7563 3654 8713 5787 

8324 2664 0476 5561 

0565 2504 7168 3510 

5107 5507 1767 0738 

2462 1821 2448 1443 

2788 0638 6861 6554 

5851 5873 5474 0547 

0670 1004 4013 2655 

5874 5506 3048 0806 

2805 5401 8462 1260 

5083 8406 6310 1862 

1076 1445 3013 2266 

8440 4804 4844 5277 

4758 6141 0686 1387 

7586 0675 0315 2568 

2544 1258 7432 5165 

3474 5023 4434 5626 

1410 0270 0434 508

5\. **Write data to a binary file**

In [2]:
import pandas as pd
from struct import pack, unpack


#a) Packing-----------
binary_file= open('data/data_000637.dat', 'wb')
file_name= "data/data_000637.txt"

data = pd.read_csv(file_name, nrows =10, skiprows=range(1,1))
print("data: \n", data, "\n")
print("Binary: ")
for i in range(len(data)):
    h = data.loc[data.index[i], 'HEAD']
    f = data.loc[data.index[i], 'FPGA']
    t = data.loc[data.index[i], 'TDC_CHANNEL']
    o = data.loc[data.index[i], 'ORBIT_CNT']
    b = data.loc[data.index[i], 'BX_COUNTER']
    td = data.loc[data.index[i], 'TDC_MEAS']
    
    word  = (h & 0x3) << 62
    word += (f & 0xF) << 58
    word += (t & 0x1FF) << 49
    word += (o & 0xFFFFFFFF) << 17
    word += (b & 0xFFF) << 5
    word += (td & 0x1F) << 0
    packed = pack('<q', word)
    print(packed)
    binary_file.write(packed)
    
binary_file.close()

#b) Unpacking-----------
with open('data/data_000637.dat', 'rb') as file:
    file_content = file.read()
    word_counter = 0
    word_size = 8 # size of the word in bytes
    for i in range(0, len(file_content), word_size):
        word_counter += 1
        if word_counter > 10: break
        wd = unpack('<q', file_content[i : i + word_size])[0] # get an 8-byte word
        
        head     = (wd >> 62) & 0x3
        fpga     = (wd >> 58) & 0xF
        tdc_chan = (wd >> 49) & 0x1FF
        orb_cnt  = (wd >> 17) & 0xFFFFFFFF
        bx       = (wd >> 5 ) & 0xFFF
        tdc_meas = (wd >> 0 ) & 0x1F
        print('\n{0}\t{1}\t{2}\t{3}\t{4}\t{5}'.format(head, fpga, tdc_chan, orb_cnt, bx, tdc_meas))
        
#c)
print("\nThe size of binary and txt file are respectfully 80 and 312 bytes which shows\n" +
       "saving data in binary format is much more better than .txt due to the less memory consumption")


data: 
    HEAD  FPGA  TDC_CHANNEL   ORBIT_CNT  BX_COUNTER  TDC_MEAS
0     1     0          123  3869200167        2374        26
1     1     0          124  3869200167        2374        27
2     1     0           63  3869200167        2553        28
3     1     0           64  3869200167        2558        19
4     1     0           64  3869200167        2760        25
5     1     0           63  3869200167        2762         4
6     1     0           61  3869200167        2772        14
7     1     0          139  3869200167        2776         0
8     1     0           62  3869200167        2774        21
9     1     0           60  3869200167        2788         7 

Binary: 
b'\xda(O\x9e>\xcd\xf7@'
b'\xdb(O\x9e>\xcd\xf9@'
b'<?O\x9e>\xcd\x7f@'
b'\xd3?O\x9e>\xcd\x81@'
b'\x19YO\x9e>\xcd\x81@'
b'DYO\x9e>\xcd\x7f@'
b'\x8eZO\x9e>\xcd{@'
b'\x00[O\x9e>\xcd\x17A'
b'\xd5ZO\x9e>\xcd}@'
b'\x87\\O\x9e>\xcdy@'

1	0	123	3869200167	2374	26

1	0	124	3869200167	2374	27

1	0	63	3869200167	2553	28

