1\. **Reductions**

Find the total mean, and the mean for each row and column of the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [1]:
import numpy as np
m = np.arange(12).reshape((3,4))

print(m,'\n')
print(f"total mean:{m.mean()}, Column mean:{m.mean(0)},Row mean:{m.mean(1)}")


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

total mean:5.5, Column mean:[4. 5. 6. 7.],Row mean:[1.5 5.5 9.5]


2\. **Outer product**

Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [5]:
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])

In [6]:
np.outer(u,v)

array([[ 2,  4,  6,  8],
       [ 6, 12, 18, 24],
       [10, 20, 30, 40],
       [14, 28, 42, 56]])

In [3]:
np.array([(x*y) for x in u for y in v]).reshape(4,4)

array([[ 2,  4,  6,  8],
       [ 6, 12, 18, 24],
       [10, 20, 30, 40],
       [14, 28, 42, 56]])

In [4]:
u[:,np.newaxis]*v

array([[ 2,  4,  6,  8],
       [ 6, 12, 18, 24],
       [10, 20, 30, 40],
       [14, 28, 42, 56]])

3\. **Matrix masking**

Create a 10 by 6 matrix of float random numbers, distributed between 0 and 3 according to a flat distribution.

After creating the matrix, set all entries $< 0.3$ to zero using a mask.

In [19]:
nums = np.array(np.random.uniform(0,3,60))

matr = nums.reshape(10,6)

    

matr

array([[1.91583911, 1.8098794 , 0.16276201, 2.50548679, 1.09271618,
        0.3738967 ],
       [2.54645432, 2.44171382, 1.98252548, 1.47464257, 2.97541223,
        0.45187086],
       [1.56924074, 2.65817854, 0.10986047, 2.17104428, 1.23295507,
        0.74549802],
       [0.9932066 , 1.59411809, 0.21207588, 2.90785402, 2.69382745,
        0.26203936],
       [1.15803438, 2.98291359, 1.43179168, 0.18748815, 0.40207711,
        0.36446111],
       [1.2501563 , 1.60839819, 1.37803187, 2.08776726, 1.61884894,
        1.14263466],
       [0.72418978, 2.47681011, 1.48275619, 1.9084892 , 1.5332961 ,
        1.46953849],
       [1.69142856, 0.34994284, 1.80527087, 0.60571831, 1.75253787,
        2.15480499],
       [2.67083774, 2.24252884, 2.98955346, 1.26480661, 2.25605825,
        2.50491154],
       [1.45815323, 0.162468  , 1.50563173, 1.54382835, 2.36506342,
        2.29379251]])

4\. **Trigonometric functions**

Use `np.linspace` to create an array of 100 numbers between $0$ and $2\pi$ (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the `sin` and `cos` functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

In [27]:
m = np.linspace(0,2*np.pi,num=100)


def closest_points(x):
    output1=[]
    output2=[]
    for index,i in enumerate(x):
        if np.absolute(np.sin(i)-np.cos(i)) < 0.1:
            output1.append(i)
            output2.append(index)           
    return output2,output1

In [28]:
m        # original array

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [25]:
m[9::10] #extracted values

array([0.57119866, 1.20586385, 1.84052903, 2.47519421, 3.10985939,
       3.74452458, 4.37918976, 5.01385494, 5.64852012, 6.28318531])

In [26]:
m[::-1]  # reversed array

array([6.28318531, 6.21971879, 6.15625227, 6.09278575, 6.02931923,
       5.96585272, 5.9023862 , 5.83891968, 5.77545316, 5.71198664,
       5.64852012, 5.58505361, 5.52158709, 5.45812057, 5.39465405,
       5.33118753, 5.26772102, 5.2042545 , 5.14078798, 5.07732146,
       5.01385494, 4.95038842, 4.88692191, 4.82345539, 4.75998887,
       4.69652235, 4.63305583, 4.56958931, 4.5061228 , 4.44265628,
       4.37918976, 4.31572324, 4.25225672, 4.1887902 , 4.12532369,
       4.06185717, 3.99839065, 3.93492413, 3.87145761, 3.8079911 ,
       3.74452458, 3.68105806, 3.61759154, 3.55412502, 3.4906585 ,
       3.42719199, 3.36372547, 3.30025895, 3.23679243, 3.17332591,
       3.10985939, 3.04639288, 2.98292636, 2.91945984, 2.85599332,
       2.7925268 , 2.72906028, 2.66559377, 2.60212725, 2.53866073,
       2.47519421, 2.41172769, 2.34826118, 2.28479466, 2.22132814,
       2.15786162, 2.0943951 , 2.03092858, 1.96746207, 1.90399555,
       1.84052903, 1.77706251, 1.71359599, 1.65012947, 1.58666

In [23]:
diff(m) #closest points

([12, 13, 61, 62],
 [0.7615982190520711,
  0.8250647373064104,
  3.8714576135146945,
  3.934924131769034])

5\. **Matrices**

Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [30]:
dims = np.array(np.arange(1,11))
matrix = np.outer(dims,dims)




def anti_diagonal(x):
    return np.fliplr(x).diagonal()


matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [31]:
np.trace(matrix) # trace of the matrix

385

In [32]:
anti_diagonal(matrix) #antidiaginal of the matrix

array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])

In [33]:
np.diagonal(matrix[:,1:10]) #diagonal offset by 1 upwards 

array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])

6\. **Broadcasting**

Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles.

The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [35]:
positions_miles =np.array([0,198,303,736,871,1175,1475,1544,1913,2448])
positions_miles

array([   0,  198,  303,  736,  871, 1175, 1475, 1544, 1913, 2448])

In [36]:
distances_miles = np.absolute(positions_miles[:,np.newaxis]-positions_miles)
distances_miles

array([[   0,  198,  303,  736,  871, 1175, 1475, 1544, 1913, 2448],
       [ 198,    0,  105,  538,  673,  977, 1277, 1346, 1715, 2250],
       [ 303,  105,    0,  433,  568,  872, 1172, 1241, 1610, 2145],
       [ 736,  538,  433,    0,  135,  439,  739,  808, 1177, 1712],
       [ 871,  673,  568,  135,    0,  304,  604,  673, 1042, 1577],
       [1175,  977,  872,  439,  304,    0,  300,  369,  738, 1273],
       [1475, 1277, 1172,  739,  604,  300,    0,   69,  438,  973],
       [1544, 1346, 1241,  808,  673,  369,   69,    0,  369,  904],
       [1913, 1715, 1610, 1177, 1042,  738,  438,  369,    0,  535],
       [2448, 2250, 2145, 1712, 1577, 1273,  973,  904,  535,    0]])

In [38]:
distances_km =(distances_miles*1.60934)
distances_km

array([[   0.     ,  318.64932,  487.63002, 1184.47424, 1401.73514,
        1890.9745 , 2373.7765 , 2484.82096, 3078.66742, 3939.66432],
       [ 318.64932,    0.     ,  168.9807 ,  865.82492, 1083.08582,
        1572.32518, 2055.12718, 2166.17164, 2760.0181 , 3621.015  ],
       [ 487.63002,  168.9807 ,    0.     ,  696.84422,  914.10512,
        1403.34448, 1886.14648, 1997.19094, 2591.0374 , 3452.0343 ],
       [1184.47424,  865.82492,  696.84422,    0.     ,  217.2609 ,
         706.50026, 1189.30226, 1300.34672, 1894.19318, 2755.19008],
       [1401.73514, 1083.08582,  914.10512,  217.2609 ,    0.     ,
         489.23936,  972.04136, 1083.08582, 1676.93228, 2537.92918],
       [1890.9745 , 1572.32518, 1403.34448,  706.50026,  489.23936,
           0.     ,  482.802  ,  593.84646, 1187.69292, 2048.68982],
       [2373.7765 , 2055.12718, 1886.14648, 1189.30226,  972.04136,
         482.802  ,    0.     ,  111.04446,  704.89092, 1565.88782],
       [2484.82096, 2166.17164, 1997.1909

7\. **Prime numbers sieve**

Compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).

  * Constract a shape (N,) boolean array, which is the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (with `timeit`); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

8\. **Diffusion using random walk**

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of many random walkers after a given amount of time.

*Hint*: create a 2D array where each row represents a walker, and each column represents a time step.

  * Take 1000 walkers and let them walk for 200 steps
  * Use `randint` to create a 2D array of size $walkers \times steps$ with values -1 or 1
  * Calculate the walking distances for each walker (e.g. by summing the elements in each row)
  * Take the square of the previously-obtained array (element-wise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * **Optional**: plot the average distances ($\sqrt(distance^2)$) as a function of time (step)