In [130]:
import pandas as pd
import numpy as np
import json
import struct
import os

In [131]:
!wget https://www.dropbox.com/s/xvjzaxzz3ysphme/data_000637.txt
!wget https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json
!wget https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv
!wget https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

--2022-11-18 19:54:21--  https://www.dropbox.com/s/xvjzaxzz3ysphme/data_000637.txt
Resolving www.dropbox.com (www.dropbox.com)... 162.125.6.18, 2620:100:601c:18::a27d:612
Connecting to www.dropbox.com (www.dropbox.com)|162.125.6.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/raw/xvjzaxzz3ysphme/data_000637.txt [following]
--2022-11-18 19:54:21--  https://www.dropbox.com/s/raw/xvjzaxzz3ysphme/data_000637.txt
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc8737e1333ed243cef485aeb5bd.dl.dropboxusercontent.com/cd/0/inline/BxAktu_1fJYNScIMBHR4E7DEY48I9UFdQtqhgsaXzlb5hypsqI5-51piH9kjkEN9TkPKYFOmsvUi1O7UVWO43gXiw5MrFZmVyQxRBdjxRFjtlmDEzsI4VuWCmjXG3reQg2W9THlGer8m5FFLIdrZPtIsAka8iO39JyTgNqRWoqAzQA/file# [following]
--2022-11-18 19:54:21--  https://uc8737e1333ed243cef485aeb5bd.dl.dropboxusercontent.com/cd/0/inline/BxAktu_1fJYNScIMBHR4E7DEY48I9UFdQtqhgsaXzlb5hypsqI5-51piH9kjkEN9TkPKYFO

1\. **Text files**

Perform the following operations on plain `txt` files:

+ create a list of integrer numbers and then save it to a text file named `data_int.txt`. Run the `cat` command to print the content of the file.
+ create a matrix of 5x5 floats and then save it to a text file named `data_float.txt`. Use the `cat` command to print the content of the file.
+ load the `txt` file of the previous point and convert it to a `csv` file by hand.

In [132]:
# create a list of integrer numbers and then save it to a text file named data_int.txt. Run the cat command to print the content of the file.

ListOfIntegers = range(1,10)

out_file_name = "data_int.txt"

with open(out_file_name, 'w') as outfile:
  for line in ListOfIntegers:
    outfile.write(str(line) + '\n') 

!cat data_int.txt

1
2
3
4
5
6
7
8
9


In [133]:
# create a matrix of 5x5 floats and then save it to a text file named data_float.txt. Use the cat command to print the content of the file.

MatrixofFloat = np.random.random(size=(5,5))

out_file_name = "data_float.txt"

with open(out_file_name, 'w') as outfile:
  for line in MatrixofFloat:
    outfile.write(str(line) + '\n') 

!cat data_float.txt

[0.28781825 0.73812604 0.76430694 0.65385387 0.15507565]
[0.9760989  0.05883102 0.02259721 0.69023229 0.20175097]
[0.91798875 0.60695717 0.44925013 0.70642195 0.24933526]
[0.31994794 0.6013712  0.12915369 0.59300861 0.52234217]
[0.55164074 0.40571195 0.0738858  0.50367503 0.11628375]


In [134]:
#load the txt file of the previous point and convert it to a csv file by hand.
out_file_name = "data_float.txt"

#Create a DataFrame object
df = pd.DataFrame(columns = ['0' , '1', '2' , '3','4'])

with open(out_file_name, 'r') as outfile:
  for line in outfile:
    df.loc[len(df)] = line[1:-2].split()

df

0           1           2           3           4
0  0.28781825  0.73812604  0.76430694  0.65385387  0.15507565
1   0.9760989  0.05883102  0.02259721  0.69023229  0.20175097
2  0.91798875  0.60695717  0.44925013  0.70642195  0.24933526
3  0.31994794   0.6013712  0.12915369  0.59300861  0.52234217
4  0.55164074  0.40571195   0.0738858  0.50367503  0.11628375

f2\. **JSON files**

Load the file *user_data.json*, which can be found at:

- https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

and filter the data by the "CreditCardType" when it equals to "American Express". Than save the data to a new CSV file.

In [135]:
data = json.load(open('user_data.json'))

#Create a DataFrame object
df = pd.DataFrame(columns = ['ID' , 'JobTitle', 'EmailAddress' , 'FirstNameLastName','CreditCard','CreditCardType'])
for line in data :
  df.loc[len(df)] = line.values()
df = df.set_index('ID')
filter = df[df["CreditCardType"] == 'American Express'] 
filter.to_csv('user_data.csv')

In [136]:
filter

JobTitle                       EmailAddress  \
ID                                                              
2      Investment  Advisor       Clint_Thorpe5003@bulaffy.com   
12          Retail Trainee   Phillip_Carpenter9505@famism.biz   
28         Project Manager        Russel_Graves1378@extex.org   
39             Stockbroker       Leanne_Newton1268@typill.biz   
57          Budget Analyst          Tony_Giles1960@iatim.tech   
62            CNC Operator        Owen_Allcott5125@bauros.biz   
68         Project Manager           Liam_Lynn3280@kideod.biz   
74                 Dentist      Regina_Woodcock5820@yahoo.com   
81           HR Specialist       Carter_Wallace9614@atink.com   
92     Staffing Consultant           Maia_Stark2797@jiman.org   
97             Stockbroker          Ciara_Lomax982@bauros.biz   
116    Staffing Consultant      Isabel_Ellwood1475@fuliss.net   
148           CNC Operator  Abdul_Townend2202@infotech44.tech   
150             Fabricator        Caleb_Poulton1735@atink.com   
151     Restaurant Manager         Ronald_Lewis6777@deavo.com   
154                Bellman        Faith_Seymour3829@twace.org   
169        Assistant Buyer      Anthony_Hancock9083@qater.org   
176  Healthcare Specialist    Isabella_Willson5478@nanoff.biz   
182             Pharmacist     Stephanie_Darcy3298@bauros.biz   
199    Investment  Advisor         Ryan_Kennedy5565@corti.com   

     FirstNameLastName           CreditCard    CreditCardType  
ID                                                             
2         Clint Thorpe  7083-8766-0251-2345  American Express  
12   Phillip Carpenter  3657-0088-0820-5247  American Express  
28       Russel Graves  6718-4818-8011-6024  American Express  
39       Leanne Newton  5438-0816-4166-4847  American Express  
57          Tony Giles  8130-3425-7573-7745  American Express  
62        Owen Allcott  4156-0107-7210-2630  American Express  
68           Liam Lynn  7152-3247-6053-2233  American Express  
74     Regina Woodcock  0208-1753-3870-8002  American Express  
81      Carter Wallace  4256-7201-6717-4322  American Express  
92          Maia Stark  3851-1403-1734-6321  American Express  
97         Ciara Lomax  3702-3440-2472-5424  American Express  
116     Isabel Ellwood  3738-0882-0066-6683  American Express  
148      Abdul Townend  4224-1226-3557-3448  American Express  
150      Caleb Poulton  8203-6875-5225-0341  American Express  
151       Ronald Lewis  7212-0155-5014-8471  American Express  
154      Faith Seymour  4170-5186-6887-6558  American Express  
169    Anthony Hancock  0832-3357-6010-6550  American Express  
176   Isabella Willson  5177-4868-4623-0384  American Express  
182    Stephanie Darcy  0264-4020-5106-5576  American Express  
199       Ryan Kennedy  3166-6287-6242-7207  American Express

3\. **CSV files with Pandas**

Load the file from this url:

- https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

with Pandas. 

+ explore and print the DataFrame
+ calculate, using `groupby()`, the average value of each feature, separately for each class
+ save the file in a JSON format.

In [137]:
data  = pd.read_csv('mushrooms_categorized.csv')
data

class  cap-shape  cap-surface  cap-color  bruises  odor  \
0         1          5            2          4        1     6   
1         0          5            2          9        1     0   
2         0          0            2          8        1     3   
3         1          5            3          8        1     6   
4         0          5            2          3        0     5   
...     ...        ...          ...        ...      ...   ...   
8119      0          3            2          4        0     5   
8120      0          5            2          4        0     5   
8121      0          2            2          4        0     5   
8122      1          3            3          4        0     8   
8123      0          5            2          4        0     5   

      gill-attachment  gill-spacing  gill-size  gill-color  ...  \
0                   1             0          1           4  ...   
1                   1             0          0           4  ...   
2                   1             0          0           5  ...   
3                   1             0          1           5  ...   
4                   1             1          0           4  ...   
...               ...           ...        ...         ...  ...   
8119                0             0          0          11  ...   
8120                0             0          0          11  ...   
8121                0             0          0           5  ...   
8122                1             0          1           0  ...   
8123                0             0          0          11  ...   

      stalk-surface-below-ring  stalk-color-above-ring  \
0                            2                       7   
1                            2                       7   
2                            2                       7   
3                            2                       7   
4                            2                       7   
...                        ...                     ...   
8119                         2                       5   
8120                         2                       5   
8121                         2                       5   
8122                         1                       7   
8123                         2                       5   

      stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
0                          7          0           2            1          4   
1                          7          0           2            1          4   
2                          7          0           2            1          4   
3                          7          0           2            1          4   
4                          7          0           2            1          0   
...                      ...        ...         ...          ...        ...   
8119                       5          0           1            1          4   
8120                       5          0           0            1          4   
8121                       5          0           1            1          4   
8122                       7          0           2            1          0   
8123                       5          0           1            1          4   

      spore-print-color  population  habitat  
0                     2           3        5  
1                     3           2        1  
2                     3           2        3  
3                     2           3        5  
4                     3           0        1  
...                 ...         ...      ...  
8119                  0           1        2  
8120                  0           4        2  
8121                  0           1        2  
8122                  7           4        2  
8123                  4           1        2  

[8124 rows x 23 columns]

In [138]:
dataGroupBy = data.groupby(['class']).mean()
dataGroupBy.to_json("mushrooms_categorized.json", orient="columns")
dataGroupBy

cap-shape  cap-surface  cap-color   bruises      odor  gill-attachment  \
class                                                                           
0       3.266160     1.615970   4.581749  0.653992  4.334601         0.954373   
1       3.436159     2.055158   4.421859  0.159346  3.940756         0.995403   

       gill-spacing  gill-size  gill-color  stalk-shape  ...  \
class                                                    ...   
0          0.285171   0.068441    6.622624     0.615970  ...   
1          0.028601   0.567926    2.863636     0.514811  ...   

       stalk-surface-below-ring  stalk-color-above-ring  \
class                                                     
0                      1.798479                6.098859   
1                      1.394280                5.512768   

       stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
class                                                                          
0                    6.064639        0.0    1.931559     1.125475   3.007605   
1                    5.504597        0.0    2.002043     1.009193   1.522983   

       spore-print-color  population   habitat  
class                                           
0               3.201521    3.283270  1.148289  
1               4.021450    4.031665  1.895812  

[2 rows x 22 columns]

4\. **Reading the credit card numbers**

Get the binary file named *credit_card.dat* from this address:

- https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

and convert the data into the real credit card number, knowing that:
- each line corresponds to a credit card number, which consists of 16 characters (which are numbers in the 0-9 range) divided in 4 blocks, with a whitespace between each block
- each character is written using a 6 bit binary representation (including the whitespace)
- the final 4 bits of each line are a padding used to determine the end of the line, and can be ignored

*Hint*: convert the binary numbers to the decimal representation first, and then use the `chr()` function to convert the latter to a char

In [139]:
#load the txt file of the previous point and convert it to a csv file by hand.
out_file_name = "credit_card.dat"

with open(out_file_name, 'r') as outfile:
  for line in outfile:
    print(''.join([chr(int(line[i:i+6],2)) for i in range(0, len(line), 6)]))


7648 5673 3775 2271

3257 8247 3354 2266

2722 0001 4011 6652

0661 3063 3742 3150

0432 1608 1462 4742

5827 2027 8785 7303

5774 8528 2087 1117

8140 1210 6352 2845

5764 1133 7301 7100

6456 1737 4126 6726

1228 8631 7382 0000

7051 0160 5374 3166

0618 3587 1630 6376

1545 5454 7444 5636

6735 3116 3202 6834

7287 5011 1547 8413

7033 2607 3328 4200

2568 5244 1874 5024

1684 2253 7570 7118

0672 2576 0575 6631

6332 8353 8787 1340

1813 3361 1175 4211

2477 6450 8840 2368

5512 3505 2563 1326

3083 7882 0621 0025

4521 5148 8045 0334

7563 3654 8713 5787

8324 2664 0476 5561

0565 2504 7168 3510

5107 5507 1767 0738

2462 1821 2448 1443

2788 0638 6861 6554

5851 5873 5474 0547

0670 1004 4013 2655

5874 5506 3048 0806

2805 5401 8462 1260

5083 8406 6310 1862

1076 1445 3013 2266

8440 4804 4844 5277

4758 6141 0686 1387

7586 0675 0315 2568

2544 1258 7432 5165

3474 5023 4434 5626

1410 0270 0434 5086

7315 4446 1104 4215

0224 7742 8300 0266

0170 2700 3145 0640

2006 2437 805

5\. **Write data to a binary file**

a) Start from the `data/data_000637.txt` file that we have used during the previous lectures, and convert it to a binary file according to the format defined below:

In [140]:
#from IPython.display import Image
#Image("images/data_format.png")

*Hints*:
- Read the first 10 lines using Pandas
- Iterate over the DataFrame rows
- For every row, ``pack'' the values (features) into a single 64-bit word, according to the format specified above. Use bit-wise shifts and operators to do so.
- Write each 64-bit word to a binary file. You can use `struct` in this way:
```
binary_file.write( struct.pack('<q', word) )
```
where `word` is the 64-bit word.
- Close the file after completing the loop.

b) Check that the binary file is correctly written by reading it with the code used in the lecture `06_OSEMN.ipynb`, and verify that the content of the `txt` and binary files is consistent.

c) What is the difference of the size on disk between equivalent `txt` and binary files?

In [141]:
data637 = pd.read_csv('data_000637.txt', nrows = 10)
data637

HEAD  FPGA  TDC_CHANNEL   ORBIT_CNT  BX_COUNTER  TDC_MEAS
0     1     0          123  3869200167        2374        26
1     1     0          124  3869200167        2374        27
2     1     0           63  3869200167        2553        28
3     1     0           64  3869200167        2558        19
4     1     0           64  3869200167        2760        25
5     1     0           63  3869200167        2762         4
6     1     0           61  3869200167        2772        14
7     1     0          139  3869200167        2776         0
8     1     0           62  3869200167        2774        21
9     1     0           60  3869200167        2788         7

In [142]:
#------------------------------------- Question a ---------------------------------------

out_file_name = "binary_file.dat"

with open(out_file_name, 'wb') as binary_file:
  for line in data637.values : 
    word = (line[5] << 0 ) 
    word += (line[4] << 5 ) 
    word += (line[3] << 17) 
    word += (line[2] << 49) 
    word += (line[1] << 58)
    word += (line[0] << 62)

    binary_file.write( struct.pack('<q', word) )

In [143]:
#------------------------------------- Question b ---------------------------------------
data = {}
columns = ['HEAD', 'FPGA', 'CHANNEL', 'ORBIT_CNT', 'BX_CNT', 'TDC_MEAS']
df = pd.DataFrame({}, columns=columns)

with open('binary_file.dat', 'rb') as file:
    file_content = file.read()
    word_counter = 0
    word_size = 8 # size of the word in bytes
    for i in range(0, len(file_content), word_size):
        word_counter += 1
        if word_counter > 10: break
        word = struct.unpack('<q', file_content[i : i + word_size])[0] # get an 8-byte word
        head     = (word >> 62) & 0x3
        fpga     = (word >> 58) & 0xF
        tdc_chan = (word >> 49) & 0x1FF
        orb_cnt  = (word >> 17) & 0xFFFFFFFF
        bx       = (word >> 5 ) & 0xFFF
        tdc_meas = (word >> 0 ) & 0x1F
        entry = {'HEAD' : head, 'FPGA' : fpga, 'CHANNEL' : tdc_chan, 'ORBIT_CNT' : orb_cnt, 'BX_CNT' : bx, 'TDC_MEAS' : tdc_meas}
        df = df.append(entry, ignore_index=True)

df

HEAD FPGA CHANNEL   ORBIT_CNT BX_CNT TDC_MEAS
0    1    0     123  3869200167   2374       26
1    1    0     124  3869200167   2374       27
2    1    0      63  3869200167   2553       28
3    1    0      64  3869200167   2558       19
4    1    0      64  3869200167   2760       25
5    1    0      63  3869200167   2762        4
6    1    0      61  3869200167   2772       14
7    1    0     139  3869200167   2776        0
8    1    0      62  3869200167   2774       21
9    1    0      60  3869200167   2788        7

Yes the content of both the Txt file and Binary file is consistent 

In [144]:
#------------------------------------- Question b ---------------------------------------
# What is the difference of the size on disk between equivalent txt and binary files?

* Size of the text file on disk is 312 byte 
* Size of the Binary file on disk is 80 byte 
* Size(Binary file) << Size (Text file)
----

* In text file, text, character, numbers are stored one character per byte i.e. 32667 occupies 5 bytes even though it occupies 2 bytes in memory.

In [145]:
data637.to_csv('text_file.txt', sep=' ', index=False)
file_size = 0
with open('text_file.txt', 'r') as file:
  for i in file:
    file_size += len(i)
print('The size of the binary file calculated by Os module: ', os.stat('text_file.txt').st_size, 'bytes')
print('The size of the binary file calculated manually : ',file_size, 'bytes')

The size of the binary file calculated by Os module:  312 bytes
The size of the binary file calculated manually :  312 bytes


* In binary file data is stored in binary format and each data would occupy the same number of bytes on disks as it occupies in memory.

In [146]:
print('The size of the binary file calculated by Os module: ', os.stat('binary_file.dat').st_size, 'bytes')
print('The size of the binary file calculated manually : ', word_counter * word_size, 'bytes')

The size of the binary file calculated by Os module:  80 bytes
The size of the binary file calculated manually :  80 bytes



* In the text file, the newline character is converted to carriage-return/linefeed before being written to the disk.
* In binary file, conversion of newline to carriage-return and linefeed does not take place.

* In the text file, a special character whose ASCII value is 26 inserted after the last character to mark the end of file.
* In the binary file no such character is present. Files keep track of the end of the file from the number of characters present.