In [1]:
import pandas as pd
import numpy as np
import json
import struct

1\. **Text files**

Perform the following operations on plain `txt` files:

+ create a list of integrer numbers and then save it to a text file named `data_int.txt`. Run the `cat` command to print the content of the file.
+ create a matrix of 5x5 floats and then save it to a text file named `data_float.txt`. Use the `cat` command to print the content of the file.
+ load the `txt` file of the previous point and convert it to a `csv` file by hand.

In [2]:
# List of integrer numbers

numbers = range(1,5)

# save the list in a text file named data_int.txt
f = open("data_int.txt", 'w')
for i in numbers:
  f.write(str(i) + '\n') 
f.close()

#  Cat command to print the content of the file.
!cat data_int.txt

1
2
3
4


In [3]:
# create a matrix of 5x5 floatsX 

floatmat = np.random.random(size=(5,5))

# save it to a text file named data_int.txt

f = open("data_float.txt", 'w')
for i in floatmat:
    f.write(str(i) + '\n') 
f.close()

# cat command to print the content of the file.
!cat data_float.txt

[0.59798252 0.51591308 0.70868037 0.37467253 0.84238919]
[0.83471762 0.26465901 0.51794209 0.65953314 0.23321389]
[0.36116384 0.85562949 0.93029944 0.27255625 0.46060238]
[0.32712509 0.48736242 0.56608798 0.73006599 0.95982929]
[0.80740053 0.90509798 0.45683737 0.88013326 0.29146758]


In [4]:
# load the txt file of the previous point
data = pd.DataFrame()
f = open("data_float.txt", 'r')

# convert it to a csv file by hand.
for i in f:
  data = data.append(pd.Series(i[1:-2].split()), ignore_index = True)
f.close()
data

/tmp/ipykernel_57211/1447469041.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(pd.Series(i[1:-2].split()), ignore_index = True)
/tmp/ipykernel_57211/1447469041.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(pd.Series(i[1:-2].split()), ignore_index = True)


0           1           2           3           4
0  0.59798252  0.51591308  0.70868037  0.37467253  0.84238919
1  0.83471762  0.26465901  0.51794209  0.65953314  0.23321389
2  0.36116384  0.85562949  0.93029944  0.27255625  0.46060238
3  0.32712509  0.48736242  0.56608798  0.73006599  0.95982929
4  0.80740053  0.90509798  0.45683737  0.88013326  0.29146758

f2\. **JSON files**

Load the file *user_data.json*, which can be found at:

- https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

and filter the data by the "CreditCardType" when it equals to "American Express". Than save the data to a new CSV file.

In [5]:
!wget https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

--2022-12-02 20:15:05--  https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json
Resolving www.dropbox.com (www.dropbox.com)... 162.125.69.18, 2620:100:6025:18::a27d:4512
Connecting to www.dropbox.com (www.dropbox.com)|162.125.69.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/raw/sz5klcdpckc39hd/user_data.json [following]
--2022-12-02 20:15:05--  https://www.dropbox.com/s/raw/sz5klcdpckc39hd/user_data.json
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc8cd7280656a9b9402d33092b39.dl.dropboxusercontent.com/cd/0/inline/Bx7v9aio69rv74blVS0ITTQ8k4073qmrah8ViUKCntkQdpZn05XsJ6I8u1e3sySHbx0OxjyVnuV1ju3bUULGVkNVpX7bUIS1JPg2YjAs0Cs2NKBRx4funOTnZZ0D2k1I3K5rTvYgE47euw6_dwEyd3_2SMoXZttEV11rPPNUDzE_Uw/file# [following]
--2022-12-02 20:15:06--  https://uc8cd7280656a9b9402d33092b39.dl.dropboxusercontent.com/cd/0/inline/Bx7v9aio69rv74blVS0ITTQ8k4073qmrah8ViUKCntkQdpZn05XsJ6I8u1e3sySHbx0Oxjy

In [6]:
data = json.load(open('user_data.json'))

#Create a DataFrame object
df = pd.DataFrame()

for i in data :
  df = df.append(pd.Series(i.values()), ignore_index = True)

df.columns = data[0].keys()
df = df.set_index(df.columns[0])

#  filter the data by the "CreditCardType" when it equals to "American Express". Than save the data to a new CSV file.
df[df["CreditCardType"] == 'American Express'] .to_csv('user_data.csv')

/tmp/ipykernel_57211/3147750325.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.Series(i.values()), ignore_index = True)
/tmp/ipykernel_57211/3147750325.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.Series(i.values()), ignore_index = True)


3\. **CSV files with Pandas**

Load the file from this url:

- https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

with Pandas. 

+ explore and print the DataFrame
+ calculate, using `groupby()`, the average value of each feature, separately for each class
+ save the file in a JSON format.

In [37]:
!wget https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

--2022-12-01 16:07:38--  https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv
Resolving www.dropbox.com (www.dropbox.com)... 162.125.1.18, 2620:100:6016:18::a27d:112
Connecting to www.dropbox.com (www.dropbox.com)|162.125.1.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/raw/kgshemfgk22iy79/mushrooms_categorized.csv [following]
--2022-12-01 16:07:38--  https://www.dropbox.com/s/raw/kgshemfgk22iy79/mushrooms_categorized.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc4013c7f8a138eb588e2fd2634c.dl.dropboxusercontent.com/cd/0/inline/BxxkU241B9Cfu8SxrxU_zPxFh_tMsJc-pBIsjr8ZJOtinXrYddLEj0r6i112ZrQJeWg4Wv6wa9WMST1k6FEUkl3GrqLUp7LbdYPLEcwTrT-gURj-OK8FZ7h_RAnRPHFgZSxpP6uYWEPOT-AZTjmDnLbXAQFqxhLxG-r6k5WjaEiH9A/file# [following]
--2022-12-01 16:07:38--  https://uc4013c7f8a138eb588e2fd2634c.dl.dropboxusercontent.com/cd/0/inline/BxxkU241B9Cfu8SxrxU_zPxFh_tMsJc-pBIsjr8ZJ

In [ ]:
# explore and print the DataFrame
df  = pd.read_csv('mushrooms_categorized.csv')
df

In [40]:
# calculate, using groupby(), the average value of each feature, separately for each class
class_groups = df.groupby(['class']).mean()
# save the file in a JSON format.
class_groups.to_json("mushrooms_categorized.json", orient="columns")
class_groups

      class  cap-shape  cap-surface  cap-color  bruises  odor  \
0         1          5            2          4        1     6   
1         0          5            2          9        1     0   
2         0          0            2          8        1     3   
3         1          5            3          8        1     6   
4         0          5            2          3        0     5   
...     ...        ...          ...        ...      ...   ...   
8119      0          3            2          4        0     5   
8120      0          5            2          4        0     5   
8121      0          2            2          4        0     5   
8122      1          3            3          4        0     8   
8123      0          5            2          4        0     5   

      gill-attachment  gill-spacing  gill-size  gill-color  ...  \
0                   1             0          1           4  ...   
1                   1             0          0           4  ...   
2                 

4\. **Reading the credit card numbers**

Get the binary file named *credit_card.dat* from this address:

- https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

and convert the data into the real credit card number, knowing that:
- each line corresponds to a credit card number, which consists of 16 characters (which are numbers in the 0-9 range) divided in 4 blocks, with a whitespace between each block
- each character is written using a 6 bit binary representation (including the whitespace)
- the final 4 bits of each line are a padding used to determine the end of the line, and can be ignored

*Hint*: convert the binary numbers to the decimal representation first, and then use the `chr()` function to convert the latter to a char

In [41]:
!wget https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

--2022-12-01 16:12:07--  https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat
Resolving www.dropbox.com (www.dropbox.com)... 162.125.1.18, 2620:100:6016:18::a27d:112
Connecting to www.dropbox.com (www.dropbox.com)|162.125.1.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/raw/8m0syw2tkul3dap/credit_card.dat [following]
--2022-12-01 16:12:07--  https://www.dropbox.com/s/raw/8m0syw2tkul3dap/credit_card.dat
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc10d832e752a3591d07f7c4370e.dl.dropboxusercontent.com/cd/0/inline/BxzKsMq5Bz8VX4iWhs828wDHAfqnuN6OxV8ycAOhdYTYamhMkBOWZyEivlAg4MuqKal_O_YbG3759I04C8Zvnga9TSWAY2shC_YPo42tbtMA2d8I_uGYm2jsMYfeVqzrYAl97bg9XA0PWVR4VvS6aQ9J37iW1bSW0v0EXAymXZhKBw/file# [following]
--2022-12-01 16:12:08--  https://uc10d832e752a3591d07f7c4370e.dl.dropboxusercontent.com/cd/0/inline/BxzKsMq5Bz8VX4iWhs828wDHAfqnuN6OxV8ycAOhdYTYamhMkBOWZyEivlAg4MuqKal_O_Y

In [43]:
#load the txt file of the previous point and convert it to a csv file by hand.
out_file_name = "credit_card.dat"
f =  open(out_file_name, 'r')
for i in f:
  s = ''
  for j in range(0, len(i), 6):
    s += chr(int(i[j:j+6],2))
  print(s)
f.close()

7648 5673 3775 2271

3257 8247 3354 2266

2722 0001 4011 6652

0661 3063 3742 3150

0432 1608 1462 4742

5827 2027 8785 7303

5774 8528 2087 1117

8140 1210 6352 2845

5764 1133 7301 7100

6456 1737 4126 6726

1228 8631 7382 0000

7051 0160 5374 3166

0618 3587 1630 6376

1545 5454 7444 5636

6735 3116 3202 6834

7287 5011 1547 8413

7033 2607 3328 4200

2568 5244 1874 5024

1684 2253 7570 7118

0672 2576 0575 6631

6332 8353 8787 1340

1813 3361 1175 4211

2477 6450 8840 2368

5512 3505 2563 1326

3083 7882 0621 0025

4521 5148 8045 0334

7563 3654 8713 5787

8324 2664 0476 5561

0565 2504 7168 3510

5107 5507 1767 0738

2462 1821 2448 1443

2788 0638 6861 6554

5851 5873 5474 0547

0670 1004 4013 2655

5874 5506 3048 0806

2805 5401 8462 1260

5083 8406 6310 1862

1076 1445 3013 2266

8440 4804 4844 5277

4758 6141 0686 1387

7586 0675 0315 2568

2544 1258 7432 5165

3474 5023 4434 5626

1410 0270 0434 5086

7315 4446 1104 4215

0224 7742 8300 0266

0170 2700 3145 0640

2006 2437 805

5\. **Write data to a binary file**

a) Start from the `data/data_000637.txt` file that we have used during the previous lectures, and convert it to a binary file according to the format defined below:

In [ ]:
from IPython.display import Image
Image("images/data_format.png")

*Hints*:
- Read the first 10 lines using Pandas
- Iterate over the DataFrame rows
- For every row, ``pack'' the values (features) into a single 64-bit word, according to the format specified above. Use bit-wise shifts and operators to do so.
- Write each 64-bit word to a binary file. You can use `struct` in this way:
```
binary_file.write( struct.pack('<q', word) )
```
where `word` is the 64-bit word.
- Close the file after completing the loop.

b) Check that the binary file is correctly written by reading it with the code used in the lecture `06_OSEMN.ipynb`, and verify that the content of the `txt` and binary files is consistent.

c) What is the difference of the size on disk between equivalent `txt` and binary files?

In [44]:
!wget https://www.dropbox.com/s/xvjzaxzz3ysphme/data_000637.txt

--2022-12-01 16:24:54--  https://www.dropbox.com/s/xvjzaxzz3ysphme/data_000637.txt
Resolving www.dropbox.com (www.dropbox.com)... 162.125.1.18, 2620:100:6016:18::a27d:112
Connecting to www.dropbox.com (www.dropbox.com)|162.125.1.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/raw/xvjzaxzz3ysphme/data_000637.txt [following]
--2022-12-01 16:24:54--  https://www.dropbox.com/s/raw/xvjzaxzz3ysphme/data_000637.txt
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc346d5e9ed69460728222c6cfb8.dl.dropboxusercontent.com/cd/0/inline/Bxw8mpOyvJ896VO58w1LaI2RIR_Fmwau4UHmc4NLo0bAbQkQYrv42XRvwgvZ7KUqPGb-TZa3O1KIJxjNgfTKQ1rjZX7R8q-OfGe0sxDiy7taquPnfs18QRlXnAAv6abbhxswOnWMOQmUDDJjLNTnCbda2gcAMaTiVvW-mkw7t0-xTA/file# [following]
--2022-12-01 16:24:54--  https://uc346d5e9ed69460728222c6cfb8.dl.dropboxusercontent.com/cd/0/inline/Bxw8mpOyvJ896VO58w1LaI2RIR_Fmwau4UHmc4NLo0bAbQkQYrv42XRvwgvZ7KUqPGb-TZa

In [53]:
# Read the first 10 lines using Pandas
df_1 = pd.read_csv('data_000637.txt', nrows = 10)

# Iterate over the DataFrame rows
f = open( "data_000637.dat", 'wb')
for i in df_1.values : 
  word = (i[5] << 0 ) 
  word += (i[4] << 5 ) 
  word += (i[3] << 17) 
  word += (i[2] << 49) 
  word += (i[1] << 58)
  word += (i[0] << 62)
  f.write( struct.pack('<q', word) )
f.close()

In [51]:

data = {}
columns = ['HEAD', 'FPGA', 'CHANNEL', 'ORBIT_CNT', 'BX_CNT', 'TDC_MEAS']
df = pd.DataFrame({}, columns=columns)

with open('data_000637.dat', 'rb') as file:
    file_content = file.read()
    word_counter = 0
    word_size = 8 # size of the word in bytes
    for i in range(0, len(file_content), word_size):
        word_counter += 1
        if word_counter > 10: break
        word = struct.unpack('<q', file_content[i : i + word_size])[0] # get an 8-byte word
        head     = (word >> 62) & 0x3
        fpga     = (word >> 58) & 0xF
        tdc_chan = (word >> 49) & 0x1FF
        orb_cnt  = (word >> 17) & 0xFFFFFFFF
        bx       = (word >> 5 ) & 0xFFF
        tdc_meas = (word >> 0 ) & 0x1F
        #if i == 0: print ('{0}\t{1}\t{2}\t{3}\t{4}\t{5}'.format('HEAD', 'FPGA', 'CHANNEL', 'ORBIT_CNT', 'BX_CNT', 'TDC_MEAS'))
        #print('{0}\t{1}\t{2}\t{3}\t{4}\t{5}'.format(head, fpga, tdc_chan, orb_cnt, bx, tdc_meas))
        entry = {'HEAD' : head, 'FPGA' : fpga, 'CHANNEL' : tdc_chan, 'ORBIT_CNT' : orb_cnt, 'BX_CNT' : bx, 'TDC_MEAS' : tdc_meas}
        df = df.append(entry, ignore_index=True)

In [60]:
import os
df_1.to_csv('data637.txt', sep=' ', index=False)
print('The size of the Text file: ', os.stat('data637.txt').st_size, 'bytes')
print('The size of the binary file', os.stat('binary_file.dat').st_size, 'bytes \n')
print("The size of the text file is bigger than the size of binary file because each chacter in\ntext file occupies 1 bytes in memory while in the binary file\neach word occupies 8 bytes .")

The size of the Text file:  312 bytes
The size of the binary file 80 bytes 

The size of the text file is bigger than the size of binary file because each chacter in
text file occupies 1 bytes in memory while in the binary file
each word occupies 8 bytes .
