1\. **Reductions**

Find the total mean, and the mean for each row and column of the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [2]:
import numpy as np
m = np.arange(12).reshape((3,4))
s = list(m.shape)

mean_row = np.sum(m,axis=1)/(s[1])
mean_col = np.sum(m,axis=0)/(s[0])
mean = np.sum(m)/(s[0]*s[1])
print(m)
print("The mean value on the row: ", mean_row)
print("The mean value on the column: ", mean_col)
print("The mean value on the matrix: ", mean)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
The mean value on the row:  [1.5 5.5 9.5]
The mean value on the column:  [4. 5. 6. 7.]
The mean value on the matrix:  5.5


2\. **Outer product**

Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [3]:
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])

# 1. using outer function
p_1 = np.outer(u,v,out=None)

#2. for loop
p_2 = np.eye(4,4)
for i in range(u.size):
    for j in range(v.size):
        p_2[i][j] = u[i]*v[j]
        
#3. using broadcasting
p_3 = u[:,np.newaxis]*v
    
    
print("The outer product using outer function is : ", p_1)
print("The outer product using for loop is : ", p_2)
print("The outer product using numpy broadcasting operations is : ", p_3)

The outer product using outer function is :  [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
The outer product using for loop is :  [[ 2.  4.  6.  8.]
 [ 6. 12. 18. 24.]
 [10. 20. 30. 40.]
 [14. 28. 42. 56.]]
The outer product using numpy broadcasting operations is :  [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. **Matrix masking**

Create a 10 by 6 matrix of float random numbers, distributed between 0 and 3 according to a flat distribution.

After creating the matrix, set all entries $< 0.3$ to zero using a mask.

In [4]:
import numpy.random as npr

r = 3*npr.rand(10,6)
mask = (r < 0.3)
#print(mask)
print("Original matrix: \n",r)

for i in range(10):
    for j in range(6):
        if mask[i,j]:
            #print(mask[i,j])
            r[i,j] = 0
            #print(r[i,j])
filtered = r
print("Filtered matrix: \n",filtered)



Original matrix: 
 [[1.97985885 1.44284232 0.23951882 0.58541068 2.00634815 0.41278806]
 [0.69514506 0.3940859  1.40598852 0.8936412  1.69932543 2.88312499]
 [2.56994789 0.80107614 2.14702205 1.70995751 1.79779379 2.46468428]
 [2.34054205 1.8874955  0.10255335 2.9537821  0.94461209 1.05442024]
 [0.55608872 0.24636465 1.9263314  1.35044452 0.06286793 1.17040102]
 [0.02236549 0.89338244 2.95021022 0.41609749 2.81088639 1.83160749]
 [0.79886573 0.81980767 2.68435706 0.54870705 1.4565879  2.04399042]
 [1.69166824 1.25840199 2.64267642 1.64869636 1.33186    1.19640818]
 [0.01761525 0.00774908 0.74795986 1.38682648 2.13619586 2.92603205]
 [1.14890778 0.87613762 0.34953483 2.08568117 2.29618819 0.21281   ]]
Filtered matrix: 
 [[1.97985885 1.44284232 0.         0.58541068 2.00634815 0.41278806]
 [0.69514506 0.3940859  1.40598852 0.8936412  1.69932543 2.88312499]
 [2.56994789 0.80107614 2.14702205 1.70995751 1.79779379 2.46468428]
 [2.34054205 1.8874955  0.         2.9537821  0.94461209 1.05442

4\. **Trigonometric functions**

Use `np.linspace` to create an array of 100 numbers between $0$ and $2\pi$ (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the `sin` and `cos` functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

In [5]:
import math
arr = np.linspace(0,2*np.pi,100)
#a
a = np.ones(10)
for i in range(10):
    a[i] = (arr[i*10])
    #print(arr[i*10])
print("Every 10th element: \n",a)

#b
b = arr[::-1]
print("Reversed array: \n",b)

#c
print("These are the values which satisfy the request: ")
print ("{:<30} {:<20}".format('Absolute difference','Value'))

    
for i in range(arr.size):
    if(abs(math.sin(arr[i])-math.cos(arr[i])) < 0.1):
        print ("{:<30} {:<20}".format(abs(math.sin(arr[i])-math.cos(arr[i])),arr[i]))

Every 10th element: 
 [0.         0.63466518 1.26933037 1.90399555 2.53866073 3.17332591
 3.8079911  4.44265628 5.07732146 5.71198664]
Reversed array: 
 [6.28318531 6.21971879 6.15625227 6.09278575 6.02931923 5.96585272
 5.9023862  5.83891968 5.77545316 5.71198664 5.64852012 5.58505361
 5.52158709 5.45812057 5.39465405 5.33118753 5.26772102 5.2042545
 5.14078798 5.07732146 5.01385494 4.95038842 4.88692191 4.82345539
 4.75998887 4.69652235 4.63305583 4.56958931 4.5061228  4.44265628
 4.37918976 4.31572324 4.25225672 4.1887902  4.12532369 4.06185717
 3.99839065 3.93492413 3.87145761 3.8079911  3.74452458 3.68105806
 3.61759154 3.55412502 3.4906585  3.42719199 3.36372547 3.30025895
 3.23679243 3.17332591 3.10985939 3.04639288 2.98292636 2.91945984
 2.85599332 2.7925268  2.72906028 2.66559377 2.60212725 2.53866073
 2.47519421 2.41172769 2.34826118 2.28479466 2.22132814 2.15786162
 2.0943951  2.03092858 1.96746207 1.90399555 1.84052903 1.77706251
 1.71359599 1.65012947 1.58666296 1.52319644

5\. **Matrices**

Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [6]:
u = np.arange(1, 11)
m = u[:,np.newaxis]*u
print(m)
print("The trace of the matrix m is : ", np.matrix.trace(m))
m_rev = m[::-1]
print("The anit-diagonal of the matrix m is : ", np.matrix.diagonal(m[::-1]))
print("The diagonal with offset by one of m is : ", np.matrix.diagonal(m,offset=1))

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
The trace of the matrix m is :  385
The anit-diagonal of the matrix m is :  [10 18 24 28 30 30 28 24 18 10]
The diagonal with offset by one of m is :  [ 2  6 12 20 30 42 56 72 90]


6\. **Broadcasting**

Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles.

The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [7]:
print ("Chicago ", "Springfield ", "Saint-Louis ", "Tulsa ", "Oklahoma City ", "Amarillo ", "Santa Fe ", "Albuquerque ", "Flagstaff ", "Los Angeles")
#print ("Chicago ", "Springfield ", "Saint-Louis ", "Tulsa ", "Oklahoma City ", "Amarillo ", "Santa Fe ", "Albuquerque ", "Flagstaff ", "Los Angeles")

miles = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])
k = 1.609
km = np.array([x*k for x in miles])

d_miles = abs(miles[:,np.newaxis]-miles)
d_km = np.round(abs(km[:,np.newaxis]-km),1)

print("Distances in miles: ",miles)
print("Distances in km: ", km)

#2D grid of distances among each city in miles 
print("Grid of istances for miles: \n",d_miles)
#2D grid of distances among each city in kms 
print(f"Grid of istances for km: \n %{d_km}")



Chicago  Springfield  Saint-Louis  Tulsa  Oklahoma City  Amarillo  Santa Fe  Albuquerque  Flagstaff  Los Angeles
Distances in miles:  [   0  198  303  736  871 1175 1475 1544 1913 2448]
Distances in km:  [   0.     318.582  487.527 1184.224 1401.439 1890.575 2373.275 2484.296
 3078.017 3938.832]
Grid of istances for miles: 
 [[   0  198  303  736  871 1175 1475 1544 1913 2448]
 [ 198    0  105  538  673  977 1277 1346 1715 2250]
 [ 303  105    0  433  568  872 1172 1241 1610 2145]
 [ 736  538  433    0  135  439  739  808 1177 1712]
 [ 871  673  568  135    0  304  604  673 1042 1577]
 [1175  977  872  439  304    0  300  369  738 1273]
 [1475 1277 1172  739  604  300    0   69  438  973]
 [1544 1346 1241  808  673  369   69    0  369  904]
 [1913 1715 1610 1177 1042  738  438  369    0  535]
 [2448 2250 2145 1712 1577 1273  973  904  535    0]]
Grid of istances for km: 
 %[[   0.   318.6  487.5 1184.2 1401.4 1890.6 2373.3 2484.3 3078.  3938.8]
 [ 318.6    0.   168.9  865.6 1082.9 1572

7\. **Prime numbers sieve**

Compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).

  * Constract a shape (N,) boolean array, which is the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (with `timeit`); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [8]:
import timeit

N = 99
u = np.linspace(0,N,N+1)
primes = []
#print(u)

start_time = timeit.default_timer()
mask = [(all(x % y != 0 for y in range(2, x))) for x in range(2, len(u))]

for i in range(2,len(mask)):
    if mask[i]:
        primes.append(u[i])

end_time = timeit.default_timer()
time = end_time - start_time

print("The mask: \n",mask)
print("Prime numbers are: ", primes )
print("Time of the algorithm: ", time)



The mask: 
 [True, True, False, True, False, True, False, False, False, True, False, True, False, False, False, True, False, True, False, False, False, True, False, False, False, False, False, True, False, True, False, False, False, False, False, True, False, False, False, True, False, True, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, True, False, True, False, False, False, False, False, True, False, False, False, True, False, True, False, False, False, False, False, True, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, True, False, False]
Prime numbers are:  [3.0, 5.0, 9.0, 11.0, 15.0, 17.0, 21.0, 27.0, 29.0, 35.0, 39.0, 41.0, 45.0, 51.0, 57.0, 59.0, 65.0, 69.0, 71.0, 77.0, 81.0, 87.0, 95.0]
Time of the algorithm:  0.0002488999998604413


8\. **Diffusion using random walk**

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of many random walkers after a given amount of time.

*Hint*: create a 2D array where each row represents a walker, and each column represents a time step.

  * Take 1000 walkers and let them walk for 200 steps
  * Use `randint` to create a 2D array of size $walkers \times steps$ with values -1 or 1
  * Calculate the walking distances for each walker (e.g. by summing the elements in each row)
  * Take the square of the previously-obtained array (element-wise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * **Optional**: plot the average distances ($\sqrt(distance^2)$) as a function of time (step)

In [40]:
number_walkers = 10
steps = 5
u = npr.randint(-1,2, size = (number_walkers,steps)) #initializing an array with 1000 walkers and 200 steps
print(u)

total_dist = []
mean_dist = []
v = np.ones((number_walkers,steps)) #list containing the squared distances
total_dist.append(np.sum(u,axis=1)) #distances for each walker

for i in range(len(total_dist)):
    total_dist[i]=total_dist[i]**2
print("Distances for walker: ",total_dist[0])

#mean squared distances at each step 
v=u*u
#print(v)   
mean_dist.append(np.sum(v,axis=0)/number_walkers) #sum of the squares on each column

for i in (range(len(mean_dist))):
    a = mean_dist[0][i]
    mean_dist[0][i] = np.round(math.sqrt(a),2)

print("Squared distances at each step: ",mean_dist[0])




[[ 0 -1  1 -1 -1]
 [ 0  1  1 -1 -1]
 [ 0  0  0  0 -1]
 [-1  0  1  0 -1]
 [-1  1  0  1 -1]
 [ 1 -1  1  0 -1]
 [-1  1 -1  0  0]
 [ 1  0  1  0 -1]
 [-1  1  1 -1  1]
 [ 0  1  0  0  1]]
Distances for walker:  [4 0 1 1 0 0 1 1 1 4]
Squared distances at each step:  [0.77 0.7  0.7  0.4  0.9 ]
