In [10]:
###########Esercizio 1
import numpy as np
import math
from numpy import random
m = np.arange(12).reshape((3,4))
tMean=m.mean()
colMean=m.mean(0)
rowMean=m.mean(1)
print("the mean for each row is : ",rowMean,"\n")
print("the mean for each column is ",colMean,'\n')
print("the mean of total array is : ",tMean,"\n")
#another way to compute  total mean
ta=sum(sum(m[:,:]))/12
print("using another way ",ta,"\n")
############# Esercizio 2
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
outerP1=np.outer(u,v)
print("outer product using oter method : ","\n",outerP1,"\n")
o=[]
for i in u :
    for j in v :
        o.append(i*j)
o=np.array(o)
print("outer product using two nested for loops: \n",o.reshape(4,4),"\n")

###################################################### Esercizio 3
z=np.random.uniform(0.0,3.0,(10,6))
print(" before  \n",z)
z[z<0.3]=0

print("after \n",z)
################################## Esercizio 4

k=np.linspace(0,2*(math.pi),100)
print("linspace : \n", k)
result= k[::10]
print("\n Every 10th elements : \n",result)
#######
print("reversed : \n",k[100:0:-1])
#######
mask=(abs(np.sin(k)-np.cos(k))>0.3)
print("the mask is : \n",mask)
print(" element which sin - cos more than 0.3 are \n ",k[mask])


the mean for each row is :  [1.5 5.5 9.5] 

the mean for each column is  [4. 5. 6. 7.] 

the mean of total array is :  5.5 

using another way  5.5 

outer product using oter method :  
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]] 

outer product using two nested for loops: 
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]] 

 before  
 [[2.06517711 2.65423104 1.93166729 0.57989735 2.0471326  0.88415053]
 [2.21783881 0.09626867 2.24938224 1.47969626 0.91703737 0.07801403]
 [1.39867112 1.43301297 2.19662209 0.60526597 0.89658152 2.45084297]
 [1.7619686  0.54745438 2.18072336 2.5892574  1.6131428  0.37921645]
 [1.68902786 1.29450463 0.33281323 2.40385832 1.39828404 2.01786223]
 [2.56749065 0.49405911 1.43917516 1.06438725 1.4399048  1.67078278]
 [0.49411193 2.92571345 1.87342366 1.37713888 2.6142631  0.52931394]
 [2.44998053 1.8745753  2.21131964 0.92737322 1.24753172 1.89379315]
 [1.42293816 1.2224725  0.3554881  1.5084649  0.24890981 0.74565792]
 [2.8745278