In [1]:
import pandas as pd
import numpy as np
import numpy.random as npr
import json

1\. **Text files**

Perform the following operations on plain `txt` files:

+ create a list of integrer numbers and then save it to a text file named `data_int.txt`. Run the `cat` command to print the content of the file.
+ create a matrix of 5x5 floats and then save it to a text file named `data_float.txt`. Use the `cat` command to print the content of the file.
+ load the `txt` file of the previous point and convert it to a `csv` file by hand.

In [56]:
random_ints = npr.randint(1, 50, 15)
print(">> Random ints =", random_ints)
data_int_file = "data/data_int.txt"

with open(data_int_file, 'w') as f:
    f.write(str(random_ints))

# !cat data/data_int.txt

matrix_5float = np.random.uniform(1, 15, (5, 5))
print(">> 5x5 matrix =\n", matrix_5float)
data_float_file = "data/data_float.txt"

with open(data_float_file, 'w') as f:
    f.write(str(matrix_5float))

# !cat data/data_float.txt
data_csv_file = "data/data_float.csv"

with open(data_float_file, 'r') as f:
    with open(data_csv_file, 'w') as c:
        for line in f:
            modifyFile = line.replace("[", "")
            modifyFile = modifyFile.replace("]", "")
            modifyFile = modifyFile.split()
            modifyFile = ",".join(modifyFile) + ","
            c.write(modifyFile)


>> Random ints = [17 30 29 46 49 33  8 36 25 43 15 28 29 35  2]
>> 5x5 matrix =
 [[ 4.44311973 10.55676349  4.8346619   6.79624693  1.56321262]
 [13.92821619 11.2533013  10.20458772  8.81496831  3.51022775]
 [ 6.23957862  3.3676718   8.76270538 12.16767256 11.2365988 ]
 [ 5.14100374 10.46201097  6.34097118  5.38553519  1.89527785]
 [ 6.81879613 10.20357651  6.15147776  3.40913744  7.54651068]]


2\. **JSON files**

Load the file *user_data.json*, which can be found at:

- https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

and filter the data by the "CreditCardType" when it equals to "American Express". Than save the data to a new CSV file.

In [69]:
#!wget "https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json" -P data/
data_json_file = "data/user_data.json"

data = pd.read_json(data_json_file)

print(">> User data:\n",data)

data = data[data['CreditCardType'] == "American Express"]

data.to_csv("data/user_data.csv")


>> User data:
       ID             JobTitle                    EmailAddress  \
0      1      Project Manager    Remy_Crawford1065@typill.biz   
1      2  Investment  Advisor    Clint_Thorpe5003@bulaffy.com   
2      3                 Cook   Russel_Hooper9403@bulaffy.com   
3      4      Business Broker   Benjamin_Rowan6280@gembat.biz   
4      5         Loan Officer       Matt_Lloyd3241@guentu.biz   
..   ...                  ...                             ...   
195  196         Loan Officer        Wade_Khan6086@twipet.com   
196  197                 Cook         Ally_Rose8531@twace.org   
197  198     Machine Operator      Harvey_Moore7505@extex.org   
198  199  Investment  Advisor      Ryan_Kennedy5565@corti.com   
199  200          Stockbroker  Michaela_Murphy8359@ovock.tech   

    FirstNameLastName           CreditCard    CreditCardType  
0       Remy Crawford  6205-7258-7671-0612       Capital One  
1        Clint Thorpe  7083-8766-0251-2345  American Express  
2       Russel 

3\. **CSV files with Pandas**

Load the file from this url:

- https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

with Pandas. 

+ explore and print the DataFrame
+ calculate, using `groupby()`, the average value of each feature, separately for each class
+ save the file in a JSON format.

In [72]:
#!wget "https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv" -P data/
mushrooms_csv_file = "data/mushrooms_categorized.csv"
mushrooms_json_file = "data/mushrooms_categorized.json"

data = pd.read_csv(mushrooms_csv_file)

#print(">> Mushrooms data:\n", data)

average_features = data.groupby(['class'])[data.columns].mean()
average_features.to_json(mushrooms_json_file)
#print(">> Average value of each feature - Mushrooms data:\n", average_features)


>> Average value of each feature - Mushrooms data:
        class  cap-shape  cap-surface  cap-color   bruises      odor  \
class                                                                 
0        0.0   3.266160     1.615970   4.581749  0.653992  4.334601   
1        1.0   3.436159     2.055158   4.421859  0.159346  3.940756   

       gill-attachment  gill-spacing  gill-size  gill-color  ...  \
class                                                        ...   
0             0.954373      0.285171   0.068441    6.622624  ...   
1             0.995403      0.028601   0.567926    2.863636  ...   

       stalk-surface-below-ring  stalk-color-above-ring  \
class                                                     
0                      1.798479                6.098859   
1                      1.394280                5.512768   

       stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
class                                                                    

4\. **Reading the credit card numbers**

Get the binary file named *credit_card.dat* from this address:

- https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

and convert the data into the real credit card number, knowing that:
- each line corresponds to a credit card number, which consists of 16 characters (which are numbers in the 0-9 range) divided in 4 blocks, with a whitespace between each block
- each character is written using a 6 bit binary representation (including the whitespace)
- the final 4 bits of each line are a padding used to determine the end of the line, and can be ignored

*Hint*: convert the binary numbers to the decimal representation first, and then use the `chr()` function to convert the latter to a char

In [48]:
#!wget "https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat" -P data/
credit_dat = "data/credit_card.dat"
credit=[]
with open(credit_dat, 'r') as file:
    for line in file:
        block = ''
        i = 0
        while(i<len(line)):
            bin_number = '0b' + line[i:i + 6]
            block += chr(int(bin_number, 2))
            i+=6
        print(block)
        credit.append(block)
        


7648 5673 3775 2271

3257 8247 3354 2266

2722 0001 4011 6652

0661 3063 3742 3150

0432 1608 1462 4742

5827 2027 8785 7303

5774 8528 2087 1117

8140 1210 6352 2845

5764 1133 7301 7100

6456 1737 4126 6726

1228 8631 7382 0000

7051 0160 5374 3166

0618 3587 1630 6376

1545 5454 7444 5636

6735 3116 3202 6834

7287 5011 1547 8413

7033 2607 3328 4200

2568 5244 1874 5024

1684 2253 7570 7118

0672 2576 0575 6631

6332 8353 8787 1340

1813 3361 1175 4211

2477 6450 8840 2368

5512 3505 2563 1326

3083 7882 0621 0025

4521 5148 8045 0334

7563 3654 8713 5787

8324 2664 0476 5561

0565 2504 7168 3510

5107 5507 1767 0738

2462 1821 2448 1443

2788 0638 6861 6554

5851 5873 5474 0547

0670 1004 4013 2655

5874 5506 3048 0806

2805 5401 8462 1260

5083 8406 6310 1862

1076 1445 3013 2266

8440 4804 4844 5277

4758 6141 0686 1387

7586 0675 0315 2568

2544 1258 7432 5165

3474 5023 4434 5626

1410 0270 0434 5086

7315 4446 1104 4215

0224 7742 8300 0266

0170 2700 3145 0640

2006 2437 805

5\. **Write data to a binary file**

a) Start from the `data/data_000637.txt` file that we have used during the previous lectures, and convert it to a binary file according to the format defined below:

In [ ]:
from IPython.display import Image
Image("images/data_format.png")

*Hints*:
- Read the first 10 lines using Pandas
- Iterate over the DataFrame rows
- For every row, ``pack'' the values (features) into a single 64-bit word, according to the format specified above. Use bit-wise shifts and operators to do so.
- Write each 64-bit word to a binary file. You can use `struct` in this way:
```
binary_file.write( struct.pack('<q', word) )
```
where `word` is the 64-bit word.
- Close the file after completing the loop.

b) Check that the binary file is correctly written by reading it with the code used in the lecture `06_OSEMN.ipynb`, and verify that the content of the `txt` and binary files is consistent.

c) What is the difference of the size on disk between equivalent `txt` and binary files?